// Code generated by wayland-scanner. DO NOT EDIT.

package pointergesturesunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfacePointerGesturePinchV1 = "zwp_pointer_gesture_pinch_v1"
const VersionPointerGesturePinchV1 = 3

const (
	PointerGesturePinchV1RequestDestroy uint16 = 0
)

const (
	PointerGesturePinchV1EventBegin  uint16 = 0
	PointerGesturePinchV1EventUpdate uint16 = 1
	PointerGesturePinchV1EventEnd    uint16 = 2
)

// pointergesturepinchv1EventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var pointergesturepinchv1EventFDCounts = map[uint16]int{
	0: 0,
	1: 0,
	2: 0,
}

type PointerGesturePinchV1DestroyRequest struct {
}

func (r *PointerGesturePinchV1DestroyRequest) Opcode() uint16 {
	return PointerGesturePinchV1RequestDestroy
}

func (r *PointerGesturePinchV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *PointerGesturePinchV1DestroyRequest) Since() uint32 { return 1 }

type PointerGesturePinchV1BeginEvent struct {
	Serial  uint32
	Time    uint32
	Surface wire.ObjectID
	Fingers uint32
}

func (e *PointerGesturePinchV1BeginEvent) Opcode() uint16 { return PointerGesturePinchV1EventBegin }

func (e *PointerGesturePinchV1BeginEvent) Unmarshal(r *wire.Reader) error {
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	time, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Time = time
	surface, err := r.Object()
	if err != nil {
		return err
	}
	e.Surface = surface
	fingers, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Fingers = fingers
	return nil
}

func (e *PointerGesturePinchV1BeginEvent) Since() uint32 { return 1 }

type PointerGesturePinchV1UpdateEvent struct {
	Time     uint32
	Dx       wire.Fixed
	Dy       wire.Fixed
	Scale    wire.Fixed
	Rotation wire.Fixed
}

func (e *PointerGesturePinchV1UpdateEvent) Opcode() uint16 { return PointerGesturePinchV1EventUpdate }

func (e *PointerGesturePinchV1UpdateEvent) Unmarshal(r *wire.Reader) error {
	time, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Time = time
	dx, err := r.Fixed()
	if err != nil {
		return err
	}
	e.Dx = dx
	dy, err := r.Fixed()
	if err != nil {
		return err
	}
	e.Dy = dy
	scale, err := r.Fixed()
	if err != nil {
		return err
	}
	e.Scale = scale
	rotation, err := r.Fixed()
	if err != nil {
		return err
	}
	e.Rotation = rotation
	return nil
}

func (e *PointerGesturePinchV1UpdateEvent) Since() uint32 { return 1 }

type PointerGesturePinchV1EndEvent struct {
	Serial    uint32
	Time      uint32
	Cancelled int32
}

func (e *PointerGesturePinchV1EndEvent) Opcode() uint16 { return PointerGesturePinchV1EventEnd }

func (e *PointerGesturePinchV1EndEvent) Unmarshal(r *wire.Reader) error {
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	time, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Time = time
	cancelled, err := r.Int32()
	if err != nil {
		return err
	}
	e.Cancelled = cancelled
	return nil
}

func (e *PointerGesturePinchV1EndEvent) Since() uint32 { return 1 }

type PointerGesturePinchV1BeginFunc func(ev PointerGesturePinchV1BeginEvent)

type PointerGesturePinchV1UpdateFunc func(ev PointerGesturePinchV1UpdateEvent)

type PointerGesturePinchV1EndFunc func(ev PointerGesturePinchV1EndEvent)

type PointerGesturePinchV1 struct {
	proxy *wayland.Proxy
}

func NewPointerGesturePinchV1(p *wayland.Proxy) *PointerGesturePinchV1 {
	p.SetEventFDCounts(pointergesturepinchv1EventFDCounts)
	return &PointerGesturePinchV1{proxy: p}
}

func (o *PointerGesturePinchV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *PointerGesturePinchV1) OnBegin(fn PointerGesturePinchV1BeginFunc) {
	o.proxy.RegisterEvent(PointerGesturePinchV1EventBegin, func(r *wire.Reader) {
		var ev PointerGesturePinchV1BeginEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Begin", err)
			return
		}

		fn(ev)
	})
}

func (o *PointerGesturePinchV1) OnUpdate(fn PointerGesturePinchV1UpdateFunc) {
	o.proxy.RegisterEvent(PointerGesturePinchV1EventUpdate, func(r *wire.Reader) {
		var ev PointerGesturePinchV1UpdateEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Update", err)
			return
		}

		fn(ev)
	})
}

func (o *PointerGesturePinchV1) OnEnd(fn PointerGesturePinchV1EndFunc) {
	o.proxy.RegisterEvent(PointerGesturePinchV1EventEnd, func(r *wire.Reader) {
		var ev PointerGesturePinchV1EndEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("End", err)
			return
		}

		fn(ev)
	})
}

func (o *PointerGesturePinchV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(PointerGesturePinchV1RequestDestroy, &PointerGesturePinchV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

func BindPointerGesturePinchV1(b wayland.Binder, name uint32, version uint32) (*PointerGesturePinchV1, error) {
	if version < 1 || version > VersionPointerGesturePinchV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfacePointerGesturePinchV1, version)
	if err != nil {
		return nil, err
	}
	x := NewPointerGesturePinchV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
