// Code generated by wayland-scanner. DO NOT EDIT.

package pointergesturesunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfacePointerGestureSwipeV1 = "zwp_pointer_gesture_swipe_v1"
const VersionPointerGestureSwipeV1 = 3

const (
	PointerGestureSwipeV1RequestDestroy uint16 = 0
)

const (
	PointerGestureSwipeV1EventBegin  uint16 = 0
	PointerGestureSwipeV1EventUpdate uint16 = 1
	PointerGestureSwipeV1EventEnd    uint16 = 2
)

// pointergestureswipev1EventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var pointergestureswipev1EventFDCounts = map[uint16]int{
	0: 0,
	1: 0,
	2: 0,
}

func init() {
	wayland.RegisterInterfaceFDCounts(InterfacePointerGestureSwipeV1, pointergestureswipev1EventFDCounts)
}

// PointerGestureSwipeV1DestroyRequest destroy the pointer swipe gesture object.
type PointerGestureSwipeV1DestroyRequest struct {
}

func (r *PointerGestureSwipeV1DestroyRequest) Opcode() uint16 {
	return PointerGestureSwipeV1RequestDestroy
}

func (r *PointerGestureSwipeV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *PointerGestureSwipeV1DestroyRequest) Since() uint32 { return 1 }

// PointerGestureSwipeV1BeginEvent multi-finger swipe begin.
//
// This event is sent when a multi-finger swipe gesture is detected
// on the device.
type PointerGestureSwipeV1BeginEvent struct {
	Serial uint32
	// Time timestamp with millisecond granularity.
	Time    uint32
	Surface wire.ObjectID
	// Fingers number of fingers.
	Fingers uint32
}

func (e *PointerGestureSwipeV1BeginEvent) Opcode() uint16 { return PointerGestureSwipeV1EventBegin }

func (e *PointerGestureSwipeV1BeginEvent) Unmarshal(r *wire.Reader) error {
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	time, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Time = time
	surface, err := r.Object()
	if err != nil {
		return err
	}
	e.Surface = surface
	fingers, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Fingers = fingers
	return nil
}

func (e *PointerGestureSwipeV1BeginEvent) Since() uint32 { return 1 }

// PointerGestureSwipeV1UpdateEvent multi-finger swipe motion.
//
// This event is sent when a multi-finger swipe gesture changes the
// position of the logical center.
//
// The dx and dy coordinates are relative coordinates of the logical
// center of the gesture compared to the previous event.
type PointerGestureSwipeV1UpdateEvent struct {
	// Time timestamp with millisecond granularity.
	Time uint32
	// Dx delta x coordinate in surface coordinate space.
	Dx wire.Fixed
	// Dy delta y coordinate in surface coordinate space.
	Dy wire.Fixed
}

func (e *PointerGestureSwipeV1UpdateEvent) Opcode() uint16 { return PointerGestureSwipeV1EventUpdate }

func (e *PointerGestureSwipeV1UpdateEvent) Unmarshal(r *wire.Reader) error {
	time, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Time = time
	dx, err := r.Fixed()
	if err != nil {
		return err
	}
	e.Dx = dx
	dy, err := r.Fixed()
	if err != nil {
		return err
	}
	e.Dy = dy
	return nil
}

func (e *PointerGestureSwipeV1UpdateEvent) Since() uint32 { return 1 }

// PointerGestureSwipeV1EndEvent multi-finger swipe end.
//
// This event is sent when a multi-finger swipe gesture ceases to
// be valid. This may happen when one or more fingers are lifted or
// the gesture is cancelled.
//
// When a gesture is cancelled, the client should undo state changes
// caused by this gesture. What causes a gesture to be cancelled is
// implementation-dependent.
type PointerGestureSwipeV1EndEvent struct {
	Serial uint32
	// Time timestamp with millisecond granularity.
	Time uint32
	// Cancelled 1 if the gesture was cancelled, 0 otherwise.
	Cancelled int32
}

func (e *PointerGestureSwipeV1EndEvent) Opcode() uint16 { return PointerGestureSwipeV1EventEnd }

func (e *PointerGestureSwipeV1EndEvent) Unmarshal(r *wire.Reader) error {
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	time, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Time = time
	cancelled, err := r.Int32()
	if err != nil {
		return err
	}
	e.Cancelled = cancelled
	return nil
}

func (e *PointerGestureSwipeV1EndEvent) Since() uint32 { return 1 }

// PointerGestureSwipeV1BeginFunc is a callback for Begin events.
type PointerGestureSwipeV1BeginFunc func(ev PointerGestureSwipeV1BeginEvent)

// PointerGestureSwipeV1UpdateFunc is a callback for Update events.
type PointerGestureSwipeV1UpdateFunc func(ev PointerGestureSwipeV1UpdateEvent)

// PointerGestureSwipeV1EndFunc is a callback for End events.
type PointerGestureSwipeV1EndFunc func(ev PointerGestureSwipeV1EndEvent)

// PointerGestureSwipeV1 a swipe gesture object.
//
// A swipe gesture object notifies a client about a multi-finger swipe
// gesture detected on an indirect input device such as a touchpad.
// The gesture is usually initiated by multiple fingers moving in the
// same direction but once initiated the direction may change.
// The precise conditions of when such a gesture is detected are
// implementation-dependent.
//
// A gesture consists of three stages: begin, update (optional) and end.
// There cannot be multiple simultaneous hold, pinch or swipe gestures on a
// same pointer/seat, how compositors prevent these situations is
// implementation-dependent.
//
// A gesture may be cancelled by the compositor or the hardware.
// Clients should not consider performing permanent or irreversible
// actions until the end of a gesture has been received.
type PointerGestureSwipeV1 struct {
	proxy *wayland.Proxy
}

// NewPointerGestureSwipeV1 wraps p in a PointerGestureSwipeV1 proxy.
func NewPointerGestureSwipeV1(p *wayland.Proxy) *PointerGestureSwipeV1 {
	p.SetEventFDCounts(pointergestureswipev1EventFDCounts)
	return &PointerGestureSwipeV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *PointerGestureSwipeV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// OnBegin registers fn to receive Begin events.
func (o *PointerGestureSwipeV1) OnBegin(fn PointerGestureSwipeV1BeginFunc) {
	o.proxy.RegisterEvent(PointerGestureSwipeV1EventBegin, func(r *wire.Reader) {
		var ev PointerGestureSwipeV1BeginEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Begin", err)
			return
		}

		fn(ev)
	})
}

// OnUpdate registers fn to receive Update events.
func (o *PointerGestureSwipeV1) OnUpdate(fn PointerGestureSwipeV1UpdateFunc) {
	o.proxy.RegisterEvent(PointerGestureSwipeV1EventUpdate, func(r *wire.Reader) {
		var ev PointerGestureSwipeV1UpdateEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Update", err)
			return
		}

		fn(ev)
	})
}

// OnEnd registers fn to receive End events.
func (o *PointerGestureSwipeV1) OnEnd(fn PointerGestureSwipeV1EndFunc) {
	o.proxy.RegisterEvent(PointerGestureSwipeV1EventEnd, func(r *wire.Reader) {
		var ev PointerGestureSwipeV1EndEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("End", err)
			return
		}

		fn(ev)
	})
}

// Destroy destroy the pointer swipe gesture object.
func (o *PointerGestureSwipeV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(PointerGestureSwipeV1RequestDestroy, &PointerGestureSwipeV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// BindPointerGestureSwipeV1 binds the zwp_pointer_gesture_swipe_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionPointerGestureSwipeV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindPointerGestureSwipeV1(reg, name, min(g.Version,
// VersionPointerGestureSwipeV1)), to bind at the highest mutually supported version.
func BindPointerGestureSwipeV1(b wayland.Binder, name uint32, version uint32) (*PointerGestureSwipeV1, error) {
	if version < 1 || version > VersionPointerGestureSwipeV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfacePointerGestureSwipeV1, version)
	if err != nil {
		return nil, err
	}
	x := NewPointerGestureSwipeV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
