// Code generated by wayland-scanner. DO NOT EDIT.

package tabletunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceTabletSeatV1 = "zwp_tablet_seat_v1"
const VersionTabletSeatV1 = 1

const (
	TabletSeatV1RequestDestroy uint16 = 0
)

const (
	TabletSeatV1EventTabletAdded uint16 = 0
	TabletSeatV1EventToolAdded   uint16 = 1
)

type TabletSeatV1DestroyRequest struct {
}

func (r *TabletSeatV1DestroyRequest) Opcode() uint16 { return TabletSeatV1RequestDestroy }

func (r *TabletSeatV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *TabletSeatV1DestroyRequest) Since() uint32 { return 1 }

type TabletSeatV1TabletAddedEvent struct {
	ID *TabletV1
}

func (e *TabletSeatV1TabletAddedEvent) Opcode() uint16 { return TabletSeatV1EventTabletAdded }

func (e *TabletSeatV1TabletAddedEvent) Since() uint32 { return 1 }

type TabletSeatV1ToolAddedEvent struct {
	ID *TabletToolV1
}

func (e *TabletSeatV1ToolAddedEvent) Opcode() uint16 { return TabletSeatV1EventToolAdded }

func (e *TabletSeatV1ToolAddedEvent) Since() uint32 { return 1 }

type TabletSeatV1TabletAddedFunc func(ev TabletSeatV1TabletAddedEvent)

type TabletSeatV1ToolAddedFunc func(ev TabletSeatV1ToolAddedEvent)

type TabletSeatV1 struct {
	proxy *wayland.Proxy
}

func NewTabletSeatV1(p *wayland.Proxy) *TabletSeatV1 {
	return &TabletSeatV1{proxy: p}
}

func (o *TabletSeatV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *TabletSeatV1) OnTabletAdded(fn TabletSeatV1TabletAddedFunc) {
	o.proxy.RegisterEvent(TabletSeatV1EventTabletAdded, func(r *wire.Reader) {
		var ev TabletSeatV1TabletAddedEvent

		rawID, err := r.NewID()
		if err != nil {
			o.proxy.Conn().FailEvent("TabletAdded", err)
			return
		}
		p := wayland.NewProxyWithID(o.proxy.Conn(), uint32(rawID))
		o.proxy.Conn().RegisterProxy(p)
		ev.ID = NewTabletV1(p)
		p.SetVersion(o.proxy.Version())

		fn(ev)
	})
}

func (o *TabletSeatV1) OnToolAdded(fn TabletSeatV1ToolAddedFunc) {
	o.proxy.RegisterEvent(TabletSeatV1EventToolAdded, func(r *wire.Reader) {
		var ev TabletSeatV1ToolAddedEvent

		rawID, err := r.NewID()
		if err != nil {
			o.proxy.Conn().FailEvent("ToolAdded", err)
			return
		}
		p := wayland.NewProxyWithID(o.proxy.Conn(), uint32(rawID))
		o.proxy.Conn().RegisterProxy(p)
		ev.ID = NewTabletToolV1(p)
		p.SetVersion(o.proxy.Version())

		fn(ev)
	})
}

func (o *TabletSeatV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(TabletSeatV1RequestDestroy, &TabletSeatV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

func BindTabletSeatV1(b wayland.Binder, name uint32, version uint32) (*TabletSeatV1, error) {
	if version < 1 || version > VersionTabletSeatV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceTabletSeatV1, version)
	if err != nil {
		return nil, err
	}
	x := NewTabletSeatV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
