// Code generated by wayland-scanner. DO NOT EDIT.

package colormanagement

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceImageDescriptionInfoV1 = "wp_image_description_info_v1"
const VersionImageDescriptionInfoV1 = 3

const (
	ImageDescriptionInfoV1EventDone            uint16 = 0
	ImageDescriptionInfoV1EventIccFile         uint16 = 1
	ImageDescriptionInfoV1EventPrimaries       uint16 = 2
	ImageDescriptionInfoV1EventPrimariesNamed  uint16 = 3
	ImageDescriptionInfoV1EventTfPower         uint16 = 4
	ImageDescriptionInfoV1EventTfNamed         uint16 = 5
	ImageDescriptionInfoV1EventLuminances      uint16 = 6
	ImageDescriptionInfoV1EventTargetPrimaries uint16 = 7
	ImageDescriptionInfoV1EventTargetLuminance uint16 = 8
	ImageDescriptionInfoV1EventTargetMaxCll    uint16 = 9
	ImageDescriptionInfoV1EventTargetMaxFall   uint16 = 10
)

var imagedescriptioninfov1EventFDCounts = map[uint16]int{
	1: 1,
}

type ImageDescriptionInfoV1DoneEvent struct {
}

func (e *ImageDescriptionInfoV1DoneEvent) Opcode() uint16 { return ImageDescriptionInfoV1EventDone }

func (e *ImageDescriptionInfoV1DoneEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *ImageDescriptionInfoV1DoneEvent) Since() int { return 1 }

type ImageDescriptionInfoV1IccFileEvent struct {
	Icc     int
	IccSize uint32
}

func (e *ImageDescriptionInfoV1IccFileEvent) Opcode() uint16 {
	return ImageDescriptionInfoV1EventIccFile
}

func (e *ImageDescriptionInfoV1IccFileEvent) Unmarshal(r *wire.Reader) error {
	icc, err := r.Fd()
	if err != nil {
		return err
	}
	e.Icc = icc
	iccSize, err := r.Uint32()
	if err != nil {
		return err
	}
	e.IccSize = iccSize
	return nil
}

func (e *ImageDescriptionInfoV1IccFileEvent) Since() int { return 1 }

type ImageDescriptionInfoV1PrimariesEvent struct {
	RX int32
	RY int32
	GX int32
	GY int32
	BX int32
	BY int32
	WX int32
	WY int32
}

func (e *ImageDescriptionInfoV1PrimariesEvent) Opcode() uint16 {
	return ImageDescriptionInfoV1EventPrimaries
}

func (e *ImageDescriptionInfoV1PrimariesEvent) Unmarshal(r *wire.Reader) error {
	rX, err := r.Int32()
	if err != nil {
		return err
	}
	e.RX = rX
	rY, err := r.Int32()
	if err != nil {
		return err
	}
	e.RY = rY
	gX, err := r.Int32()
	if err != nil {
		return err
	}
	e.GX = gX
	gY, err := r.Int32()
	if err != nil {
		return err
	}
	e.GY = gY
	bX, err := r.Int32()
	if err != nil {
		return err
	}
	e.BX = bX
	bY, err := r.Int32()
	if err != nil {
		return err
	}
	e.BY = bY
	wX, err := r.Int32()
	if err != nil {
		return err
	}
	e.WX = wX
	wY, err := r.Int32()
	if err != nil {
		return err
	}
	e.WY = wY
	return nil
}

func (e *ImageDescriptionInfoV1PrimariesEvent) Since() int { return 1 }

type ImageDescriptionInfoV1PrimariesNamedEvent struct {
	Primaries uint32
}

func (e *ImageDescriptionInfoV1PrimariesNamedEvent) Opcode() uint16 {
	return ImageDescriptionInfoV1EventPrimariesNamed
}

func (e *ImageDescriptionInfoV1PrimariesNamedEvent) Unmarshal(r *wire.Reader) error {
	primaries, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Primaries = primaries
	return nil
}

func (e *ImageDescriptionInfoV1PrimariesNamedEvent) Since() int { return 1 }

type ImageDescriptionInfoV1TfPowerEvent struct {
	Eexp uint32
}

func (e *ImageDescriptionInfoV1TfPowerEvent) Opcode() uint16 {
	return ImageDescriptionInfoV1EventTfPower
}

func (e *ImageDescriptionInfoV1TfPowerEvent) Unmarshal(r *wire.Reader) error {
	eexp, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Eexp = eexp
	return nil
}

func (e *ImageDescriptionInfoV1TfPowerEvent) Since() int { return 1 }

type ImageDescriptionInfoV1TfNamedEvent struct {
	Tf uint32
}

func (e *ImageDescriptionInfoV1TfNamedEvent) Opcode() uint16 {
	return ImageDescriptionInfoV1EventTfNamed
}

func (e *ImageDescriptionInfoV1TfNamedEvent) Unmarshal(r *wire.Reader) error {
	tf, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Tf = tf
	return nil
}

func (e *ImageDescriptionInfoV1TfNamedEvent) Since() int { return 1 }

type ImageDescriptionInfoV1LuminancesEvent struct {
	MinLum       uint32
	MaxLum       uint32
	ReferenceLum uint32
}

func (e *ImageDescriptionInfoV1LuminancesEvent) Opcode() uint16 {
	return ImageDescriptionInfoV1EventLuminances
}

func (e *ImageDescriptionInfoV1LuminancesEvent) Unmarshal(r *wire.Reader) error {
	minLum, err := r.Uint32()
	if err != nil {
		return err
	}
	e.MinLum = minLum
	maxLum, err := r.Uint32()
	if err != nil {
		return err
	}
	e.MaxLum = maxLum
	referenceLum, err := r.Uint32()
	if err != nil {
		return err
	}
	e.ReferenceLum = referenceLum
	return nil
}

func (e *ImageDescriptionInfoV1LuminancesEvent) Since() int { return 1 }

type ImageDescriptionInfoV1TargetPrimariesEvent struct {
	RX int32
	RY int32
	GX int32
	GY int32
	BX int32
	BY int32
	WX int32
	WY int32
}

func (e *ImageDescriptionInfoV1TargetPrimariesEvent) Opcode() uint16 {
	return ImageDescriptionInfoV1EventTargetPrimaries
}

func (e *ImageDescriptionInfoV1TargetPrimariesEvent) Unmarshal(r *wire.Reader) error {
	rX, err := r.Int32()
	if err != nil {
		return err
	}
	e.RX = rX
	rY, err := r.Int32()
	if err != nil {
		return err
	}
	e.RY = rY
	gX, err := r.Int32()
	if err != nil {
		return err
	}
	e.GX = gX
	gY, err := r.Int32()
	if err != nil {
		return err
	}
	e.GY = gY
	bX, err := r.Int32()
	if err != nil {
		return err
	}
	e.BX = bX
	bY, err := r.Int32()
	if err != nil {
		return err
	}
	e.BY = bY
	wX, err := r.Int32()
	if err != nil {
		return err
	}
	e.WX = wX
	wY, err := r.Int32()
	if err != nil {
		return err
	}
	e.WY = wY
	return nil
}

func (e *ImageDescriptionInfoV1TargetPrimariesEvent) Since() int { return 1 }

type ImageDescriptionInfoV1TargetLuminanceEvent struct {
	MinLum uint32
	MaxLum uint32
}

func (e *ImageDescriptionInfoV1TargetLuminanceEvent) Opcode() uint16 {
	return ImageDescriptionInfoV1EventTargetLuminance
}

func (e *ImageDescriptionInfoV1TargetLuminanceEvent) Unmarshal(r *wire.Reader) error {
	minLum, err := r.Uint32()
	if err != nil {
		return err
	}
	e.MinLum = minLum
	maxLum, err := r.Uint32()
	if err != nil {
		return err
	}
	e.MaxLum = maxLum
	return nil
}

func (e *ImageDescriptionInfoV1TargetLuminanceEvent) Since() int { return 1 }

type ImageDescriptionInfoV1TargetMaxCllEvent struct {
	MaxCll uint32
}

func (e *ImageDescriptionInfoV1TargetMaxCllEvent) Opcode() uint16 {
	return ImageDescriptionInfoV1EventTargetMaxCll
}

func (e *ImageDescriptionInfoV1TargetMaxCllEvent) Unmarshal(r *wire.Reader) error {
	maxCll, err := r.Uint32()
	if err != nil {
		return err
	}
	e.MaxCll = maxCll
	return nil
}

func (e *ImageDescriptionInfoV1TargetMaxCllEvent) Since() int { return 1 }

type ImageDescriptionInfoV1TargetMaxFallEvent struct {
	MaxFall uint32
}

func (e *ImageDescriptionInfoV1TargetMaxFallEvent) Opcode() uint16 {
	return ImageDescriptionInfoV1EventTargetMaxFall
}

func (e *ImageDescriptionInfoV1TargetMaxFallEvent) Unmarshal(r *wire.Reader) error {
	maxFall, err := r.Uint32()
	if err != nil {
		return err
	}
	e.MaxFall = maxFall
	return nil
}

func (e *ImageDescriptionInfoV1TargetMaxFallEvent) Since() int { return 1 }

type ImageDescriptionInfoV1DoneFunc func(ev ImageDescriptionInfoV1DoneEvent)

type ImageDescriptionInfoV1IccFileFunc func(ev ImageDescriptionInfoV1IccFileEvent)

type ImageDescriptionInfoV1PrimariesFunc func(ev ImageDescriptionInfoV1PrimariesEvent)

type ImageDescriptionInfoV1PrimariesNamedFunc func(ev ImageDescriptionInfoV1PrimariesNamedEvent)

type ImageDescriptionInfoV1TfPowerFunc func(ev ImageDescriptionInfoV1TfPowerEvent)

type ImageDescriptionInfoV1TfNamedFunc func(ev ImageDescriptionInfoV1TfNamedEvent)

type ImageDescriptionInfoV1LuminancesFunc func(ev ImageDescriptionInfoV1LuminancesEvent)

type ImageDescriptionInfoV1TargetPrimariesFunc func(ev ImageDescriptionInfoV1TargetPrimariesEvent)

type ImageDescriptionInfoV1TargetLuminanceFunc func(ev ImageDescriptionInfoV1TargetLuminanceEvent)

type ImageDescriptionInfoV1TargetMaxCllFunc func(ev ImageDescriptionInfoV1TargetMaxCllEvent)

type ImageDescriptionInfoV1TargetMaxFallFunc func(ev ImageDescriptionInfoV1TargetMaxFallEvent)

type ImageDescriptionInfoV1 struct {
	proxy *wayland.Proxy
}

func NewImageDescriptionInfoV1(p *wayland.Proxy) *ImageDescriptionInfoV1 {
	p.SetEventFDCounts(imagedescriptioninfov1EventFDCounts)
	return &ImageDescriptionInfoV1{proxy: p}
}

func (o *ImageDescriptionInfoV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *ImageDescriptionInfoV1) OnDone(fn ImageDescriptionInfoV1DoneFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventDone, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1DoneEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ImageDescriptionInfoV1) OnIccFile(fn ImageDescriptionInfoV1IccFileFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventIccFile, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1IccFileEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ImageDescriptionInfoV1) OnPrimaries(fn ImageDescriptionInfoV1PrimariesFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventPrimaries, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1PrimariesEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ImageDescriptionInfoV1) OnPrimariesNamed(fn ImageDescriptionInfoV1PrimariesNamedFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventPrimariesNamed, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1PrimariesNamedEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ImageDescriptionInfoV1) OnTfPower(fn ImageDescriptionInfoV1TfPowerFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventTfPower, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1TfPowerEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ImageDescriptionInfoV1) OnTfNamed(fn ImageDescriptionInfoV1TfNamedFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventTfNamed, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1TfNamedEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ImageDescriptionInfoV1) OnLuminances(fn ImageDescriptionInfoV1LuminancesFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventLuminances, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1LuminancesEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ImageDescriptionInfoV1) OnTargetPrimaries(fn ImageDescriptionInfoV1TargetPrimariesFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventTargetPrimaries, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1TargetPrimariesEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ImageDescriptionInfoV1) OnTargetLuminance(fn ImageDescriptionInfoV1TargetLuminanceFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventTargetLuminance, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1TargetLuminanceEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ImageDescriptionInfoV1) OnTargetMaxCll(fn ImageDescriptionInfoV1TargetMaxCllFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventTargetMaxCll, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1TargetMaxCllEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ImageDescriptionInfoV1) OnTargetMaxFall(fn ImageDescriptionInfoV1TargetMaxFallFunc) {
	o.proxy.RegisterEvent(ImageDescriptionInfoV1EventTargetMaxFall, func(r *wire.Reader) {
		var ev ImageDescriptionInfoV1TargetMaxFallEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func BindImageDescriptionInfoV1(b wayland.Binder, name uint32, version uint32) (*ImageDescriptionInfoV1, error) {
	if version < 1 || version > VersionImageDescriptionInfoV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceImageDescriptionInfoV1, version)
	if err != nil {
		return nil, err
	}
	x := NewImageDescriptionInfoV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
