// Code generated by wayland-scanner. DO NOT EDIT.

package colormanagement

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceImageDescriptionReferenceV1 = "wp_image_description_reference_v1"
const VersionImageDescriptionReferenceV1 = 1

const (
	ImageDescriptionReferenceV1RequestDestroy uint16 = 0
)

type ImageDescriptionReferenceV1DestroyRequest struct {
}

func (r *ImageDescriptionReferenceV1DestroyRequest) Opcode() uint16 {
	return ImageDescriptionReferenceV1RequestDestroy
}

func (r *ImageDescriptionReferenceV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *ImageDescriptionReferenceV1DestroyRequest) Since() uint32 { return 1 }

type ImageDescriptionReferenceV1 struct {
	proxy *wayland.Proxy
}

func NewImageDescriptionReferenceV1(p *wayland.Proxy) *ImageDescriptionReferenceV1 {
	return &ImageDescriptionReferenceV1{proxy: p}
}

func (o *ImageDescriptionReferenceV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *ImageDescriptionReferenceV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(ImageDescriptionReferenceV1RequestDestroy, &ImageDescriptionReferenceV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// BindImageDescriptionReferenceV1 binds the wp_image_description_reference_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionImageDescriptionReferenceV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindImageDescriptionReferenceV1(reg, name, min(g.Version,
// VersionImageDescriptionReferenceV1)), to bind at the highest mutually supported version.
func BindImageDescriptionReferenceV1(b wayland.Binder, name uint32, version uint32) (*ImageDescriptionReferenceV1, error) {
	if version < 1 || version > VersionImageDescriptionReferenceV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceImageDescriptionReferenceV1, version)
	if err != nil {
		return nil, err
	}
	x := NewImageDescriptionReferenceV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
