// Code generated by wayland-scanner. DO NOT EDIT.

package extimagecopycapture

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceImageCopyCaptureManagerV1 = "ext_image_copy_capture_manager_v1"
const VersionImageCopyCaptureManagerV1 = 1

const (
	ImageCopyCaptureManagerV1RequestCreateSession              uint16 = 0
	ImageCopyCaptureManagerV1RequestCreatePointerCursorSession uint16 = 1
	ImageCopyCaptureManagerV1RequestDestroy                    uint16 = 2
)

type ImageCopyCaptureManagerV1Error uint32

const (
	ImageCopyCaptureManagerV1ErrorInvalidOption ImageCopyCaptureManagerV1Error = 1
)

type ImageCopyCaptureManagerV1Options uint32

const (
	ImageCopyCaptureManagerV1OptionsPaintCursors ImageCopyCaptureManagerV1Options = 1
)

type ImageCopyCaptureManagerV1CreateSessionRequest struct {
	Session wire.NewID
	Source  wire.ObjectID
	Options uint32
}

func (r *ImageCopyCaptureManagerV1CreateSessionRequest) Opcode() uint16 {
	return ImageCopyCaptureManagerV1RequestCreateSession
}

func (r *ImageCopyCaptureManagerV1CreateSessionRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.Session); err != nil {
		return err
	}
	if err := w.Object(r.Source); err != nil {
		return err
	}
	if err := w.Uint32(r.Options); err != nil {
		return err
	}
	return nil
}

func (r *ImageCopyCaptureManagerV1CreateSessionRequest) Since() int { return 1 }

type ImageCopyCaptureManagerV1CreatePointerCursorSessionRequest struct {
	Session wire.NewID
	Source  wire.ObjectID
	Pointer wire.ObjectID
}

func (r *ImageCopyCaptureManagerV1CreatePointerCursorSessionRequest) Opcode() uint16 {
	return ImageCopyCaptureManagerV1RequestCreatePointerCursorSession
}

func (r *ImageCopyCaptureManagerV1CreatePointerCursorSessionRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.Session); err != nil {
		return err
	}
	if err := w.Object(r.Source); err != nil {
		return err
	}
	if err := w.Object(r.Pointer); err != nil {
		return err
	}
	return nil
}

func (r *ImageCopyCaptureManagerV1CreatePointerCursorSessionRequest) Since() int { return 1 }

type ImageCopyCaptureManagerV1DestroyRequest struct {
}

func (r *ImageCopyCaptureManagerV1DestroyRequest) Opcode() uint16 {
	return ImageCopyCaptureManagerV1RequestDestroy
}

func (r *ImageCopyCaptureManagerV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *ImageCopyCaptureManagerV1DestroyRequest) Since() int { return 1 }

type ImageCopyCaptureManagerV1 struct {
	proxy *wayland.Proxy
}

func NewImageCopyCaptureManagerV1(p *wayland.Proxy) *ImageCopyCaptureManagerV1 {
	return &ImageCopyCaptureManagerV1{proxy: p}
}

func (o *ImageCopyCaptureManagerV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *ImageCopyCaptureManagerV1) CreateSession(source wire.ObjectID, options uint32) (*ImageCopyCaptureSessionV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewImageCopyCaptureSessionV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), ImageCopyCaptureManagerV1RequestCreateSession, &ImageCopyCaptureManagerV1CreateSessionRequest{
		Session: wire.NewID(p.ID()),
		Source:  source,
		Options: options,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func (o *ImageCopyCaptureManagerV1) CreatePointerCursorSession(source wire.ObjectID, pointer wire.ObjectID) (*ImageCopyCaptureCursorSessionV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewImageCopyCaptureCursorSessionV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), ImageCopyCaptureManagerV1RequestCreatePointerCursorSession, &ImageCopyCaptureManagerV1CreatePointerCursorSessionRequest{
		Session: wire.NewID(p.ID()),
		Source:  source,
		Pointer: pointer,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func (o *ImageCopyCaptureManagerV1) Destroy() error {
	return o.proxy.SendRequest(ImageCopyCaptureManagerV1RequestDestroy, &ImageCopyCaptureManagerV1DestroyRequest{})
}

func BindImageCopyCaptureManagerV1(b wayland.Binder, name uint32, version uint32) (*ImageCopyCaptureManagerV1, error) {
	if version < 1 || version > VersionImageCopyCaptureManagerV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceImageCopyCaptureManagerV1, version)
	if err != nil {
		return nil, err
	}
	x := NewImageCopyCaptureManagerV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
