// Code generated by wayland-scanner. DO NOT EDIT.

package linuxexplicitsynchronizationunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceLinuxExplicitSynchronizationV1 = "zwp_linux_explicit_synchronization_v1"
const VersionLinuxExplicitSynchronizationV1 = 2

const (
	LinuxExplicitSynchronizationV1RequestDestroy            uint16 = 0
	LinuxExplicitSynchronizationV1RequestGetSynchronization uint16 = 1
)

type LinuxExplicitSynchronizationV1Error uint32

const (
	// LinuxExplicitSynchronizationV1ErrorSynchronizationExists the surface already has a synchronization object associated.
	LinuxExplicitSynchronizationV1ErrorSynchronizationExists LinuxExplicitSynchronizationV1Error = 0
)

// LinuxExplicitSynchronizationV1DestroyRequest destroy explicit synchronization factory object.
//
// Destroy this explicit synchronization factory object. Other objects,
// including zwp_linux_surface_synchronization_v1 objects created by this
// factory, shall not be affected by this request.
type LinuxExplicitSynchronizationV1DestroyRequest struct{}

func (r *LinuxExplicitSynchronizationV1DestroyRequest) Opcode() uint16 {
	return LinuxExplicitSynchronizationV1RequestDestroy
}

func (r *LinuxExplicitSynchronizationV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *LinuxExplicitSynchronizationV1DestroyRequest) Since() uint32 { return 1 }

// LinuxExplicitSynchronizationV1GetSynchronizationRequest extend surface interface for explicit synchronization.
//
// Instantiate an interface extension for the given wl_surface to provide
// explicit synchronization.
//
// If the given wl_surface already has an explicit synchronization object
// associated, the synchronization_exists protocol error is raised.
//
// Graphics APIs, like EGL or Vulkan, that manage the buffer queue and
// commits of a wl_surface themselves, are likely to be using this
// extension internally. If a client is using such an API for a
// wl_surface, it should not directly use this extension on that surface,
// to avoid raising a synchronization_exists protocol error.
type LinuxExplicitSynchronizationV1GetSynchronizationRequest struct {
	// ID the new synchronization interface id.
	ID wire.NewID
	// Surface the surface.
	Surface wire.ObjectID
}

func (r *LinuxExplicitSynchronizationV1GetSynchronizationRequest) Opcode() uint16 {
	return LinuxExplicitSynchronizationV1RequestGetSynchronization
}

func (r *LinuxExplicitSynchronizationV1GetSynchronizationRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Surface); err != nil {
		return err
	}
	return nil
}

func (r *LinuxExplicitSynchronizationV1GetSynchronizationRequest) Since() uint32 { return 1 }

// LinuxExplicitSynchronizationV1 protocol for providing explicit synchronization.
//
// This global is a factory interface, allowing clients to request
// explicit synchronization for buffers on a per-surface basis.
//
// See zwp_linux_surface_synchronization_v1 for more information.
//
// This interface is derived from Chromium's
// zcr_linux_explicit_synchronization_v1.
//
// Note: this protocol is superseded by linux-drm-syncobj.
//
// Warning! The protocol described in this file is experimental and
// backward incompatible changes may be made. Backward compatible changes
// may be added together with the corresponding interface version bump.
// Backward incompatible changes are done by bumping the version number in
// the protocol and interface names and resetting the interface version.
// Once the protocol is to be declared stable, the 'z' prefix and the
// version number in the protocol and interface names are removed and the
// interface version number is reset.
type LinuxExplicitSynchronizationV1 struct {
	proxy *wayland.Proxy
}

// NewLinuxExplicitSynchronizationV1 wraps p in a LinuxExplicitSynchronizationV1 proxy.
func NewLinuxExplicitSynchronizationV1(p *wayland.Proxy) *LinuxExplicitSynchronizationV1 {
	return &LinuxExplicitSynchronizationV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *LinuxExplicitSynchronizationV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// Destroy destroy explicit synchronization factory object.
//
// Destroy this explicit synchronization factory object. Other objects,
// including zwp_linux_surface_synchronization_v1 objects created by this
// factory, shall not be affected by this request.
func (o *LinuxExplicitSynchronizationV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(LinuxExplicitSynchronizationV1RequestDestroy, &LinuxExplicitSynchronizationV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// GetSynchronization extend surface interface for explicit synchronization.
//
// Instantiate an interface extension for the given wl_surface to provide
// explicit synchronization.
//
// If the given wl_surface already has an explicit synchronization object
// associated, the synchronization_exists protocol error is raised.
//
// Graphics APIs, like EGL or Vulkan, that manage the buffer queue and
// commits of a wl_surface themselves, are likely to be using this
// extension internally. If a client is using such an API for a
// wl_surface, it should not directly use this extension on that surface,
// to avoid raising a synchronization_exists protocol error.
func (o *LinuxExplicitSynchronizationV1) GetSynchronization(surface wire.ObjectID) (*LinuxSurfaceSynchronizationV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewLinuxSurfaceSynchronizationV1(p)
	conn.RegisterProxy(p)
	if err := conn.SendRequest(o.proxy.ID(), LinuxExplicitSynchronizationV1RequestGetSynchronization, &LinuxExplicitSynchronizationV1GetSynchronizationRequest{
		ID:      wire.NewID(p.ID()),
		Surface: surface,
	}); err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// BindLinuxExplicitSynchronizationV1 binds the zwp_linux_explicit_synchronization_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionLinuxExplicitSynchronizationV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindLinuxExplicitSynchronizationV1(reg, name, min(g.Version,
// VersionLinuxExplicitSynchronizationV1)), to bind at the highest mutually supported version.
func BindLinuxExplicitSynchronizationV1(b wayland.Binder, name, version uint32) (*LinuxExplicitSynchronizationV1, error) {
	if version < 1 || version > VersionLinuxExplicitSynchronizationV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceLinuxExplicitSynchronizationV1, version)
	if err != nil {
		return nil, err
	}
	x := NewLinuxExplicitSynchronizationV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
