// Code generated by wayland-scanner. DO NOT EDIT.

package wayland

import (
	"github.com/xogas/wayland/wire"
)

const InterfaceDataDeviceManager = "wl_data_device_manager"
const VersionDataDeviceManager = 4

const (
	DataDeviceManagerRequestCreateDataSource uint16 = 0
	DataDeviceManagerRequestGetDataDevice    uint16 = 1
	DataDeviceManagerRequestRelease          uint16 = 2
)

// DataDeviceManagerDndAction drag and drop actions.
//
// This is a bitmask of the available/preferred actions in a
// drag-and-drop operation.
//
// In the compositor, the selected action is a result of matching the
// actions offered by the source and destination sides.  "action" events
// with a "none" action will be sent to both source and destination if
// there is no match. All further checks will effectively happen on
// (source actions ∩ destination actions).
//
// In addition, compositors may also pick different actions in
// reaction to key modifiers being pressed. One common design that
// is used in major toolkits (and the behavior recommended for
// compositors) is:
//
//   - If no modifiers are pressed, the first match (in bit order)
//     will be used.
//   - Pressing Shift selects "move", if enabled in the mask.
//   - Pressing Control selects "copy", if enabled in the mask.
//
// Behavior beyond that is considered implementation-dependent.
// Compositors may for example bind other modifiers (like Alt/Meta)
// or drags initiated with other buttons than BTN_LEFT to specific
// actions (e.g. "ask").
//
// This is a bitfield of flags.
type DataDeviceManagerDndAction uint32

const (
	// DataDeviceManagerDndActionNone no action.
	DataDeviceManagerDndActionNone DataDeviceManagerDndAction = 0

	// DataDeviceManagerDndActionCopy copy action.
	DataDeviceManagerDndActionCopy DataDeviceManagerDndAction = 1

	// DataDeviceManagerDndActionMove move action.
	DataDeviceManagerDndActionMove DataDeviceManagerDndAction = 2

	// DataDeviceManagerDndActionAsk ask action.
	DataDeviceManagerDndActionAsk DataDeviceManagerDndAction = 4
)

// DataDeviceManagerCreateDataSourceRequest create a new data source.
//
// Create a new data source.
type DataDeviceManagerCreateDataSourceRequest struct {
	// ID data source to create.
	ID wire.NewID
}

func (r *DataDeviceManagerCreateDataSourceRequest) Opcode() uint16 {
	return DataDeviceManagerRequestCreateDataSource
}

func (r *DataDeviceManagerCreateDataSourceRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	return nil
}

func (r *DataDeviceManagerCreateDataSourceRequest) Since() uint32 { return 1 }

// DataDeviceManagerGetDataDeviceRequest create a new data device.
//
// Create a new data device for a given seat.
type DataDeviceManagerGetDataDeviceRequest struct {
	// ID data device to create.
	ID wire.NewID
	// Seat seat associated with the data device.
	Seat wire.ObjectID
}

func (r *DataDeviceManagerGetDataDeviceRequest) Opcode() uint16 {
	return DataDeviceManagerRequestGetDataDevice
}

func (r *DataDeviceManagerGetDataDeviceRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Seat); err != nil {
		return err
	}
	return nil
}

func (r *DataDeviceManagerGetDataDeviceRequest) Since() uint32 { return 1 }

// DataDeviceManagerReleaseRequest destroy wl_data_device_manager.
//
// This request destroys the wl_data_device_manager. This has no effect on any other
// objects.
type DataDeviceManagerReleaseRequest struct{}

func (r *DataDeviceManagerReleaseRequest) Opcode() uint16 { return DataDeviceManagerRequestRelease }

func (r *DataDeviceManagerReleaseRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *DataDeviceManagerReleaseRequest) Since() uint32 { return 4 }

// DataDeviceManager data transfer interface.
//
// The wl_data_device_manager is a singleton global object that
// provides access to inter-client data transfer mechanisms such as
// copy-and-paste and drag-and-drop.  These mechanisms are tied to
// a wl_seat and this interface lets a client get a wl_data_device
// corresponding to a wl_seat.
//
// Depending on the version bound, the objects created from the bound
// wl_data_device_manager object will have different requirements for
// functioning properly. See wl_data_source.set_actions,
// wl_data_offer.accept and wl_data_offer.finish for details.
type DataDeviceManager struct {
	proxy *Proxy
}

// NewDataDeviceManager wraps p in a DataDeviceManager proxy.
func NewDataDeviceManager(p *Proxy) *DataDeviceManager {
	return &DataDeviceManager{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *DataDeviceManager) Proxy() *Proxy {
	return o.proxy
}

// CreateDataSource create a new data source.
//
// Create a new data source.
func (o *DataDeviceManager) CreateDataSource() (*DataSource, error) {
	conn := o.proxy.Conn()
	p := NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewDataSource(p)
	conn.RegisterProxy(p)
	if err := conn.SendRequest(o.proxy.ID(), DataDeviceManagerRequestCreateDataSource, &DataDeviceManagerCreateDataSourceRequest{
		ID: wire.NewID(p.ID()),
	}); err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// GetDataDevice create a new data device.
//
// Create a new data device for a given seat.
func (o *DataDeviceManager) GetDataDevice(seat wire.ObjectID) (*DataDevice, error) {
	conn := o.proxy.Conn()
	p := NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewDataDevice(p)
	conn.RegisterProxy(p)
	if err := conn.SendRequest(o.proxy.ID(), DataDeviceManagerRequestGetDataDevice, &DataDeviceManagerGetDataDeviceRequest{
		ID:   wire.NewID(p.ID()),
		Seat: seat,
	}); err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// Release destroy wl_data_device_manager.
//
// This request destroys the wl_data_device_manager. This has no effect on any other
// objects.
func (o *DataDeviceManager) Release() error {
	if v := o.proxy.Version(); v > 0 && v < uint32(4) {
		return ErrVersionMismatch
	}
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(DataDeviceManagerRequestRelease, &DataDeviceManagerReleaseRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// BindDataDeviceManager binds the wl_data_device_manager global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionDataDeviceManager] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindDataDeviceManager(reg, name, min(g.Version,
// VersionDataDeviceManager)), to bind at the highest mutually supported version.
func BindDataDeviceManager(b Binder, name, version uint32) (*DataDeviceManager, error) {
	if version < 1 || version > VersionDataDeviceManager {
		return nil, ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceDataDeviceManager, version)
	if err != nil {
		return nil, err
	}
	x := NewDataDeviceManager(p)
	x.proxy.SetVersion(version)
	return x, nil
}
