// Code generated by wayland-scanner. DO NOT EDIT.

package wayland

import (
	"github.com/xogas/wayland/wire"
)

const InterfaceDataOffer = "wl_data_offer"
const VersionDataOffer = 4

const (
	DataOfferRequestAccept     uint16 = 0
	DataOfferRequestReceive    uint16 = 1
	DataOfferRequestDestroy    uint16 = 2
	DataOfferRequestFinish     uint16 = 3
	DataOfferRequestSetActions uint16 = 4
)

const (
	DataOfferEventOffer         uint16 = 0
	DataOfferEventSourceActions uint16 = 1
	DataOfferEventAction        uint16 = 2
)

// dataofferEventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var dataofferEventFDCounts = map[uint16]int{
	0: 0,
	1: 0,
	2: 0,
}

type DataOfferError uint32

const (
	DataOfferErrorInvalidFinish     DataOfferError = 0
	DataOfferErrorInvalidActionMask DataOfferError = 1
	DataOfferErrorInvalidAction     DataOfferError = 2
	DataOfferErrorInvalidOffer      DataOfferError = 3
)

type DataOfferAcceptRequest struct {
	Serial   uint32
	MimeType *string // nullable
}

func (r *DataOfferAcceptRequest) Opcode() uint16 { return DataOfferRequestAccept }

func (r *DataOfferAcceptRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Serial); err != nil {
		return err
	}
	if err := w.StringNullable(r.MimeType); err != nil {
		return err
	}
	return nil
}

func (r *DataOfferAcceptRequest) Since() uint32 { return 1 }

type DataOfferReceiveRequest struct {
	MimeType string
	Fd       int
}

func (r *DataOfferReceiveRequest) Opcode() uint16 { return DataOfferRequestReceive }

func (r *DataOfferReceiveRequest) Marshal(w *wire.Writer) error {
	if err := w.String(r.MimeType); err != nil {
		return err
	}
	if err := w.Fd(r.Fd); err != nil {
		return err
	}
	return nil
}

func (r *DataOfferReceiveRequest) Since() uint32 { return 1 }

type DataOfferDestroyRequest struct {
}

func (r *DataOfferDestroyRequest) Opcode() uint16 { return DataOfferRequestDestroy }

func (r *DataOfferDestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *DataOfferDestroyRequest) Since() uint32 { return 1 }

type DataOfferFinishRequest struct {
}

func (r *DataOfferFinishRequest) Opcode() uint16 { return DataOfferRequestFinish }

func (r *DataOfferFinishRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *DataOfferFinishRequest) Since() uint32 { return 3 }

type DataOfferSetActionsRequest struct {
	DndActions      DataDeviceManagerDndAction
	PreferredAction DataDeviceManagerDndAction
}

func (r *DataOfferSetActionsRequest) Opcode() uint16 { return DataOfferRequestSetActions }

func (r *DataOfferSetActionsRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(uint32(r.DndActions)); err != nil {
		return err
	}
	if err := w.Uint32(uint32(r.PreferredAction)); err != nil {
		return err
	}
	return nil
}

func (r *DataOfferSetActionsRequest) Since() uint32 { return 3 }

type DataOfferOfferEvent struct {
	MimeType string
}

func (e *DataOfferOfferEvent) Opcode() uint16 { return DataOfferEventOffer }

func (e *DataOfferOfferEvent) Unmarshal(r *wire.Reader) error {
	mimeType, err := r.String()
	if err != nil {
		return err
	}
	e.MimeType = mimeType
	return nil
}

func (e *DataOfferOfferEvent) Since() uint32 { return 1 }

type DataOfferSourceActionsEvent struct {
	SourceActions DataDeviceManagerDndAction
}

func (e *DataOfferSourceActionsEvent) Opcode() uint16 { return DataOfferEventSourceActions }

func (e *DataOfferSourceActionsEvent) Unmarshal(r *wire.Reader) error {
	sourceActions, err := r.Uint32()
	if err != nil {
		return err
	}
	e.SourceActions = DataDeviceManagerDndAction(sourceActions)
	return nil
}

func (e *DataOfferSourceActionsEvent) Since() uint32 { return 3 }

type DataOfferActionEvent struct {
	DndAction DataDeviceManagerDndAction
}

func (e *DataOfferActionEvent) Opcode() uint16 { return DataOfferEventAction }

func (e *DataOfferActionEvent) Unmarshal(r *wire.Reader) error {
	dndAction, err := r.Uint32()
	if err != nil {
		return err
	}
	e.DndAction = DataDeviceManagerDndAction(dndAction)
	return nil
}

func (e *DataOfferActionEvent) Since() uint32 { return 3 }

type DataOfferOfferFunc func(ev DataOfferOfferEvent)

type DataOfferSourceActionsFunc func(ev DataOfferSourceActionsEvent)

type DataOfferActionFunc func(ev DataOfferActionEvent)

type DataOffer struct {
	proxy *Proxy
}

func NewDataOffer(p *Proxy) *DataOffer {
	p.SetEventFDCounts(dataofferEventFDCounts)
	return &DataOffer{proxy: p}
}

func (o *DataOffer) Proxy() *Proxy {
	return o.proxy
}

func (o *DataOffer) OnOffer(fn DataOfferOfferFunc) {
	o.proxy.RegisterEvent(DataOfferEventOffer, func(r *wire.Reader) {
		var ev DataOfferOfferEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Offer", err)
			return
		}

		fn(ev)
	})
}

func (o *DataOffer) OnSourceActions(fn DataOfferSourceActionsFunc) {
	o.proxy.RegisterEvent(DataOfferEventSourceActions, func(r *wire.Reader) {
		var ev DataOfferSourceActionsEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("SourceActions", err)
			return
		}

		fn(ev)
	})
}

func (o *DataOffer) OnAction(fn DataOfferActionFunc) {
	o.proxy.RegisterEvent(DataOfferEventAction, func(r *wire.Reader) {
		var ev DataOfferActionEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Action", err)
			return
		}

		fn(ev)
	})
}

func (o *DataOffer) Accept(serial uint32, mimeType *string) error {
	return o.proxy.SendRequest(DataOfferRequestAccept, &DataOfferAcceptRequest{
		Serial:   serial,
		MimeType: mimeType,
	})
}

func (o *DataOffer) Receive(mimeType string, fd int) error {
	return o.proxy.SendRequest(DataOfferRequestReceive, &DataOfferReceiveRequest{
		MimeType: mimeType,
		Fd:       fd,
	})
}

func (o *DataOffer) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(DataOfferRequestDestroy, &DataOfferDestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

func (o *DataOffer) Finish() error {
	if v := o.proxy.Version(); v > 0 && v < uint32(3) {
		return ErrVersionMismatch
	}
	return o.proxy.SendRequest(DataOfferRequestFinish, &DataOfferFinishRequest{})
}

func (o *DataOffer) SetActions(dndActions DataDeviceManagerDndAction, preferredAction DataDeviceManagerDndAction) error {
	if v := o.proxy.Version(); v > 0 && v < uint32(3) {
		return ErrVersionMismatch
	}
	return o.proxy.SendRequest(DataOfferRequestSetActions, &DataOfferSetActionsRequest{
		DndActions:      dndActions,
		PreferredAction: preferredAction,
	})
}

func BindDataOffer(b Binder, name uint32, version uint32) (*DataOffer, error) {
	if version < 1 || version > VersionDataOffer {
		return nil, ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceDataOffer, version)
	if err != nil {
		return nil, err
	}
	x := NewDataOffer(p)
	x.proxy.SetVersion(version)
	return x, nil
}
