// Code generated by wayland-scanner. DO NOT EDIT.

package wayland

import (
	"github.com/xogas/wayland/wire"
)

const InterfaceOutput = "wl_output"
const VersionOutput = 4

const (
	OutputRequestRelease uint16 = 0
)

const (
	OutputEventGeometry    uint16 = 0
	OutputEventMode        uint16 = 1
	OutputEventDone        uint16 = 2
	OutputEventScale       uint16 = 3
	OutputEventName        uint16 = 4
	OutputEventDescription uint16 = 5
)

// outputEventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var outputEventFDCounts = map[uint16]int{
	0: 0,
	1: 0,
	2: 0,
	3: 0,
	4: 0,
	5: 0,
}

type OutputSubpixel uint32

const (
	OutputSubpixelUnknown       OutputSubpixel = 0
	OutputSubpixelNone          OutputSubpixel = 1
	OutputSubpixelHorizontalRgb OutputSubpixel = 2
	OutputSubpixelHorizontalBgr OutputSubpixel = 3
	OutputSubpixelVerticalRgb   OutputSubpixel = 4
	OutputSubpixelVerticalBgr   OutputSubpixel = 5
)

type OutputTransform uint32

const (
	OutputTransformNormal     OutputTransform = 0
	OutputTransform90         OutputTransform = 1
	OutputTransform180        OutputTransform = 2
	OutputTransform270        OutputTransform = 3
	OutputTransformFlipped    OutputTransform = 4
	OutputTransformFlipped90  OutputTransform = 5
	OutputTransformFlipped180 OutputTransform = 6
	OutputTransformFlipped270 OutputTransform = 7
)

// OutputMode is a bitfield of flags.
type OutputMode uint32

const (
	OutputModeCurrent   OutputMode = 1
	OutputModePreferred OutputMode = 2
)

type OutputReleaseRequest struct {
}

func (r *OutputReleaseRequest) Opcode() uint16 { return OutputRequestRelease }

func (r *OutputReleaseRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *OutputReleaseRequest) Since() uint32 { return 3 }

type OutputGeometryEvent struct {
	X              int32
	Y              int32
	PhysicalWidth  int32
	PhysicalHeight int32
	Subpixel       int32
	Make           string
	Model          string
	Transform      int32
}

func (e *OutputGeometryEvent) Opcode() uint16 { return OutputEventGeometry }

func (e *OutputGeometryEvent) Unmarshal(r *wire.Reader) error {
	x, err := r.Int32()
	if err != nil {
		return err
	}
	e.X = x
	y, err := r.Int32()
	if err != nil {
		return err
	}
	e.Y = y
	physicalWidth, err := r.Int32()
	if err != nil {
		return err
	}
	e.PhysicalWidth = physicalWidth
	physicalHeight, err := r.Int32()
	if err != nil {
		return err
	}
	e.PhysicalHeight = physicalHeight
	subpixel, err := r.Int32()
	if err != nil {
		return err
	}
	e.Subpixel = subpixel
	make, err := r.String()
	if err != nil {
		return err
	}
	e.Make = make
	model, err := r.String()
	if err != nil {
		return err
	}
	e.Model = model
	transform, err := r.Int32()
	if err != nil {
		return err
	}
	e.Transform = transform
	return nil
}

func (e *OutputGeometryEvent) Since() uint32 { return 1 }

type OutputModeEvent struct {
	Flags   OutputMode
	Width   int32
	Height  int32
	Refresh int32
}

func (e *OutputModeEvent) Opcode() uint16 { return OutputEventMode }

func (e *OutputModeEvent) Unmarshal(r *wire.Reader) error {
	flags, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Flags = OutputMode(flags)
	width, err := r.Int32()
	if err != nil {
		return err
	}
	e.Width = width
	height, err := r.Int32()
	if err != nil {
		return err
	}
	e.Height = height
	refresh, err := r.Int32()
	if err != nil {
		return err
	}
	e.Refresh = refresh
	return nil
}

func (e *OutputModeEvent) Since() uint32 { return 1 }

type OutputDoneEvent struct {
}

func (e *OutputDoneEvent) Opcode() uint16 { return OutputEventDone }

func (e *OutputDoneEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *OutputDoneEvent) Since() uint32 { return 2 }

type OutputScaleEvent struct {
	Factor int32
}

func (e *OutputScaleEvent) Opcode() uint16 { return OutputEventScale }

func (e *OutputScaleEvent) Unmarshal(r *wire.Reader) error {
	factor, err := r.Int32()
	if err != nil {
		return err
	}
	e.Factor = factor
	return nil
}

func (e *OutputScaleEvent) Since() uint32 { return 2 }

type OutputNameEvent struct {
	Name string
}

func (e *OutputNameEvent) Opcode() uint16 { return OutputEventName }

func (e *OutputNameEvent) Unmarshal(r *wire.Reader) error {
	name, err := r.String()
	if err != nil {
		return err
	}
	e.Name = name
	return nil
}

func (e *OutputNameEvent) Since() uint32 { return 4 }

type OutputDescriptionEvent struct {
	Description string
}

func (e *OutputDescriptionEvent) Opcode() uint16 { return OutputEventDescription }

func (e *OutputDescriptionEvent) Unmarshal(r *wire.Reader) error {
	description, err := r.String()
	if err != nil {
		return err
	}
	e.Description = description
	return nil
}

func (e *OutputDescriptionEvent) Since() uint32 { return 4 }

type OutputGeometryFunc func(ev OutputGeometryEvent)

type OutputModeFunc func(ev OutputModeEvent)

type OutputDoneFunc func(ev OutputDoneEvent)

type OutputScaleFunc func(ev OutputScaleEvent)

type OutputNameFunc func(ev OutputNameEvent)

type OutputDescriptionFunc func(ev OutputDescriptionEvent)

type Output struct {
	proxy *Proxy
}

func NewOutput(p *Proxy) *Output {
	p.SetEventFDCounts(outputEventFDCounts)
	return &Output{proxy: p}
}

func (o *Output) Proxy() *Proxy {
	return o.proxy
}

func (o *Output) OnGeometry(fn OutputGeometryFunc) {
	o.proxy.RegisterEvent(OutputEventGeometry, func(r *wire.Reader) {
		var ev OutputGeometryEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Geometry", err)
			return
		}

		fn(ev)
	})
}

func (o *Output) OnMode(fn OutputModeFunc) {
	o.proxy.RegisterEvent(OutputEventMode, func(r *wire.Reader) {
		var ev OutputModeEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Mode", err)
			return
		}

		fn(ev)
	})
}

func (o *Output) OnDone(fn OutputDoneFunc) {
	o.proxy.RegisterEvent(OutputEventDone, func(r *wire.Reader) {
		var ev OutputDoneEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Done", err)
			return
		}

		fn(ev)
	})
}

func (o *Output) OnScale(fn OutputScaleFunc) {
	o.proxy.RegisterEvent(OutputEventScale, func(r *wire.Reader) {
		var ev OutputScaleEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Scale", err)
			return
		}

		fn(ev)
	})
}

func (o *Output) OnName(fn OutputNameFunc) {
	o.proxy.RegisterEvent(OutputEventName, func(r *wire.Reader) {
		var ev OutputNameEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Name", err)
			return
		}

		fn(ev)
	})
}

func (o *Output) OnDescription(fn OutputDescriptionFunc) {
	o.proxy.RegisterEvent(OutputEventDescription, func(r *wire.Reader) {
		var ev OutputDescriptionEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Description", err)
			return
		}

		fn(ev)
	})
}

func (o *Output) Release() error {
	if v := o.proxy.Version(); v > 0 && v < uint32(3) {
		return ErrVersionMismatch
	}
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(OutputRequestRelease, &OutputReleaseRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

func BindOutput(b Binder, name uint32, version uint32) (*Output, error) {
	if version < 1 || version > VersionOutput {
		return nil, ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceOutput, version)
	if err != nil {
		return nil, err
	}
	x := NewOutput(p)
	x.proxy.SetVersion(version)
	return x, nil
}
