// Code generated by wayland-scanner. DO NOT EDIT.

package wayland

import (
	"github.com/xogas/wayland/wire"
)

const InterfaceSurface = "wl_surface"
const VersionSurface = 7

const (
	SurfaceRequestDestroy            uint16 = 0
	SurfaceRequestAttach             uint16 = 1
	SurfaceRequestDamage             uint16 = 2
	SurfaceRequestFrame              uint16 = 3
	SurfaceRequestSetOpaqueRegion    uint16 = 4
	SurfaceRequestSetInputRegion     uint16 = 5
	SurfaceRequestCommit             uint16 = 6
	SurfaceRequestSetBufferTransform uint16 = 7
	SurfaceRequestSetBufferScale     uint16 = 8
	SurfaceRequestDamageBuffer       uint16 = 9
	SurfaceRequestOffset             uint16 = 10
	SurfaceRequestGetRelease         uint16 = 11
)

const (
	SurfaceEventEnter                    uint16 = 0
	SurfaceEventLeave                    uint16 = 1
	SurfaceEventPreferredBufferScale     uint16 = 2
	SurfaceEventPreferredBufferTransform uint16 = 3
)

// surfaceEventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var surfaceEventFDCounts = map[uint16]int{
	0: 0,
	1: 0,
	2: 0,
	3: 0,
}

func init() {
	RegisterInterfaceFDCounts(InterfaceSurface, surfaceEventFDCounts)
}

// SurfaceError wl_surface error values.
//
// These errors can be emitted in response to wl_surface requests.
type SurfaceError uint32

const (
	// SurfaceErrorInvalidScale buffer scale value is invalid.
	SurfaceErrorInvalidScale SurfaceError = 0

	// SurfaceErrorInvalidTransform buffer transform value is invalid.
	SurfaceErrorInvalidTransform SurfaceError = 1

	// SurfaceErrorInvalidSize buffer size is invalid.
	SurfaceErrorInvalidSize SurfaceError = 2

	// SurfaceErrorInvalidOffset buffer offset is invalid.
	SurfaceErrorInvalidOffset SurfaceError = 3

	// SurfaceErrorDefunctRoleObject surface was destroyed before its role object.
	SurfaceErrorDefunctRoleObject SurfaceError = 4

	// SurfaceErrorNoBuffer no buffer was attached.
	SurfaceErrorNoBuffer SurfaceError = 5
)

// SurfaceDestroyRequest delete surface.
//
// Deletes the surface and invalidates its object ID.
type SurfaceDestroyRequest struct {
}

func (r *SurfaceDestroyRequest) Opcode() uint16 { return SurfaceRequestDestroy }

func (r *SurfaceDestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SurfaceDestroyRequest) Since() uint32 { return 1 }

// SurfaceAttachRequest set the surface contents.
//
// Set a buffer as the content of this surface.
//
// The new size of the surface is calculated based on the buffer
// size transformed by the inverse buffer_transform and the
// inverse buffer_scale. This means that at commit time the supplied
// buffer size must be an integer multiple of the buffer_scale. If
// that's not the case, an invalid_size error is sent.
//
// The x and y arguments specify the location of the new pending
// buffer's upper left corner, relative to the current buffer's upper
// left corner, in surface-local coordinates. In other words, the
// x and y, combined with the new surface size define in which
// directions the surface's size changes. Setting anything other than 0
// as x and y arguments is discouraged, and should instead be replaced
// with using the separate wl_surface.offset request.
//
// When the bound wl_surface version is 5 or higher, passing any
// non-zero x or y is a protocol violation, and will result in an
// 'invalid_offset' error being raised. The x and y arguments are ignored
// and do not change the pending state. To achieve equivalent semantics,
// use wl_surface.offset.
//
// Surface contents are double-buffered state, see wl_surface.commit.
//
// The initial surface contents are void; there is no content.
// wl_surface.attach assigns the given wl_buffer as the pending
// wl_buffer. wl_surface.commit makes the pending wl_buffer the new
// surface contents, and the size of the surface becomes the size
// calculated from the wl_buffer, as described above. After commit,
// there is no pending buffer until the next attach.
//
// Committing a pending wl_buffer allows the compositor to read the
// pixels in the wl_buffer. The compositor may access the pixels at
// any time after the wl_surface.commit request. When the compositor
// will not access the pixels anymore, it will send the
// wl_buffer.release event. Only after receiving wl_buffer.release,
// the client may reuse the wl_buffer. A wl_buffer that has been
// attached and then replaced by another attach instead of committed
// will not receive a release event, and is not used by the
// compositor.
//
// If a pending wl_buffer has been committed to more than one wl_surface,
// the delivery of wl_buffer.release events becomes undefined. A well
// behaved client should not rely on wl_buffer.release events in this
// case. Instead, clients hitting this case should use
// wl_surface.get_release or use a protocol extension providing per-commit
// release notifications (if none of these options are available, a
// fallback can be implemented by creating multiple wl_buffer objects from
// the same backing storage).
//
// Destroying the wl_buffer after wl_buffer.release does not change
// the surface contents. Destroying the wl_buffer before wl_buffer.release
// is allowed as long as the underlying buffer storage isn't re-used (this
// can happen e.g. on client process termination). However, if the client
// destroys the wl_buffer before receiving the wl_buffer.release event and
// mutates the underlying buffer storage, the surface contents become
// undefined immediately.
//
// If wl_surface.attach is sent with a NULL wl_buffer, the
// following wl_surface.commit will remove the surface content.
//
// If a pending wl_buffer has been destroyed, the result is not specified.
// Many compositors are known to remove the surface content on the following
// wl_surface.commit, but this behaviour is not universal. Clients seeking to
// maximise compatibility should not destroy pending buffers and should
// ensure that they explicitly remove content from surfaces, even after
// destroying buffers.
type SurfaceAttachRequest struct {
	// Buffer buffer of surface contents.
	Buffer wire.ObjectID // nullable
	// X surface-local x coordinate.
	X int32
	// Y surface-local y coordinate.
	Y int32
}

func (r *SurfaceAttachRequest) Opcode() uint16 { return SurfaceRequestAttach }

func (r *SurfaceAttachRequest) Marshal(w *wire.Writer) error {
	if err := w.Object(r.Buffer); err != nil {
		return err
	}
	if err := w.Int32(r.X); err != nil {
		return err
	}
	if err := w.Int32(r.Y); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceAttachRequest) Since() uint32 { return 1 }

// SurfaceDamageRequest mark part of the surface damaged.
//
// This request is used to describe the regions where the pending
// buffer is different from the current surface contents, and where
// the surface therefore needs to be repainted. The compositor
// ignores the parts of the damage that fall outside of the surface.
//
// Damage is double-buffered state, see wl_surface.commit.
//
// The damage rectangle is specified in surface-local coordinates,
// where x and y specify the upper left corner of the damage rectangle.
//
// The initial value for pending damage is empty: no damage.
// wl_surface.damage adds pending damage: the new pending damage
// is the union of old pending damage and the given rectangle.
//
// wl_surface.commit assigns pending damage as the current damage,
// and clears pending damage. The server will clear the current
// damage as it repaints the surface.
//
// Note! New clients should not use this request. Instead damage can be
// posted with wl_surface.damage_buffer which uses buffer coordinates
// instead of surface coordinates.
type SurfaceDamageRequest struct {
	// X surface-local x coordinate.
	X int32
	// Y surface-local y coordinate.
	Y int32
	// Width width of damage rectangle.
	Width int32
	// Height height of damage rectangle.
	Height int32
}

func (r *SurfaceDamageRequest) Opcode() uint16 { return SurfaceRequestDamage }

func (r *SurfaceDamageRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.X); err != nil {
		return err
	}
	if err := w.Int32(r.Y); err != nil {
		return err
	}
	if err := w.Int32(r.Width); err != nil {
		return err
	}
	if err := w.Int32(r.Height); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceDamageRequest) Since() uint32 { return 1 }

// SurfaceFrameRequest request a frame throttling hint.
//
// Request a notification when it is a good time to start drawing a new
// frame, by creating a frame callback. This is useful for throttling
// redrawing operations, and driving animations.
//
// When a client is animating on a wl_surface, it can use the 'frame'
// request to get notified when it is a good time to draw and commit the
// next frame of animation. If the client commits an update earlier than
// that, it is likely that some updates will not make it to the display,
// and the client is wasting resources by drawing too often.
//
// The frame request will take effect on the next wl_surface.commit.
// The notification will only be posted for one frame unless
// requested again. For a wl_surface, the notifications are posted in
// the order the frame requests were committed.
//
// The server must send the notifications so that a client
// will not send excessive updates, while still allowing
// the highest possible update rate for clients that wait for the reply
// before drawing again. The server should give some time for the client
// to draw and commit after sending the frame callback events to let it
// hit the next output refresh.
//
// A server should avoid signaling the frame callbacks if the
// surface is not visible in any way, e.g. the surface is off-screen,
// or completely obscured by other opaque surfaces.
//
// The object returned by this request will be destroyed by the
// compositor after the callback is fired and as such the client must not
// attempt to use it after that point.
//
// The callback_data passed in the callback is the current time, in
// milliseconds, with an undefined base.
type SurfaceFrameRequest struct {
	// Callback callback object for the frame request.
	Callback wire.NewID
}

func (r *SurfaceFrameRequest) Opcode() uint16 { return SurfaceRequestFrame }

func (r *SurfaceFrameRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.Callback); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceFrameRequest) Since() uint32 { return 1 }

// SurfaceSetOpaqueRegionRequest set opaque region.
//
// This request sets the region of the surface that contains
// opaque content.
//
// The opaque region is an optimization hint for the compositor
// that lets it optimize the redrawing of content behind opaque
// regions.  Setting an opaque region is not required for correct
// behaviour, but marking transparent content as opaque will result
// in repaint artifacts.
//
// The opaque region is specified in surface-local coordinates.
//
// The compositor ignores the parts of the opaque region that fall
// outside of the surface.
//
// Opaque region is double-buffered state, see wl_surface.commit.
//
// wl_surface.set_opaque_region changes the pending opaque region.
// wl_surface.commit copies the pending region to the current region.
// Otherwise, the pending and current regions are never changed.
//
// The initial value for an opaque region is empty. Setting the pending
// opaque region has copy semantics, and the wl_region object can be
// destroyed immediately. A NULL wl_region causes the pending opaque
// region to be set to empty.
type SurfaceSetOpaqueRegionRequest struct {
	// Region opaque region of the surface.
	Region wire.ObjectID // nullable
}

func (r *SurfaceSetOpaqueRegionRequest) Opcode() uint16 { return SurfaceRequestSetOpaqueRegion }

func (r *SurfaceSetOpaqueRegionRequest) Marshal(w *wire.Writer) error {
	if err := w.Object(r.Region); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceSetOpaqueRegionRequest) Since() uint32 { return 1 }

// SurfaceSetInputRegionRequest set input region.
//
// This request sets the region of the surface that can receive
// pointer and touch events.
//
// Input events happening outside of this region will try the next
// surface in the server surface stack. The compositor ignores the
// parts of the input region that fall outside of the surface.
//
// The input region is specified in surface-local coordinates.
//
// Input region is double-buffered state, see wl_surface.commit.
//
// wl_surface.set_input_region changes the pending input region.
// wl_surface.commit copies the pending region to the current region.
// Otherwise the pending and current regions are never changed,
// except cursor and icon surfaces are special cases, see
// wl_pointer.set_cursor and wl_data_device.start_drag.
//
// The initial value for an input region is infinite. That means the
// whole surface will accept input. Setting the pending input region
// has copy semantics, and the wl_region object can be destroyed
// immediately. A NULL wl_region causes the input region to be set
// to infinite.
type SurfaceSetInputRegionRequest struct {
	// Region input region of the surface.
	Region wire.ObjectID // nullable
}

func (r *SurfaceSetInputRegionRequest) Opcode() uint16 { return SurfaceRequestSetInputRegion }

func (r *SurfaceSetInputRegionRequest) Marshal(w *wire.Writer) error {
	if err := w.Object(r.Region); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceSetInputRegionRequest) Since() uint32 { return 1 }

// SurfaceCommitRequest commit pending surface state.
//
// Surface state (input, opaque, and damage regions, attached buffers,
// etc.) is double-buffered. Protocol requests modify the pending state,
// as opposed to the active state in use by the compositor.
//
// All requests that need a commit to become effective are documented
// to affect double-buffered state.
//
// Other interfaces may add further double-buffered surface state.
//
// A commit request atomically creates a Content Update (CU) from the
// pending state, even if the pending state has not been touched. The
// content update is placed at the end of a per-surface queue until it
// becomes active. After commit, the new pending state is as documented for
// each related request.
//
// A CU is either a Desync Content Update (DCU) or a Sync Content Update
// (SCU). If the surface is effectively synchronized at the commit request,
// it is a SCU, otherwise a DCU.
//
// When a surface transitions from effectively synchronized to effectively
// desynchronized, all SCUs in its queue which are not reachable by any
// DCU become DCUs and dependency edges from outside the queue to these CUs
// are removed.
//
// See wl_subsurface for the definition of 'effectively synchronized' and
// 'effectively desynchronized'.
//
// When a CU is placed in the queue, the CU has a dependency on the CU in
// front of it and to the SCU at end of the queue of every direct child
// surface if that SCU exists and does not have another dependent. This can
// form a directed acyclic graph of CUs with dependencies as edges.
//
// In addition to surface state, the CU can have constraints that must be
// satisfied before it can be applied. Other interfaces may add CU
// constraints.
//
// All DCUs which do not have a SCU in front of themselves in their queue,
// are candidates. If the graph that's reachable by a candidate does not
// have any unsatisfied constraints, the entire graph must be applied
// atomically.
//
// When a CU is applied, the wl_buffer is applied before all other state.
// This means that all coordinates in double-buffered state are relative to
// the newly attached wl_buffers, except for wl_surface.attach itself. If
// there is no newly attached wl_buffer, the coordinates are relative to
// the previous content update.
type SurfaceCommitRequest struct {
}

func (r *SurfaceCommitRequest) Opcode() uint16 { return SurfaceRequestCommit }

func (r *SurfaceCommitRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SurfaceCommitRequest) Since() uint32 { return 1 }

// SurfaceSetBufferTransformRequest sets the buffer transformation.
//
// This request sets the transformation that the client has already applied
// to the content of the buffer. The accepted values for the transform
// parameter are the values for wl_output.transform.
//
// The compositor applies the inverse of this transformation whenever it
// uses the buffer contents.
//
// Buffer transform is double-buffered state, see wl_surface.commit.
//
// A newly created surface has its buffer transformation set to normal.
//
// wl_surface.set_buffer_transform changes the pending buffer
// transformation. wl_surface.commit copies the pending buffer
// transformation to the current one. Otherwise, the pending and current
// values are never changed.
//
// The purpose of this request is to allow clients to render content
// according to the output transform, thus permitting the compositor to
// use certain optimizations even if the display is rotated. Using
// hardware overlays and scanning out a client buffer for fullscreen
// surfaces are examples of such optimizations. Those optimizations are
// highly dependent on the compositor implementation, so the use of this
// request should be considered on a case-by-case basis.
//
// Note that if the transform value includes 90 or 270 degree rotation,
// the width of the buffer will become the surface height and the height
// of the buffer will become the surface width.
//
// If transform is not one of the values from the
// wl_output.transform enum the invalid_transform protocol error
// is raised.
type SurfaceSetBufferTransformRequest struct {
	// Transform transform for interpreting buffer contents.
	Transform int32
}

func (r *SurfaceSetBufferTransformRequest) Opcode() uint16 { return SurfaceRequestSetBufferTransform }

func (r *SurfaceSetBufferTransformRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.Transform); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceSetBufferTransformRequest) Since() uint32 { return 2 }

// SurfaceSetBufferScaleRequest sets the buffer scaling factor.
//
// This request sets an optional scaling factor on how the compositor
// interprets the contents of the buffer attached to the window.
//
// Buffer scale is double-buffered state, see wl_surface.commit.
//
// A newly created surface has its buffer scale set to 1.
//
// wl_surface.set_buffer_scale changes the pending buffer scale.
// wl_surface.commit copies the pending buffer scale to the current one.
// Otherwise, the pending and current values are never changed.
//
// The purpose of this request is to allow clients to supply higher
// resolution buffer data for use on high resolution outputs. It is
// intended that you pick the same buffer scale as the scale of the
// output that the surface is displayed on. This means the compositor
// can avoid scaling when rendering the surface on that output.
//
// Note that if the scale is larger than 1, then you have to attach
// a buffer that is larger (by a factor of scale in each dimension)
// than the desired surface size.
//
// If scale is not greater than 0 the invalid_scale protocol error is
// raised.
type SurfaceSetBufferScaleRequest struct {
	// Scale scale for interpreting buffer contents.
	Scale int32
}

func (r *SurfaceSetBufferScaleRequest) Opcode() uint16 { return SurfaceRequestSetBufferScale }

func (r *SurfaceSetBufferScaleRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.Scale); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceSetBufferScaleRequest) Since() uint32 { return 3 }

// SurfaceDamageBufferRequest mark part of the surface damaged using buffer coordinates.
//
// This request is used to describe the regions where the pending
// buffer is different from the current surface contents, and where
// the surface therefore needs to be repainted. The compositor
// ignores the parts of the damage that fall outside of the surface.
//
// Damage is double-buffered state, see wl_surface.commit.
//
// The damage rectangle is specified in buffer coordinates,
// where x and y specify the upper left corner of the damage rectangle.
//
// The initial value for pending damage is empty: no damage.
// wl_surface.damage_buffer adds pending damage: the new pending
// damage is the union of old pending damage and the given rectangle.
//
// wl_surface.commit assigns pending damage as the current damage,
// and clears pending damage. The server will clear the current
// damage as it repaints the surface.
//
// This request differs from wl_surface.damage in only one way - it
// takes damage in buffer coordinates instead of surface-local
// coordinates. While this generally is more intuitive than surface
// coordinates, it is especially desirable when using wp_viewport
// or when a drawing library (like EGL) is unaware of buffer scale
// and buffer transform.
//
// Note: Because buffer transformation changes and damage requests may
// be interleaved in the protocol stream, it is impossible to determine
// the actual mapping between surface and buffer damage until
// wl_surface.commit time. Therefore, compositors wishing to take both
// kinds of damage into account will have to accumulate damage from the
// two requests separately and only transform from one to the other
// after receiving the wl_surface.commit.
type SurfaceDamageBufferRequest struct {
	// X buffer-local x coordinate.
	X int32
	// Y buffer-local y coordinate.
	Y int32
	// Width width of damage rectangle.
	Width int32
	// Height height of damage rectangle.
	Height int32
}

func (r *SurfaceDamageBufferRequest) Opcode() uint16 { return SurfaceRequestDamageBuffer }

func (r *SurfaceDamageBufferRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.X); err != nil {
		return err
	}
	if err := w.Int32(r.Y); err != nil {
		return err
	}
	if err := w.Int32(r.Width); err != nil {
		return err
	}
	if err := w.Int32(r.Height); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceDamageBufferRequest) Since() uint32 { return 4 }

// SurfaceOffsetRequest set the surface contents offset.
//
// The x and y arguments specify the location of the new pending
// buffer's upper left corner, relative to the current buffer's upper
// left corner, in surface-local coordinates. In other words, the
// x and y, combined with the new surface size define in which
// directions the surface's size changes.
//
// The exact semantics of wl_surface.offset are role-specific. Refer to
// the documentation of specific roles for more information.
//
// Surface location offset is double-buffered state, see
// wl_surface.commit.
//
// This request is semantically equivalent to and the replaces the x and y
// arguments in the wl_surface.attach request in wl_surface versions prior
// to 5. See wl_surface.attach for details.
type SurfaceOffsetRequest struct {
	// X surface-local x coordinate.
	X int32
	// Y surface-local y coordinate.
	Y int32
}

func (r *SurfaceOffsetRequest) Opcode() uint16 { return SurfaceRequestOffset }

func (r *SurfaceOffsetRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.X); err != nil {
		return err
	}
	if err := w.Int32(r.Y); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceOffsetRequest) Since() uint32 { return 5 }

// SurfaceGetReleaseRequest get a release callback.
//
// Create a callback for the release of the buffer attached by the client
// with wl_surface.attach.
//
// The compositor will release the buffer when it has finished its usage of
// the underlying storage for the relevant commit. Once the client receives
// this event, and assuming the associated buffer is not pending release
// from other wl_surface.commit requests, the client can safely re-use the
// buffer.
//
// Release callbacks are double-buffered state, and will be associated
// with the pending buffer at wl_surface.commit time.
//
// The callback_data passed in the wl_callback.done event is unused and
// is always zero.
//
// Sending this request without attaching a non-null buffer in the same
// content update is a protocol error. The compositor will send the
// no_buffer error in this case.
type SurfaceGetReleaseRequest struct {
	// Callback callback object for the release.
	Callback wire.NewID
}

func (r *SurfaceGetReleaseRequest) Opcode() uint16 { return SurfaceRequestGetRelease }

func (r *SurfaceGetReleaseRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.Callback); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceGetReleaseRequest) Since() uint32 { return 7 }

// SurfaceEnterEvent surface enters an output.
//
// This is emitted whenever a surface's creation, movement, or resizing
// results in some part of it being within the scanout region of an
// output.
//
// Note that a surface may be overlapping with zero or more outputs.
type SurfaceEnterEvent struct {
	// Output output entered by the surface.
	Output wire.ObjectID
}

func (e *SurfaceEnterEvent) Opcode() uint16 { return SurfaceEventEnter }

func (e *SurfaceEnterEvent) Unmarshal(r *wire.Reader) error {
	output, err := r.Object()
	if err != nil {
		return err
	}
	e.Output = output
	return nil
}

func (e *SurfaceEnterEvent) Since() uint32 { return 1 }

// SurfaceLeaveEvent surface leaves an output.
//
// This is emitted whenever a surface's creation, movement, or resizing
// results in it no longer having any part of it within the scanout region
// of an output.
//
// Clients should not use the number of outputs the surface is on for frame
// throttling purposes. The surface might be hidden even if no leave event
// has been sent, and the compositor might expect new surface content
// updates even if no enter event has been sent. The frame event should be
// used instead.
type SurfaceLeaveEvent struct {
	// Output output left by the surface.
	Output wire.ObjectID
}

func (e *SurfaceLeaveEvent) Opcode() uint16 { return SurfaceEventLeave }

func (e *SurfaceLeaveEvent) Unmarshal(r *wire.Reader) error {
	output, err := r.Object()
	if err != nil {
		return err
	}
	e.Output = output
	return nil
}

func (e *SurfaceLeaveEvent) Since() uint32 { return 1 }

// SurfacePreferredBufferScaleEvent preferred buffer scale for the surface.
//
// This event indicates the preferred buffer scale for this surface. It is
// sent whenever the compositor's preference changes.
//
// Before receiving this event the preferred buffer scale for this surface
// is 1.
//
// It is intended that scaling aware clients use this event to scale their
// content and use wl_surface.set_buffer_scale to indicate the scale they
// have rendered with. This allows clients to supply a higher detail
// buffer.
//
// The compositor shall emit a scale value greater than 0.
type SurfacePreferredBufferScaleEvent struct {
	// Factor preferred scaling factor.
	Factor int32
}

func (e *SurfacePreferredBufferScaleEvent) Opcode() uint16 { return SurfaceEventPreferredBufferScale }

func (e *SurfacePreferredBufferScaleEvent) Unmarshal(r *wire.Reader) error {
	factor, err := r.Int32()
	if err != nil {
		return err
	}
	e.Factor = factor
	return nil
}

func (e *SurfacePreferredBufferScaleEvent) Since() uint32 { return 6 }

// SurfacePreferredBufferTransformEvent preferred buffer transform for the surface.
//
// This event indicates the preferred buffer transform for this surface.
// It is sent whenever the compositor's preference changes.
//
// Before receiving this event the preferred buffer transform for this
// surface is normal.
//
// Applying this transformation to the surface buffer contents and using
// wl_surface.set_buffer_transform might allow the compositor to use the
// surface buffer more efficiently.
type SurfacePreferredBufferTransformEvent struct {
	// Transform preferred transform.
	Transform OutputTransform
}

func (e *SurfacePreferredBufferTransformEvent) Opcode() uint16 {
	return SurfaceEventPreferredBufferTransform
}

func (e *SurfacePreferredBufferTransformEvent) Unmarshal(r *wire.Reader) error {
	transform, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Transform = OutputTransform(transform)
	return nil
}

func (e *SurfacePreferredBufferTransformEvent) Since() uint32 { return 6 }

// SurfaceEnterFunc is a callback for Enter events.
type SurfaceEnterFunc func(ev SurfaceEnterEvent)

// SurfaceLeaveFunc is a callback for Leave events.
type SurfaceLeaveFunc func(ev SurfaceLeaveEvent)

// SurfacePreferredBufferScaleFunc is a callback for PreferredBufferScale events.
type SurfacePreferredBufferScaleFunc func(ev SurfacePreferredBufferScaleEvent)

// SurfacePreferredBufferTransformFunc is a callback for PreferredBufferTransform events.
type SurfacePreferredBufferTransformFunc func(ev SurfacePreferredBufferTransformEvent)

// Surface an onscreen surface.
//
// A surface is a rectangular area that may be displayed on zero
// or more outputs, and shown any number of times at the compositor's
// discretion. They can present wl_buffers, receive user input, and
// define a local coordinate system.
//
// The size of a surface (and relative positions on it) is described
// in surface-local coordinates, which may differ from the buffer
// coordinates of the pixel content, in case a buffer_transform
// or a buffer_scale is used.
//
// A surface without a "role" is fairly useless: a compositor does
// not know where, when or how to present it. The role is the
// purpose of a wl_surface. Examples of roles are a cursor for a
// pointer (as set by wl_pointer.set_cursor), a drag icon
// (wl_data_device.start_drag), a sub-surface
// (wl_subcompositor.get_subsurface), and a window as defined by a
// shell protocol (e.g. wl_shell.get_shell_surface).
//
// A surface can have only one role at a time. Initially a
// wl_surface does not have a role. Once a wl_surface is given a
// role, it is set permanently for the whole lifetime of the
// wl_surface object. Giving the current role again is allowed,
// unless explicitly forbidden by the relevant interface
// specification.
//
// Surface roles are given by requests in other interfaces such as
// wl_pointer.set_cursor. The request should explicitly mention
// that this request gives a role to a wl_surface. Often, this
// request also creates a new protocol object that represents the
// role and adds additional functionality to wl_surface. When a
// client wants to destroy a wl_surface, they must destroy this role
// object before the wl_surface, otherwise a defunct_role_object error is
// sent.
//
// Destroying the role object does not remove the role from the
// wl_surface, but it may stop the wl_surface from "playing the role".
// For instance, if a wl_subsurface object is destroyed, the wl_surface
// it was created for will be unmapped and forget its position and
// z-order. It is allowed to create a wl_subsurface for the same
// wl_surface again, but it is not allowed to use the wl_surface as
// a cursor (cursor is a different role than sub-surface, and role
// switching is not allowed).
type Surface struct {
	proxy *Proxy
}

// NewSurface wraps p in a Surface proxy.
func NewSurface(p *Proxy) *Surface {
	p.SetEventFDCounts(surfaceEventFDCounts)
	return &Surface{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *Surface) Proxy() *Proxy {
	return o.proxy
}

// OnEnter registers fn to receive Enter events.
func (o *Surface) OnEnter(fn SurfaceEnterFunc) {
	o.proxy.RegisterEvent(SurfaceEventEnter, func(r *wire.Reader) {
		var ev SurfaceEnterEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Enter", err)
			return
		}

		fn(ev)
	})
}

// OnLeave registers fn to receive Leave events.
func (o *Surface) OnLeave(fn SurfaceLeaveFunc) {
	o.proxy.RegisterEvent(SurfaceEventLeave, func(r *wire.Reader) {
		var ev SurfaceLeaveEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Leave", err)
			return
		}

		fn(ev)
	})
}

// OnPreferredBufferScale registers fn to receive PreferredBufferScale events.
func (o *Surface) OnPreferredBufferScale(fn SurfacePreferredBufferScaleFunc) {
	o.proxy.RegisterEvent(SurfaceEventPreferredBufferScale, func(r *wire.Reader) {
		var ev SurfacePreferredBufferScaleEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("PreferredBufferScale", err)
			return
		}

		fn(ev)
	})
}

// OnPreferredBufferTransform registers fn to receive PreferredBufferTransform events.
func (o *Surface) OnPreferredBufferTransform(fn SurfacePreferredBufferTransformFunc) {
	o.proxy.RegisterEvent(SurfaceEventPreferredBufferTransform, func(r *wire.Reader) {
		var ev SurfacePreferredBufferTransformEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("PreferredBufferTransform", err)
			return
		}

		fn(ev)
	})
}

// Destroy delete surface.
//
// Deletes the surface and invalidates its object ID.
func (o *Surface) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(SurfaceRequestDestroy, &SurfaceDestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// Attach set the surface contents.
//
// Set a buffer as the content of this surface.
//
// The new size of the surface is calculated based on the buffer
// size transformed by the inverse buffer_transform and the
// inverse buffer_scale. This means that at commit time the supplied
// buffer size must be an integer multiple of the buffer_scale. If
// that's not the case, an invalid_size error is sent.
//
// The x and y arguments specify the location of the new pending
// buffer's upper left corner, relative to the current buffer's upper
// left corner, in surface-local coordinates. In other words, the
// x and y, combined with the new surface size define in which
// directions the surface's size changes. Setting anything other than 0
// as x and y arguments is discouraged, and should instead be replaced
// with using the separate wl_surface.offset request.
//
// When the bound wl_surface version is 5 or higher, passing any
// non-zero x or y is a protocol violation, and will result in an
// 'invalid_offset' error being raised. The x and y arguments are ignored
// and do not change the pending state. To achieve equivalent semantics,
// use wl_surface.offset.
//
// Surface contents are double-buffered state, see wl_surface.commit.
//
// The initial surface contents are void; there is no content.
// wl_surface.attach assigns the given wl_buffer as the pending
// wl_buffer. wl_surface.commit makes the pending wl_buffer the new
// surface contents, and the size of the surface becomes the size
// calculated from the wl_buffer, as described above. After commit,
// there is no pending buffer until the next attach.
//
// Committing a pending wl_buffer allows the compositor to read the
// pixels in the wl_buffer. The compositor may access the pixels at
// any time after the wl_surface.commit request. When the compositor
// will not access the pixels anymore, it will send the
// wl_buffer.release event. Only after receiving wl_buffer.release,
// the client may reuse the wl_buffer. A wl_buffer that has been
// attached and then replaced by another attach instead of committed
// will not receive a release event, and is not used by the
// compositor.
//
// If a pending wl_buffer has been committed to more than one wl_surface,
// the delivery of wl_buffer.release events becomes undefined. A well
// behaved client should not rely on wl_buffer.release events in this
// case. Instead, clients hitting this case should use
// wl_surface.get_release or use a protocol extension providing per-commit
// release notifications (if none of these options are available, a
// fallback can be implemented by creating multiple wl_buffer objects from
// the same backing storage).
//
// Destroying the wl_buffer after wl_buffer.release does not change
// the surface contents. Destroying the wl_buffer before wl_buffer.release
// is allowed as long as the underlying buffer storage isn't re-used (this
// can happen e.g. on client process termination). However, if the client
// destroys the wl_buffer before receiving the wl_buffer.release event and
// mutates the underlying buffer storage, the surface contents become
// undefined immediately.
//
// If wl_surface.attach is sent with a NULL wl_buffer, the
// following wl_surface.commit will remove the surface content.
//
// If a pending wl_buffer has been destroyed, the result is not specified.
// Many compositors are known to remove the surface content on the following
// wl_surface.commit, but this behaviour is not universal. Clients seeking to
// maximise compatibility should not destroy pending buffers and should
// ensure that they explicitly remove content from surfaces, even after
// destroying buffers.
func (o *Surface) Attach(buffer wire.ObjectID, x int32, y int32) error {
	return o.proxy.SendRequest(SurfaceRequestAttach, &SurfaceAttachRequest{
		Buffer: buffer,
		X:      x,
		Y:      y,
	})
}

// Damage mark part of the surface damaged.
//
// This request is used to describe the regions where the pending
// buffer is different from the current surface contents, and where
// the surface therefore needs to be repainted. The compositor
// ignores the parts of the damage that fall outside of the surface.
//
// Damage is double-buffered state, see wl_surface.commit.
//
// The damage rectangle is specified in surface-local coordinates,
// where x and y specify the upper left corner of the damage rectangle.
//
// The initial value for pending damage is empty: no damage.
// wl_surface.damage adds pending damage: the new pending damage
// is the union of old pending damage and the given rectangle.
//
// wl_surface.commit assigns pending damage as the current damage,
// and clears pending damage. The server will clear the current
// damage as it repaints the surface.
//
// Note! New clients should not use this request. Instead damage can be
// posted with wl_surface.damage_buffer which uses buffer coordinates
// instead of surface coordinates.
func (o *Surface) Damage(x int32, y int32, width int32, height int32) error {
	return o.proxy.SendRequest(SurfaceRequestDamage, &SurfaceDamageRequest{
		X:      x,
		Y:      y,
		Width:  width,
		Height: height,
	})
}

// Frame request a frame throttling hint.
//
// Request a notification when it is a good time to start drawing a new
// frame, by creating a frame callback. This is useful for throttling
// redrawing operations, and driving animations.
//
// When a client is animating on a wl_surface, it can use the 'frame'
// request to get notified when it is a good time to draw and commit the
// next frame of animation. If the client commits an update earlier than
// that, it is likely that some updates will not make it to the display,
// and the client is wasting resources by drawing too often.
//
// The frame request will take effect on the next wl_surface.commit.
// The notification will only be posted for one frame unless
// requested again. For a wl_surface, the notifications are posted in
// the order the frame requests were committed.
//
// The server must send the notifications so that a client
// will not send excessive updates, while still allowing
// the highest possible update rate for clients that wait for the reply
// before drawing again. The server should give some time for the client
// to draw and commit after sending the frame callback events to let it
// hit the next output refresh.
//
// A server should avoid signaling the frame callbacks if the
// surface is not visible in any way, e.g. the surface is off-screen,
// or completely obscured by other opaque surfaces.
//
// The object returned by this request will be destroyed by the
// compositor after the callback is fired and as such the client must not
// attempt to use it after that point.
//
// The callback_data passed in the callback is the current time, in
// milliseconds, with an undefined base.
func (o *Surface) Frame() (*Callback, error) {
	conn := o.proxy.Conn()
	p := NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewCallback(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), SurfaceRequestFrame, &SurfaceFrameRequest{
		Callback: wire.NewID(p.ID()),
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// SetOpaqueRegion set opaque region.
//
// This request sets the region of the surface that contains
// opaque content.
//
// The opaque region is an optimization hint for the compositor
// that lets it optimize the redrawing of content behind opaque
// regions.  Setting an opaque region is not required for correct
// behaviour, but marking transparent content as opaque will result
// in repaint artifacts.
//
// The opaque region is specified in surface-local coordinates.
//
// The compositor ignores the parts of the opaque region that fall
// outside of the surface.
//
// Opaque region is double-buffered state, see wl_surface.commit.
//
// wl_surface.set_opaque_region changes the pending opaque region.
// wl_surface.commit copies the pending region to the current region.
// Otherwise, the pending and current regions are never changed.
//
// The initial value for an opaque region is empty. Setting the pending
// opaque region has copy semantics, and the wl_region object can be
// destroyed immediately. A NULL wl_region causes the pending opaque
// region to be set to empty.
func (o *Surface) SetOpaqueRegion(region wire.ObjectID) error {
	return o.proxy.SendRequest(SurfaceRequestSetOpaqueRegion, &SurfaceSetOpaqueRegionRequest{
		Region: region,
	})
}

// SetInputRegion set input region.
//
// This request sets the region of the surface that can receive
// pointer and touch events.
//
// Input events happening outside of this region will try the next
// surface in the server surface stack. The compositor ignores the
// parts of the input region that fall outside of the surface.
//
// The input region is specified in surface-local coordinates.
//
// Input region is double-buffered state, see wl_surface.commit.
//
// wl_surface.set_input_region changes the pending input region.
// wl_surface.commit copies the pending region to the current region.
// Otherwise the pending and current regions are never changed,
// except cursor and icon surfaces are special cases, see
// wl_pointer.set_cursor and wl_data_device.start_drag.
//
// The initial value for an input region is infinite. That means the
// whole surface will accept input. Setting the pending input region
// has copy semantics, and the wl_region object can be destroyed
// immediately. A NULL wl_region causes the input region to be set
// to infinite.
func (o *Surface) SetInputRegion(region wire.ObjectID) error {
	return o.proxy.SendRequest(SurfaceRequestSetInputRegion, &SurfaceSetInputRegionRequest{
		Region: region,
	})
}

// Commit commit pending surface state.
//
// Surface state (input, opaque, and damage regions, attached buffers,
// etc.) is double-buffered. Protocol requests modify the pending state,
// as opposed to the active state in use by the compositor.
//
// All requests that need a commit to become effective are documented
// to affect double-buffered state.
//
// Other interfaces may add further double-buffered surface state.
//
// A commit request atomically creates a Content Update (CU) from the
// pending state, even if the pending state has not been touched. The
// content update is placed at the end of a per-surface queue until it
// becomes active. After commit, the new pending state is as documented for
// each related request.
//
// A CU is either a Desync Content Update (DCU) or a Sync Content Update
// (SCU). If the surface is effectively synchronized at the commit request,
// it is a SCU, otherwise a DCU.
//
// When a surface transitions from effectively synchronized to effectively
// desynchronized, all SCUs in its queue which are not reachable by any
// DCU become DCUs and dependency edges from outside the queue to these CUs
// are removed.
//
// See wl_subsurface for the definition of 'effectively synchronized' and
// 'effectively desynchronized'.
//
// When a CU is placed in the queue, the CU has a dependency on the CU in
// front of it and to the SCU at end of the queue of every direct child
// surface if that SCU exists and does not have another dependent. This can
// form a directed acyclic graph of CUs with dependencies as edges.
//
// In addition to surface state, the CU can have constraints that must be
// satisfied before it can be applied. Other interfaces may add CU
// constraints.
//
// All DCUs which do not have a SCU in front of themselves in their queue,
// are candidates. If the graph that's reachable by a candidate does not
// have any unsatisfied constraints, the entire graph must be applied
// atomically.
//
// When a CU is applied, the wl_buffer is applied before all other state.
// This means that all coordinates in double-buffered state are relative to
// the newly attached wl_buffers, except for wl_surface.attach itself. If
// there is no newly attached wl_buffer, the coordinates are relative to
// the previous content update.
func (o *Surface) Commit() error {
	return o.proxy.SendRequest(SurfaceRequestCommit, &SurfaceCommitRequest{})
}

// SetBufferTransform sets the buffer transformation.
//
// This request sets the transformation that the client has already applied
// to the content of the buffer. The accepted values for the transform
// parameter are the values for wl_output.transform.
//
// The compositor applies the inverse of this transformation whenever it
// uses the buffer contents.
//
// Buffer transform is double-buffered state, see wl_surface.commit.
//
// A newly created surface has its buffer transformation set to normal.
//
// wl_surface.set_buffer_transform changes the pending buffer
// transformation. wl_surface.commit copies the pending buffer
// transformation to the current one. Otherwise, the pending and current
// values are never changed.
//
// The purpose of this request is to allow clients to render content
// according to the output transform, thus permitting the compositor to
// use certain optimizations even if the display is rotated. Using
// hardware overlays and scanning out a client buffer for fullscreen
// surfaces are examples of such optimizations. Those optimizations are
// highly dependent on the compositor implementation, so the use of this
// request should be considered on a case-by-case basis.
//
// Note that if the transform value includes 90 or 270 degree rotation,
// the width of the buffer will become the surface height and the height
// of the buffer will become the surface width.
//
// If transform is not one of the values from the
// wl_output.transform enum the invalid_transform protocol error
// is raised.
func (o *Surface) SetBufferTransform(transform int32) error {
	if v := o.proxy.Version(); v > 0 && v < uint32(2) {
		return ErrVersionMismatch
	}
	return o.proxy.SendRequest(SurfaceRequestSetBufferTransform, &SurfaceSetBufferTransformRequest{
		Transform: transform,
	})
}

// SetBufferScale sets the buffer scaling factor.
//
// This request sets an optional scaling factor on how the compositor
// interprets the contents of the buffer attached to the window.
//
// Buffer scale is double-buffered state, see wl_surface.commit.
//
// A newly created surface has its buffer scale set to 1.
//
// wl_surface.set_buffer_scale changes the pending buffer scale.
// wl_surface.commit copies the pending buffer scale to the current one.
// Otherwise, the pending and current values are never changed.
//
// The purpose of this request is to allow clients to supply higher
// resolution buffer data for use on high resolution outputs. It is
// intended that you pick the same buffer scale as the scale of the
// output that the surface is displayed on. This means the compositor
// can avoid scaling when rendering the surface on that output.
//
// Note that if the scale is larger than 1, then you have to attach
// a buffer that is larger (by a factor of scale in each dimension)
// than the desired surface size.
//
// If scale is not greater than 0 the invalid_scale protocol error is
// raised.
func (o *Surface) SetBufferScale(scale int32) error {
	if v := o.proxy.Version(); v > 0 && v < uint32(3) {
		return ErrVersionMismatch
	}
	return o.proxy.SendRequest(SurfaceRequestSetBufferScale, &SurfaceSetBufferScaleRequest{
		Scale: scale,
	})
}

// DamageBuffer mark part of the surface damaged using buffer coordinates.
//
// This request is used to describe the regions where the pending
// buffer is different from the current surface contents, and where
// the surface therefore needs to be repainted. The compositor
// ignores the parts of the damage that fall outside of the surface.
//
// Damage is double-buffered state, see wl_surface.commit.
//
// The damage rectangle is specified in buffer coordinates,
// where x and y specify the upper left corner of the damage rectangle.
//
// The initial value for pending damage is empty: no damage.
// wl_surface.damage_buffer adds pending damage: the new pending
// damage is the union of old pending damage and the given rectangle.
//
// wl_surface.commit assigns pending damage as the current damage,
// and clears pending damage. The server will clear the current
// damage as it repaints the surface.
//
// This request differs from wl_surface.damage in only one way - it
// takes damage in buffer coordinates instead of surface-local
// coordinates. While this generally is more intuitive than surface
// coordinates, it is especially desirable when using wp_viewport
// or when a drawing library (like EGL) is unaware of buffer scale
// and buffer transform.
//
// Note: Because buffer transformation changes and damage requests may
// be interleaved in the protocol stream, it is impossible to determine
// the actual mapping between surface and buffer damage until
// wl_surface.commit time. Therefore, compositors wishing to take both
// kinds of damage into account will have to accumulate damage from the
// two requests separately and only transform from one to the other
// after receiving the wl_surface.commit.
func (o *Surface) DamageBuffer(x int32, y int32, width int32, height int32) error {
	if v := o.proxy.Version(); v > 0 && v < uint32(4) {
		return ErrVersionMismatch
	}
	return o.proxy.SendRequest(SurfaceRequestDamageBuffer, &SurfaceDamageBufferRequest{
		X:      x,
		Y:      y,
		Width:  width,
		Height: height,
	})
}

// Offset set the surface contents offset.
//
// The x and y arguments specify the location of the new pending
// buffer's upper left corner, relative to the current buffer's upper
// left corner, in surface-local coordinates. In other words, the
// x and y, combined with the new surface size define in which
// directions the surface's size changes.
//
// The exact semantics of wl_surface.offset are role-specific. Refer to
// the documentation of specific roles for more information.
//
// Surface location offset is double-buffered state, see
// wl_surface.commit.
//
// This request is semantically equivalent to and the replaces the x and y
// arguments in the wl_surface.attach request in wl_surface versions prior
// to 5. See wl_surface.attach for details.
func (o *Surface) Offset(x int32, y int32) error {
	if v := o.proxy.Version(); v > 0 && v < uint32(5) {
		return ErrVersionMismatch
	}
	return o.proxy.SendRequest(SurfaceRequestOffset, &SurfaceOffsetRequest{
		X: x,
		Y: y,
	})
}

// GetRelease get a release callback.
//
// Create a callback for the release of the buffer attached by the client
// with wl_surface.attach.
//
// The compositor will release the buffer when it has finished its usage of
// the underlying storage for the relevant commit. Once the client receives
// this event, and assuming the associated buffer is not pending release
// from other wl_surface.commit requests, the client can safely re-use the
// buffer.
//
// Release callbacks are double-buffered state, and will be associated
// with the pending buffer at wl_surface.commit time.
//
// The callback_data passed in the wl_callback.done event is unused and
// is always zero.
//
// Sending this request without attaching a non-null buffer in the same
// content update is a protocol error. The compositor will send the
// no_buffer error in this case.
func (o *Surface) GetRelease() (*Callback, error) {
	if v := o.proxy.Version(); v > 0 && v < uint32(7) {
		return nil, ErrVersionMismatch
	}
	conn := o.proxy.Conn()
	p := NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewCallback(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), SurfaceRequestGetRelease, &SurfaceGetReleaseRequest{
		Callback: wire.NewID(p.ID()),
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// BindSurface binds the wl_surface global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionSurface] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindSurface(reg, name, min(g.Version,
// VersionSurface)), to bind at the highest mutually supported version.
func BindSurface(b Binder, name uint32, version uint32) (*Surface, error) {
	if version < 1 || version > VersionSurface {
		return nil, ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceSurface, version)
	if err != nil {
		return nil, err
	}
	x := NewSurface(p)
	x.proxy.SetVersion(version)
	return x, nil
}
