// Code generated by wayland-scanner. DO NOT EDIT.

package presentationtime

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfacePresentation = "wp_presentation"
const VersionPresentation = 2

const (
	PresentationRequestDestroy  uint16 = 0
	PresentationRequestFeedback uint16 = 1
)

const (
	PresentationEventClockID uint16 = 0
)

// presentationEventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var presentationEventFDCounts = map[uint16]int{
	0: 0,
}

type PresentationError uint32

const (
	PresentationErrorInvalidTimestamp PresentationError = 0
	PresentationErrorInvalidFlag      PresentationError = 1
)

type PresentationDestroyRequest struct {
}

func (r *PresentationDestroyRequest) Opcode() uint16 { return PresentationRequestDestroy }

func (r *PresentationDestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *PresentationDestroyRequest) Since() uint32 { return 1 }

type PresentationFeedbackRequest struct {
	Surface  wire.ObjectID
	Callback wire.NewID
}

func (r *PresentationFeedbackRequest) Opcode() uint16 { return PresentationRequestFeedback }

func (r *PresentationFeedbackRequest) Marshal(w *wire.Writer) error {
	if err := w.Object(r.Surface); err != nil {
		return err
	}
	if err := w.NewID(r.Callback); err != nil {
		return err
	}
	return nil
}

func (r *PresentationFeedbackRequest) Since() uint32 { return 1 }

type PresentationClockIDEvent struct {
	ClkID uint32
}

func (e *PresentationClockIDEvent) Opcode() uint16 { return PresentationEventClockID }

func (e *PresentationClockIDEvent) Unmarshal(r *wire.Reader) error {
	clkID, err := r.Uint32()
	if err != nil {
		return err
	}
	e.ClkID = clkID
	return nil
}

func (e *PresentationClockIDEvent) Since() uint32 { return 1 }

type PresentationClockIDFunc func(ev PresentationClockIDEvent)

type Presentation struct {
	proxy *wayland.Proxy
}

func NewPresentation(p *wayland.Proxy) *Presentation {
	p.SetEventFDCounts(presentationEventFDCounts)
	return &Presentation{proxy: p}
}

func (o *Presentation) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *Presentation) OnClockID(fn PresentationClockIDFunc) {
	o.proxy.RegisterEvent(PresentationEventClockID, func(r *wire.Reader) {
		var ev PresentationClockIDEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("ClockID", err)
			return
		}

		fn(ev)
	})
}

func (o *Presentation) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(PresentationRequestDestroy, &PresentationDestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

func (o *Presentation) Feedback(surface wire.ObjectID) (*PresentationFeedback, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewPresentationFeedback(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), PresentationRequestFeedback, &PresentationFeedbackRequest{
		Surface:  surface,
		Callback: wire.NewID(p.ID()),
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// BindPresentation binds the wp_presentation global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionPresentation] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindPresentation(reg, name, min(g.Version,
// VersionPresentation)), to bind at the highest mutually supported version.
func BindPresentation(b wayland.Binder, name uint32, version uint32) (*Presentation, error) {
	if version < 1 || version > VersionPresentation {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfacePresentation, version)
	if err != nil {
		return nil, err
	}
	x := NewPresentation(p)
	x.proxy.SetVersion(version)
	return x, nil
}
