// Code generated by wayland-scanner. DO NOT EDIT.

package extdatacontrol

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceDataControlDeviceV1 = "ext_data_control_device_v1"
const VersionDataControlDeviceV1 = 1

const (
	DataControlDeviceV1RequestSetSelection        uint16 = 0
	DataControlDeviceV1RequestDestroy             uint16 = 1
	DataControlDeviceV1RequestSetPrimarySelection uint16 = 2
)

const (
	DataControlDeviceV1EventDataOffer        uint16 = 0
	DataControlDeviceV1EventSelection        uint16 = 1
	DataControlDeviceV1EventFinished         uint16 = 2
	DataControlDeviceV1EventPrimarySelection uint16 = 3
)

type DataControlDeviceV1Error uint32

const (
	DataControlDeviceV1ErrorUsedSource DataControlDeviceV1Error = 1
)

type DataControlDeviceV1SetSelectionRequest struct {
	Source wire.ObjectID
}

func (r *DataControlDeviceV1SetSelectionRequest) Opcode() uint16 {
	return DataControlDeviceV1RequestSetSelection
}

func (r *DataControlDeviceV1SetSelectionRequest) Marshal(w *wire.Writer) error {
	if err := w.Object(r.Source); err != nil {
		return err
	}
	return nil
}

func (r *DataControlDeviceV1SetSelectionRequest) Since() int { return 1 }

type DataControlDeviceV1DestroyRequest struct {
}

func (r *DataControlDeviceV1DestroyRequest) Opcode() uint16 { return DataControlDeviceV1RequestDestroy }

func (r *DataControlDeviceV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *DataControlDeviceV1DestroyRequest) Since() int { return 1 }

type DataControlDeviceV1SetPrimarySelectionRequest struct {
	Source wire.ObjectID
}

func (r *DataControlDeviceV1SetPrimarySelectionRequest) Opcode() uint16 {
	return DataControlDeviceV1RequestSetPrimarySelection
}

func (r *DataControlDeviceV1SetPrimarySelectionRequest) Marshal(w *wire.Writer) error {
	if err := w.Object(r.Source); err != nil {
		return err
	}
	return nil
}

func (r *DataControlDeviceV1SetPrimarySelectionRequest) Since() int { return 1 }

type DataControlDeviceV1DataOfferEvent struct {
	ID wire.NewID
}

func (e *DataControlDeviceV1DataOfferEvent) Opcode() uint16 { return DataControlDeviceV1EventDataOffer }

func (e *DataControlDeviceV1DataOfferEvent) Unmarshal(r *wire.Reader) error {
	iD, err := r.NewID()
	if err != nil {
		return err
	}
	e.ID = iD
	return nil
}

func (e *DataControlDeviceV1DataOfferEvent) Since() int { return 1 }

type DataControlDeviceV1SelectionEvent struct {
	ID wire.ObjectID
}

func (e *DataControlDeviceV1SelectionEvent) Opcode() uint16 { return DataControlDeviceV1EventSelection }

func (e *DataControlDeviceV1SelectionEvent) Unmarshal(r *wire.Reader) error {
	iD, err := r.Object()
	if err != nil {
		return err
	}
	e.ID = iD
	return nil
}

func (e *DataControlDeviceV1SelectionEvent) Since() int { return 1 }

type DataControlDeviceV1FinishedEvent struct {
}

func (e *DataControlDeviceV1FinishedEvent) Opcode() uint16 { return DataControlDeviceV1EventFinished }

func (e *DataControlDeviceV1FinishedEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *DataControlDeviceV1FinishedEvent) Since() int { return 1 }

type DataControlDeviceV1PrimarySelectionEvent struct {
	ID wire.ObjectID
}

func (e *DataControlDeviceV1PrimarySelectionEvent) Opcode() uint16 {
	return DataControlDeviceV1EventPrimarySelection
}

func (e *DataControlDeviceV1PrimarySelectionEvent) Unmarshal(r *wire.Reader) error {
	iD, err := r.Object()
	if err != nil {
		return err
	}
	e.ID = iD
	return nil
}

func (e *DataControlDeviceV1PrimarySelectionEvent) Since() int { return 1 }

type DataControlDeviceV1DataOfferFunc func(ev DataControlDeviceV1DataOfferEvent)

type DataControlDeviceV1SelectionFunc func(ev DataControlDeviceV1SelectionEvent)

type DataControlDeviceV1FinishedFunc func(ev DataControlDeviceV1FinishedEvent)

type DataControlDeviceV1PrimarySelectionFunc func(ev DataControlDeviceV1PrimarySelectionEvent)

type DataControlDeviceV1 struct {
	proxy *wayland.Proxy
}

func NewDataControlDeviceV1(p *wayland.Proxy) *DataControlDeviceV1 {
	return &DataControlDeviceV1{proxy: p}
}

func (o *DataControlDeviceV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *DataControlDeviceV1) OnDataOffer(fn DataControlDeviceV1DataOfferFunc) {
	o.proxy.RegisterEvent(DataControlDeviceV1EventDataOffer, func(r *wire.Reader) {
		var ev DataControlDeviceV1DataOfferEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "DataOffer", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *DataControlDeviceV1) OnSelection(fn DataControlDeviceV1SelectionFunc) {
	o.proxy.RegisterEvent(DataControlDeviceV1EventSelection, func(r *wire.Reader) {
		var ev DataControlDeviceV1SelectionEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "Selection", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *DataControlDeviceV1) OnFinished(fn DataControlDeviceV1FinishedFunc) {
	o.proxy.RegisterEvent(DataControlDeviceV1EventFinished, func(r *wire.Reader) {
		var ev DataControlDeviceV1FinishedEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "Finished", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *DataControlDeviceV1) OnPrimarySelection(fn DataControlDeviceV1PrimarySelectionFunc) {
	o.proxy.RegisterEvent(DataControlDeviceV1EventPrimarySelection, func(r *wire.Reader) {
		var ev DataControlDeviceV1PrimarySelectionEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "PrimarySelection", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *DataControlDeviceV1) SetSelection(source wire.ObjectID) error {
	return o.proxy.SendRequest(DataControlDeviceV1RequestSetSelection, &DataControlDeviceV1SetSelectionRequest{
		Source: source,
	})
}

func (o *DataControlDeviceV1) Destroy() error {
	return o.proxy.SendRequest(DataControlDeviceV1RequestDestroy, &DataControlDeviceV1DestroyRequest{})
}

func (o *DataControlDeviceV1) SetPrimarySelection(source wire.ObjectID) error {
	return o.proxy.SendRequest(DataControlDeviceV1RequestSetPrimarySelection, &DataControlDeviceV1SetPrimarySelectionRequest{
		Source: source,
	})
}

func BindDataControlDeviceV1(b wayland.Binder, name uint32, version uint32) (*DataControlDeviceV1, error) {
	if version < 1 || version > VersionDataControlDeviceV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceDataControlDeviceV1, version)
	if err != nil {
		return nil, err
	}
	x := NewDataControlDeviceV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
