// Code generated by wayland-scanner. DO NOT EDIT.

package extdatacontrol

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceDataControlOfferV1 = "ext_data_control_offer_v1"
const VersionDataControlOfferV1 = 1

const (
	DataControlOfferV1RequestReceive uint16 = 0
	DataControlOfferV1RequestDestroy uint16 = 1
)

const (
	DataControlOfferV1EventOffer uint16 = 0
)

// datacontrolofferv1EventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var datacontrolofferv1EventFDCounts = map[uint16]int{
	0: 0,
}

func init() {
	wayland.RegisterInterfaceFDCounts(InterfaceDataControlOfferV1, datacontrolofferv1EventFDCounts)
}

// DataControlOfferV1ReceiveRequest request that the data is transferred.
//
// To transfer the offered data, the client issues this request and
// indicates the MIME type it wants to receive. The transfer happens
// through the passed file descriptor (typically created with the pipe
// system call). The source client writes the data in the MIME type
// representation requested and then closes the file descriptor.
//
// The receiving client reads from the read end of the pipe until EOF and
// then closes its end, at which point the transfer is complete.
//
// This request may happen multiple times for different MIME types.
type DataControlOfferV1ReceiveRequest struct {
	// MimeType mIME type desired by receiver.
	MimeType string
	// Fd file descriptor for data transfer.
	Fd int
}

func (r *DataControlOfferV1ReceiveRequest) Opcode() uint16 { return DataControlOfferV1RequestReceive }

func (r *DataControlOfferV1ReceiveRequest) Marshal(w *wire.Writer) error {
	if err := w.String(r.MimeType); err != nil {
		return err
	}
	if err := w.Fd(r.Fd); err != nil {
		return err
	}
	return nil
}

func (r *DataControlOfferV1ReceiveRequest) Since() uint32 { return 1 }

// DataControlOfferV1DestroyRequest destroy this offer.
//
// Destroys the data offer object.
type DataControlOfferV1DestroyRequest struct{}

func (r *DataControlOfferV1DestroyRequest) Opcode() uint16 { return DataControlOfferV1RequestDestroy }

func (r *DataControlOfferV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *DataControlOfferV1DestroyRequest) Since() uint32 { return 1 }

// DataControlOfferV1OfferEvent advertise offered MIME type.
//
// Sent immediately after creating the ext_data_control_offer object.
// One event per offered MIME type.
type DataControlOfferV1OfferEvent struct {
	// MimeType offered MIME type.
	MimeType string
}

func (e *DataControlOfferV1OfferEvent) Opcode() uint16 { return DataControlOfferV1EventOffer }

func (e *DataControlOfferV1OfferEvent) Unmarshal(r *wire.Reader) error {
	mimeType, err := r.String()
	if err != nil {
		return err
	}
	e.MimeType = mimeType
	return nil
}

func (e *DataControlOfferV1OfferEvent) Since() uint32 { return 1 }

// DataControlOfferV1OfferFunc is a callback for Offer events.
type DataControlOfferV1OfferFunc func(ev DataControlOfferV1OfferEvent)

// DataControlOfferV1 offer to transfer data.
//
// A ext_data_control_offer represents a piece of data offered for transfer
// by another client (the source client). The offer describes the different
// MIME types that the data can be converted to and provides the mechanism
// for transferring the data directly from the source client.
type DataControlOfferV1 struct {
	proxy *wayland.Proxy
}

// NewDataControlOfferV1 wraps p in a DataControlOfferV1 proxy.
func NewDataControlOfferV1(p *wayland.Proxy) *DataControlOfferV1 {
	p.SetEventFDCounts(datacontrolofferv1EventFDCounts)
	return &DataControlOfferV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *DataControlOfferV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// OnOffer registers fn to receive Offer events.
func (o *DataControlOfferV1) OnOffer(fn DataControlOfferV1OfferFunc) {
	o.proxy.RegisterEvent(DataControlOfferV1EventOffer, func(r *wire.Reader) {
		var ev DataControlOfferV1OfferEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Offer", err)
			return
		}
		fn(ev)
	})
}

// Receive request that the data is transferred.
//
// To transfer the offered data, the client issues this request and
// indicates the MIME type it wants to receive. The transfer happens
// through the passed file descriptor (typically created with the pipe
// system call). The source client writes the data in the MIME type
// representation requested and then closes the file descriptor.
//
// The receiving client reads from the read end of the pipe until EOF and
// then closes its end, at which point the transfer is complete.
//
// This request may happen multiple times for different MIME types.
func (o *DataControlOfferV1) Receive(mimeType string, fd int) error {
	return o.proxy.SendRequest(DataControlOfferV1RequestReceive, &DataControlOfferV1ReceiveRequest{
		MimeType: mimeType,
		Fd:       fd,
	})
}

// Destroy destroy this offer.
//
// Destroys the data offer object.
func (o *DataControlOfferV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(DataControlOfferV1RequestDestroy, &DataControlOfferV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// BindDataControlOfferV1 binds the ext_data_control_offer_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionDataControlOfferV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindDataControlOfferV1(reg, name, min(g.Version,
// VersionDataControlOfferV1)), to bind at the highest mutually supported version.
func BindDataControlOfferV1(b wayland.Binder, name, version uint32) (*DataControlOfferV1, error) {
	if version < 1 || version > VersionDataControlOfferV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceDataControlOfferV1, version)
	if err != nil {
		return nil, err
	}
	x := NewDataControlOfferV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
