// Code generated by wayland-scanner. DO NOT EDIT.

package tabletunstablev2

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceTabletSeatV2 = "zwp_tablet_seat_v2"
const VersionTabletSeatV2 = 1

const (
	TabletSeatV2RequestDestroy uint16 = 0
)

const (
	TabletSeatV2EventTabletAdded uint16 = 0
	TabletSeatV2EventToolAdded   uint16 = 1
	TabletSeatV2EventPadAdded    uint16 = 2
)

type TabletSeatV2DestroyRequest struct {
}

func (r *TabletSeatV2DestroyRequest) Opcode() uint16 { return TabletSeatV2RequestDestroy }

func (r *TabletSeatV2DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *TabletSeatV2DestroyRequest) Since() uint32 { return 1 }

type TabletSeatV2TabletAddedEvent struct {
	ID *TabletV2
}

func (e *TabletSeatV2TabletAddedEvent) Opcode() uint16 { return TabletSeatV2EventTabletAdded }

func (e *TabletSeatV2TabletAddedEvent) Since() uint32 { return 1 }

type TabletSeatV2ToolAddedEvent struct {
	ID *TabletToolV2
}

func (e *TabletSeatV2ToolAddedEvent) Opcode() uint16 { return TabletSeatV2EventToolAdded }

func (e *TabletSeatV2ToolAddedEvent) Since() uint32 { return 1 }

type TabletSeatV2PadAddedEvent struct {
	ID *TabletPadV2
}

func (e *TabletSeatV2PadAddedEvent) Opcode() uint16 { return TabletSeatV2EventPadAdded }

func (e *TabletSeatV2PadAddedEvent) Since() uint32 { return 1 }

type TabletSeatV2TabletAddedFunc func(ev TabletSeatV2TabletAddedEvent)

type TabletSeatV2ToolAddedFunc func(ev TabletSeatV2ToolAddedEvent)

type TabletSeatV2PadAddedFunc func(ev TabletSeatV2PadAddedEvent)

type TabletSeatV2 struct {
	proxy *wayland.Proxy
}

func NewTabletSeatV2(p *wayland.Proxy) *TabletSeatV2 {
	return &TabletSeatV2{proxy: p}
}

func (o *TabletSeatV2) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *TabletSeatV2) OnTabletAdded(fn TabletSeatV2TabletAddedFunc) {
	o.proxy.RegisterEvent(TabletSeatV2EventTabletAdded, func(r *wire.Reader) {
		var ev TabletSeatV2TabletAddedEvent

		rawID, err := r.NewID()
		if err != nil {
			o.proxy.Conn().FailEvent("TabletAdded", err)
			return
		}
		p := wayland.NewProxyWithID(o.proxy.Conn(), uint32(rawID))
		o.proxy.Conn().RegisterProxy(p)
		ev.ID = NewTabletV2(p)
		p.SetVersion(o.proxy.Version())

		fn(ev)
	})
}

func (o *TabletSeatV2) OnToolAdded(fn TabletSeatV2ToolAddedFunc) {
	o.proxy.RegisterEvent(TabletSeatV2EventToolAdded, func(r *wire.Reader) {
		var ev TabletSeatV2ToolAddedEvent

		rawID, err := r.NewID()
		if err != nil {
			o.proxy.Conn().FailEvent("ToolAdded", err)
			return
		}
		p := wayland.NewProxyWithID(o.proxy.Conn(), uint32(rawID))
		o.proxy.Conn().RegisterProxy(p)
		ev.ID = NewTabletToolV2(p)
		p.SetVersion(o.proxy.Version())

		fn(ev)
	})
}

func (o *TabletSeatV2) OnPadAdded(fn TabletSeatV2PadAddedFunc) {
	o.proxy.RegisterEvent(TabletSeatV2EventPadAdded, func(r *wire.Reader) {
		var ev TabletSeatV2PadAddedEvent

		rawID, err := r.NewID()
		if err != nil {
			o.proxy.Conn().FailEvent("PadAdded", err)
			return
		}
		p := wayland.NewProxyWithID(o.proxy.Conn(), uint32(rawID))
		o.proxy.Conn().RegisterProxy(p)
		ev.ID = NewTabletPadV2(p)
		p.SetVersion(o.proxy.Version())

		fn(ev)
	})
}

func (o *TabletSeatV2) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(TabletSeatV2RequestDestroy, &TabletSeatV2DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

func BindTabletSeatV2(b wayland.Binder, name uint32, version uint32) (*TabletSeatV2, error) {
	if version < 1 || version > VersionTabletSeatV2 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceTabletSeatV2, version)
	if err != nil {
		return nil, err
	}
	x := NewTabletSeatV2(p)
	x.proxy.SetVersion(version)
	return x, nil
}
