// Code generated by wayland-scanner. DO NOT EDIT.

package tabletunstablev2

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceTabletPadStripV2 = "zwp_tablet_pad_strip_v2"
const VersionTabletPadStripV2 = 1

const (
	TabletPadStripV2RequestSetFeedback uint16 = 0
	TabletPadStripV2RequestDestroy     uint16 = 1
)

const (
	TabletPadStripV2EventSource   uint16 = 0
	TabletPadStripV2EventPosition uint16 = 1
	TabletPadStripV2EventStop     uint16 = 2
	TabletPadStripV2EventFrame    uint16 = 3
)

type TabletPadStripV2Source uint32

const (
	TabletPadStripV2SourceFinger TabletPadStripV2Source = 1
)

type TabletPadStripV2SetFeedbackRequest struct {
	Description string
	Serial      uint32
}

func (r *TabletPadStripV2SetFeedbackRequest) Opcode() uint16 {
	return TabletPadStripV2RequestSetFeedback
}

func (r *TabletPadStripV2SetFeedbackRequest) Marshal(w *wire.Writer) error {
	if err := w.String(r.Description); err != nil {
		return err
	}
	if err := w.Uint32(r.Serial); err != nil {
		return err
	}
	return nil
}

func (r *TabletPadStripV2SetFeedbackRequest) Since() int { return 1 }

type TabletPadStripV2DestroyRequest struct {
}

func (r *TabletPadStripV2DestroyRequest) Opcode() uint16 { return TabletPadStripV2RequestDestroy }

func (r *TabletPadStripV2DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *TabletPadStripV2DestroyRequest) Since() int { return 1 }

type TabletPadStripV2SourceEvent struct {
	Source uint32
}

func (e *TabletPadStripV2SourceEvent) Opcode() uint16 { return TabletPadStripV2EventSource }

func (e *TabletPadStripV2SourceEvent) Unmarshal(r *wire.Reader) error {
	source, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Source = source
	return nil
}

func (e *TabletPadStripV2SourceEvent) Since() int { return 1 }

type TabletPadStripV2PositionEvent struct {
	Position uint32
}

func (e *TabletPadStripV2PositionEvent) Opcode() uint16 { return TabletPadStripV2EventPosition }

func (e *TabletPadStripV2PositionEvent) Unmarshal(r *wire.Reader) error {
	position, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Position = position
	return nil
}

func (e *TabletPadStripV2PositionEvent) Since() int { return 1 }

type TabletPadStripV2StopEvent struct {
}

func (e *TabletPadStripV2StopEvent) Opcode() uint16 { return TabletPadStripV2EventStop }

func (e *TabletPadStripV2StopEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *TabletPadStripV2StopEvent) Since() int { return 1 }

type TabletPadStripV2FrameEvent struct {
	Time uint32
}

func (e *TabletPadStripV2FrameEvent) Opcode() uint16 { return TabletPadStripV2EventFrame }

func (e *TabletPadStripV2FrameEvent) Unmarshal(r *wire.Reader) error {
	time, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Time = time
	return nil
}

func (e *TabletPadStripV2FrameEvent) Since() int { return 1 }

type TabletPadStripV2SourceFunc func(ev TabletPadStripV2SourceEvent)

type TabletPadStripV2PositionFunc func(ev TabletPadStripV2PositionEvent)

type TabletPadStripV2StopFunc func(ev TabletPadStripV2StopEvent)

type TabletPadStripV2FrameFunc func(ev TabletPadStripV2FrameEvent)

type TabletPadStripV2 struct {
	proxy *wayland.Proxy
}

func NewTabletPadStripV2(p *wayland.Proxy) *TabletPadStripV2 {
	return &TabletPadStripV2{proxy: p}
}

func (o *TabletPadStripV2) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *TabletPadStripV2) OnSource(fn TabletPadStripV2SourceFunc) {
	o.proxy.RegisterEvent(TabletPadStripV2EventSource, func(r *wire.Reader) {
		var ev TabletPadStripV2SourceEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadStripV2) OnPosition(fn TabletPadStripV2PositionFunc) {
	o.proxy.RegisterEvent(TabletPadStripV2EventPosition, func(r *wire.Reader) {
		var ev TabletPadStripV2PositionEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadStripV2) OnStop(fn TabletPadStripV2StopFunc) {
	o.proxy.RegisterEvent(TabletPadStripV2EventStop, func(r *wire.Reader) {
		var ev TabletPadStripV2StopEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadStripV2) OnFrame(fn TabletPadStripV2FrameFunc) {
	o.proxy.RegisterEvent(TabletPadStripV2EventFrame, func(r *wire.Reader) {
		var ev TabletPadStripV2FrameEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadStripV2) SetFeedback(description string, serial uint32) error {
	return o.proxy.SendRequest(TabletPadStripV2RequestSetFeedback, &TabletPadStripV2SetFeedbackRequest{
		Description: description,
		Serial:      serial,
	})
}

func (o *TabletPadStripV2) Destroy() error {
	return o.proxy.SendRequest(TabletPadStripV2RequestDestroy, &TabletPadStripV2DestroyRequest{})
}

func BindTabletPadStripV2(b wayland.Binder, name uint32, version uint32) (*TabletPadStripV2, error) {
	if version < 1 || version > VersionTabletPadStripV2 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceTabletPadStripV2, version)
	if err != nil {
		return nil, err
	}
	x := NewTabletPadStripV2(p)
	x.proxy.SetVersion(version)
	return x, nil
}
