// Code generated by wayland-scanner. DO NOT EDIT.

package primaryselectionunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfacePrimarySelectionOfferV1 = "zwp_primary_selection_offer_v1"
const VersionPrimarySelectionOfferV1 = 1

const (
	PrimarySelectionOfferV1RequestReceive uint16 = 0
	PrimarySelectionOfferV1RequestDestroy uint16 = 1
)

const (
	PrimarySelectionOfferV1EventOffer uint16 = 0
)

type PrimarySelectionOfferV1ReceiveRequest struct {
	MimeType string
	Fd       int
}

func (r *PrimarySelectionOfferV1ReceiveRequest) Opcode() uint16 {
	return PrimarySelectionOfferV1RequestReceive
}

func (r *PrimarySelectionOfferV1ReceiveRequest) Marshal(w *wire.Writer) error {
	if err := w.String(r.MimeType); err != nil {
		return err
	}
	if err := w.Fd(r.Fd); err != nil {
		return err
	}
	return nil
}

func (r *PrimarySelectionOfferV1ReceiveRequest) Since() int { return 1 }

type PrimarySelectionOfferV1DestroyRequest struct {
}

func (r *PrimarySelectionOfferV1DestroyRequest) Opcode() uint16 {
	return PrimarySelectionOfferV1RequestDestroy
}

func (r *PrimarySelectionOfferV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *PrimarySelectionOfferV1DestroyRequest) Since() int { return 1 }

type PrimarySelectionOfferV1OfferEvent struct {
	MimeType string
}

func (e *PrimarySelectionOfferV1OfferEvent) Opcode() uint16 { return PrimarySelectionOfferV1EventOffer }

func (e *PrimarySelectionOfferV1OfferEvent) Unmarshal(r *wire.Reader) error {
	mimeType, err := r.String()
	if err != nil {
		return err
	}
	e.MimeType = mimeType
	return nil
}

func (e *PrimarySelectionOfferV1OfferEvent) Since() int { return 1 }

type PrimarySelectionOfferV1OfferFunc func(ev PrimarySelectionOfferV1OfferEvent)

type PrimarySelectionOfferV1 struct {
	proxy *wayland.Proxy
}

func NewPrimarySelectionOfferV1(p *wayland.Proxy) *PrimarySelectionOfferV1 {
	return &PrimarySelectionOfferV1{proxy: p}
}

func (o *PrimarySelectionOfferV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *PrimarySelectionOfferV1) OnOffer(fn PrimarySelectionOfferV1OfferFunc) {
	o.proxy.RegisterEvent(PrimarySelectionOfferV1EventOffer, func(r *wire.Reader) {
		var ev PrimarySelectionOfferV1OfferEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "Offer", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *PrimarySelectionOfferV1) Receive(mimeType string, fd int) error {
	return o.proxy.SendRequest(PrimarySelectionOfferV1RequestReceive, &PrimarySelectionOfferV1ReceiveRequest{
		MimeType: mimeType,
		Fd:       fd,
	})
}

func (o *PrimarySelectionOfferV1) Destroy() error {
	return o.proxy.SendRequest(PrimarySelectionOfferV1RequestDestroy, &PrimarySelectionOfferV1DestroyRequest{})
}

func BindPrimarySelectionOfferV1(b wayland.Binder, name uint32, version uint32) (*PrimarySelectionOfferV1, error) {
	if version < 1 || version > VersionPrimarySelectionOfferV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfacePrimarySelectionOfferV1, version)
	if err != nil {
		return nil, err
	}
	x := NewPrimarySelectionOfferV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
