// Code generated by wayland-scanner. DO NOT EDIT.

package primaryselectionunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfacePrimarySelectionOfferV1 = "zwp_primary_selection_offer_v1"
const VersionPrimarySelectionOfferV1 = 1

const (
	PrimarySelectionOfferV1RequestReceive uint16 = 0
	PrimarySelectionOfferV1RequestDestroy uint16 = 1
)

const (
	PrimarySelectionOfferV1EventOffer uint16 = 0
)

// primaryselectionofferv1EventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var primaryselectionofferv1EventFDCounts = map[uint16]int{
	0: 0,
}

func init() {
	wayland.RegisterInterfaceFDCounts(InterfacePrimarySelectionOfferV1, primaryselectionofferv1EventFDCounts)
}

// PrimarySelectionOfferV1ReceiveRequest request that the data is transferred.
//
// To transfer the contents of the primary selection clipboard, the client
// issues this request and indicates the mime type that it wants to
// receive. The transfer happens through the passed file descriptor
// (typically created with the pipe system call). The source client writes
// the data in the mime type representation requested and then closes the
// file descriptor.
//
// The receiving client reads from the read end of the pipe until EOF and
// closes its end, at which point the transfer is complete.
type PrimarySelectionOfferV1ReceiveRequest struct {
	MimeType string
	Fd       int
}

func (r *PrimarySelectionOfferV1ReceiveRequest) Opcode() uint16 {
	return PrimarySelectionOfferV1RequestReceive
}

func (r *PrimarySelectionOfferV1ReceiveRequest) Marshal(w *wire.Writer) error {
	if err := w.String(r.MimeType); err != nil {
		return err
	}
	if err := w.Fd(r.Fd); err != nil {
		return err
	}
	return nil
}

func (r *PrimarySelectionOfferV1ReceiveRequest) Since() uint32 { return 1 }

// PrimarySelectionOfferV1DestroyRequest destroy the primary selection offer.
//
// Destroy the primary selection offer.
type PrimarySelectionOfferV1DestroyRequest struct {
}

func (r *PrimarySelectionOfferV1DestroyRequest) Opcode() uint16 {
	return PrimarySelectionOfferV1RequestDestroy
}

func (r *PrimarySelectionOfferV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *PrimarySelectionOfferV1DestroyRequest) Since() uint32 { return 1 }

// PrimarySelectionOfferV1OfferEvent advertise offered mime type.
//
// Sent immediately after creating announcing the
// wp_primary_selection_offer through
// wp_primary_selection_device.data_offer. One event is sent per offered
// mime type.
type PrimarySelectionOfferV1OfferEvent struct {
	MimeType string
}

func (e *PrimarySelectionOfferV1OfferEvent) Opcode() uint16 { return PrimarySelectionOfferV1EventOffer }

func (e *PrimarySelectionOfferV1OfferEvent) Unmarshal(r *wire.Reader) error {
	mimeType, err := r.String()
	if err != nil {
		return err
	}
	e.MimeType = mimeType
	return nil
}

func (e *PrimarySelectionOfferV1OfferEvent) Since() uint32 { return 1 }

// PrimarySelectionOfferV1OfferFunc is a callback for Offer events.
type PrimarySelectionOfferV1OfferFunc func(ev PrimarySelectionOfferV1OfferEvent)

// PrimarySelectionOfferV1 offer to transfer primary selection contents.
//
// A wp_primary_selection_offer represents an offer to transfer the contents
// of the primary selection clipboard to the client. Similar to
// wl_data_offer, the offer also describes the mime types that the data can
// be converted to and provides the mechanisms for transferring the data
// directly to the client.
type PrimarySelectionOfferV1 struct {
	proxy *wayland.Proxy
}

// NewPrimarySelectionOfferV1 wraps p in a PrimarySelectionOfferV1 proxy.
func NewPrimarySelectionOfferV1(p *wayland.Proxy) *PrimarySelectionOfferV1 {
	p.SetEventFDCounts(primaryselectionofferv1EventFDCounts)
	return &PrimarySelectionOfferV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *PrimarySelectionOfferV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// OnOffer registers fn to receive Offer events.
func (o *PrimarySelectionOfferV1) OnOffer(fn PrimarySelectionOfferV1OfferFunc) {
	o.proxy.RegisterEvent(PrimarySelectionOfferV1EventOffer, func(r *wire.Reader) {
		var ev PrimarySelectionOfferV1OfferEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Offer", err)
			return
		}

		fn(ev)
	})
}

// Receive request that the data is transferred.
//
// To transfer the contents of the primary selection clipboard, the client
// issues this request and indicates the mime type that it wants to
// receive. The transfer happens through the passed file descriptor
// (typically created with the pipe system call). The source client writes
// the data in the mime type representation requested and then closes the
// file descriptor.
//
// The receiving client reads from the read end of the pipe until EOF and
// closes its end, at which point the transfer is complete.
func (o *PrimarySelectionOfferV1) Receive(mimeType string, fd int) error {
	return o.proxy.SendRequest(PrimarySelectionOfferV1RequestReceive, &PrimarySelectionOfferV1ReceiveRequest{
		MimeType: mimeType,
		Fd:       fd,
	})
}

// Destroy destroy the primary selection offer.
//
// Destroy the primary selection offer.
func (o *PrimarySelectionOfferV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(PrimarySelectionOfferV1RequestDestroy, &PrimarySelectionOfferV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// BindPrimarySelectionOfferV1 binds the zwp_primary_selection_offer_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionPrimarySelectionOfferV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindPrimarySelectionOfferV1(reg, name, min(g.Version,
// VersionPrimarySelectionOfferV1)), to bind at the highest mutually supported version.
func BindPrimarySelectionOfferV1(b wayland.Binder, name uint32, version uint32) (*PrimarySelectionOfferV1, error) {
	if version < 1 || version > VersionPrimarySelectionOfferV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfacePrimarySelectionOfferV1, version)
	if err != nil {
		return nil, err
	}
	x := NewPrimarySelectionOfferV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
