// Code generated by wayland-scanner. DO NOT EDIT.

package xdgsessionmanagement

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceSessionV1 = "xdg_session_v1"
const VersionSessionV1 = 1

const (
	SessionV1RequestDestroy         uint16 = 0
	SessionV1RequestRemove          uint16 = 1
	SessionV1RequestAddToplevel     uint16 = 2
	SessionV1RequestRestoreToplevel uint16 = 3
	SessionV1RequestRemoveToplevel  uint16 = 4
)

const (
	SessionV1EventCreated  uint16 = 0
	SessionV1EventRestored uint16 = 1
	SessionV1EventReplaced uint16 = 2
)

type SessionV1Error uint32

const (
	SessionV1ErrorNameInUse     SessionV1Error = 1
	SessionV1ErrorAlreadyMapped SessionV1Error = 2
	SessionV1ErrorInvalidName   SessionV1Error = 3
	SessionV1ErrorAlreadyAdded  SessionV1Error = 4
)

type SessionV1DestroyRequest struct {
}

func (r *SessionV1DestroyRequest) Opcode() uint16 { return SessionV1RequestDestroy }

func (r *SessionV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SessionV1DestroyRequest) Since() int { return 1 }

type SessionV1RemoveRequest struct {
}

func (r *SessionV1RemoveRequest) Opcode() uint16 { return SessionV1RequestRemove }

func (r *SessionV1RemoveRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SessionV1RemoveRequest) Since() int { return 1 }

type SessionV1AddToplevelRequest struct {
	ID       wire.NewID
	Toplevel wire.ObjectID
	Name     string
}

func (r *SessionV1AddToplevelRequest) Opcode() uint16 { return SessionV1RequestAddToplevel }

func (r *SessionV1AddToplevelRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Toplevel); err != nil {
		return err
	}
	if err := w.String(r.Name); err != nil {
		return err
	}
	return nil
}

func (r *SessionV1AddToplevelRequest) Since() int { return 1 }

type SessionV1RestoreToplevelRequest struct {
	ID       wire.NewID
	Toplevel wire.ObjectID
	Name     string
}

func (r *SessionV1RestoreToplevelRequest) Opcode() uint16 { return SessionV1RequestRestoreToplevel }

func (r *SessionV1RestoreToplevelRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Toplevel); err != nil {
		return err
	}
	if err := w.String(r.Name); err != nil {
		return err
	}
	return nil
}

func (r *SessionV1RestoreToplevelRequest) Since() int { return 1 }

type SessionV1RemoveToplevelRequest struct {
	Name string
}

func (r *SessionV1RemoveToplevelRequest) Opcode() uint16 { return SessionV1RequestRemoveToplevel }

func (r *SessionV1RemoveToplevelRequest) Marshal(w *wire.Writer) error {
	if err := w.String(r.Name); err != nil {
		return err
	}
	return nil
}

func (r *SessionV1RemoveToplevelRequest) Since() int { return 1 }

type SessionV1CreatedEvent struct {
	SessionID string
}

func (e *SessionV1CreatedEvent) Opcode() uint16 { return SessionV1EventCreated }

func (e *SessionV1CreatedEvent) Unmarshal(r *wire.Reader) error {
	sessionID, err := r.String()
	if err != nil {
		return err
	}
	e.SessionID = sessionID
	return nil
}

func (e *SessionV1CreatedEvent) Since() int { return 1 }

type SessionV1RestoredEvent struct {
}

func (e *SessionV1RestoredEvent) Opcode() uint16 { return SessionV1EventRestored }

func (e *SessionV1RestoredEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *SessionV1RestoredEvent) Since() int { return 1 }

type SessionV1ReplacedEvent struct {
}

func (e *SessionV1ReplacedEvent) Opcode() uint16 { return SessionV1EventReplaced }

func (e *SessionV1ReplacedEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *SessionV1ReplacedEvent) Since() int { return 1 }

type SessionV1CreatedFunc func(ev SessionV1CreatedEvent)

type SessionV1RestoredFunc func(ev SessionV1RestoredEvent)

type SessionV1ReplacedFunc func(ev SessionV1ReplacedEvent)

type SessionV1 struct {
	proxy *wayland.Proxy
}

func NewSessionV1(p *wayland.Proxy) *SessionV1 {
	return &SessionV1{proxy: p}
}

func (o *SessionV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *SessionV1) OnCreated(fn SessionV1CreatedFunc) {
	o.proxy.RegisterEvent(SessionV1EventCreated, func(r *wire.Reader) {
		var ev SessionV1CreatedEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "Created", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *SessionV1) OnRestored(fn SessionV1RestoredFunc) {
	o.proxy.RegisterEvent(SessionV1EventRestored, func(r *wire.Reader) {
		var ev SessionV1RestoredEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "Restored", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *SessionV1) OnReplaced(fn SessionV1ReplacedFunc) {
	o.proxy.RegisterEvent(SessionV1EventReplaced, func(r *wire.Reader) {
		var ev SessionV1ReplacedEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "Replaced", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *SessionV1) Destroy() error {
	return o.proxy.SendRequest(SessionV1RequestDestroy, &SessionV1DestroyRequest{})
}

func (o *SessionV1) Remove() error {
	return o.proxy.SendRequest(SessionV1RequestRemove, &SessionV1RemoveRequest{})
}

func (o *SessionV1) AddToplevel(toplevel wire.ObjectID, name string) (*ToplevelSessionV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewToplevelSessionV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), SessionV1RequestAddToplevel, &SessionV1AddToplevelRequest{
		ID:       wire.NewID(p.ID()),
		Toplevel: toplevel,
		Name:     name,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func (o *SessionV1) RestoreToplevel(toplevel wire.ObjectID, name string) (*ToplevelSessionV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewToplevelSessionV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), SessionV1RequestRestoreToplevel, &SessionV1RestoreToplevelRequest{
		ID:       wire.NewID(p.ID()),
		Toplevel: toplevel,
		Name:     name,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func (o *SessionV1) RemoveToplevel(name string) error {
	return o.proxy.SendRequest(SessionV1RequestRemoveToplevel, &SessionV1RemoveToplevelRequest{
		Name: name,
	})
}

func BindSessionV1(b wayland.Binder, name uint32, version uint32) (*SessionV1, error) {
	if version < 1 || version > VersionSessionV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceSessionV1, version)
	if err != nil {
		return nil, err
	}
	x := NewSessionV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
