// Code generated by wayland-scanner. DO NOT EDIT.

package xdgsessionmanagement

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceSessionManagerV1 = "xdg_session_manager_v1"
const VersionSessionManagerV1 = 1

const (
	SessionManagerV1RequestDestroy    uint16 = 0
	SessionManagerV1RequestGetSession uint16 = 1
)

type SessionManagerV1Error uint32

const (
	// SessionManagerV1ErrorInUse a requested session is already in use.
	SessionManagerV1ErrorInUse SessionManagerV1Error = 1

	// SessionManagerV1ErrorInvalidSessionID invalid session identifier.
	SessionManagerV1ErrorInvalidSessionID SessionManagerV1Error = 2

	// SessionManagerV1ErrorInvalidReason invalid reason.
	SessionManagerV1ErrorInvalidReason SessionManagerV1Error = 3
)

// SessionManagerV1Reason reason for getting a session.
//
// The reason may determine in what way a session restores the window
// management state of associated toplevels.
//
// For example newly launched applications might be launched on the active
// workspace with restored size and position, while a recovered
// application might restore additional state such as active workspace and
// stacking order.
type SessionManagerV1Reason uint32

const (
	// SessionManagerV1ReasonLaunch.
	//
	// A new app instance is launched, for example from an app launcher.
	SessionManagerV1ReasonLaunch SessionManagerV1Reason = 1

	// SessionManagerV1ReasonRecover.
	//
	// An app instance is recovering from for example a compositor or app crash.
	SessionManagerV1ReasonRecover SessionManagerV1Reason = 2

	// SessionManagerV1ReasonSessionRestore.
	//
	// An app instance is restored, for example part of a restored session, or
	// restored from having been temporarily terminated due to resource
	// constraints.
	SessionManagerV1ReasonSessionRestore SessionManagerV1Reason = 3
)

// SessionManagerV1DestroyRequest destroy this object.
//
// Destroy the manager object. The existing session objects will be
// unaffected.
type SessionManagerV1DestroyRequest struct {
}

func (r *SessionManagerV1DestroyRequest) Opcode() uint16 { return SessionManagerV1RequestDestroy }

func (r *SessionManagerV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SessionManagerV1DestroyRequest) Since() uint32 { return 1 }

// SessionManagerV1GetSessionRequest create or restore a session.
//
// Create a session object corresponding to either an existing session
// identified by the given session identifier string or a new session.
// While the session object exists, the session is considered to be "in
// use".
//
// If an identifier string represents a session that is currently actively
// in use by the the same client, an 'in_use' error is raised. If some
// other client is currently using the same session, the new session will
// replace managing the associated state.
//
// If the reason is not a valid enum entry, the 'invalid_reason' protocol
// error is raised.
//
// NULL is passed to initiate a new session. If a session_id is passed
// which does not represent a valid session, the compositor treats it as if
// NULL had been passed.
//
// The session id string must be UTF-8 encoded. It is also limited by the
// maximum length of wayland messages (around 4KB). The 'invalid_session_id'
// protocol error will be raised if an invalid string is provided.
//
// A client is allowed to have any number of in use sessions at the same
// time.
type SessionManagerV1GetSessionRequest struct {
	ID wire.NewID
	// Reason reason for session.
	Reason SessionManagerV1Reason
	// SessionID the session to restore.
	SessionID *string // nullable
}

func (r *SessionManagerV1GetSessionRequest) Opcode() uint16 { return SessionManagerV1RequestGetSession }

func (r *SessionManagerV1GetSessionRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Uint32(uint32(r.Reason)); err != nil {
		return err
	}
	if err := w.StringNullable(r.SessionID); err != nil {
		return err
	}
	return nil
}

func (r *SessionManagerV1GetSessionRequest) Since() uint32 { return 1 }

// SessionManagerV1 manage sessions for applications.
//
// The xdg_session_manager_v1 interface defines base requests for creating and
// managing a session for an application. Sessions persist across application
// and compositor restarts unless explicitly destroyed. A session is created
// for the purpose of maintaining an application's xdg_toplevel surfaces
// across compositor or application restarts. The compositor should remember
// as many states as possible for surfaces in a given session, but there is
// no requirement for which states must be remembered.
//
// Policies such as cache eviction are declared an implementation detail of
// the compositor. Clients should account for no longer existing sessions.
type SessionManagerV1 struct {
	proxy *wayland.Proxy
}

// NewSessionManagerV1 wraps p in a SessionManagerV1 proxy.
func NewSessionManagerV1(p *wayland.Proxy) *SessionManagerV1 {
	return &SessionManagerV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *SessionManagerV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// Destroy destroy this object.
//
// Destroy the manager object. The existing session objects will be
// unaffected.
func (o *SessionManagerV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(SessionManagerV1RequestDestroy, &SessionManagerV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// GetSession create or restore a session.
//
// Create a session object corresponding to either an existing session
// identified by the given session identifier string or a new session.
// While the session object exists, the session is considered to be "in
// use".
//
// If an identifier string represents a session that is currently actively
// in use by the the same client, an 'in_use' error is raised. If some
// other client is currently using the same session, the new session will
// replace managing the associated state.
//
// If the reason is not a valid enum entry, the 'invalid_reason' protocol
// error is raised.
//
// NULL is passed to initiate a new session. If a session_id is passed
// which does not represent a valid session, the compositor treats it as if
// NULL had been passed.
//
// The session id string must be UTF-8 encoded. It is also limited by the
// maximum length of wayland messages (around 4KB). The 'invalid_session_id'
// protocol error will be raised if an invalid string is provided.
//
// A client is allowed to have any number of in use sessions at the same
// time.
func (o *SessionManagerV1) GetSession(reason SessionManagerV1Reason, sessionID *string) (*SessionV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewSessionV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), SessionManagerV1RequestGetSession, &SessionManagerV1GetSessionRequest{
		ID:        wire.NewID(p.ID()),
		Reason:    reason,
		SessionID: sessionID,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// BindSessionManagerV1 binds the xdg_session_manager_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionSessionManagerV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindSessionManagerV1(reg, name, min(g.Version,
// VersionSessionManagerV1)), to bind at the highest mutually supported version.
func BindSessionManagerV1(b wayland.Binder, name uint32, version uint32) (*SessionManagerV1, error) {
	if version < 1 || version > VersionSessionManagerV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceSessionManagerV1, version)
	if err != nil {
		return nil, err
	}
	x := NewSessionManagerV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
