// Code generated by wayland-scanner. DO NOT EDIT.

package textinputunstablev3

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceTextInputV3 = "zwp_text_input_v3"
const VersionTextInputV3 = 2

const (
	TextInputV3RequestDestroy             uint16 = 0
	TextInputV3RequestEnable              uint16 = 1
	TextInputV3RequestDisable             uint16 = 2
	TextInputV3RequestSetSurroundingText  uint16 = 3
	TextInputV3RequestSetTextChangeCause  uint16 = 4
	TextInputV3RequestSetContentType      uint16 = 5
	TextInputV3RequestSetCursorRectangle  uint16 = 6
	TextInputV3RequestCommit              uint16 = 7
	TextInputV3RequestSetAvailableActions uint16 = 8
	TextInputV3RequestShowInputPanel      uint16 = 9
	TextInputV3RequestHideInputPanel      uint16 = 10
)

const (
	TextInputV3EventEnter                 uint16 = 0
	TextInputV3EventLeave                 uint16 = 1
	TextInputV3EventPreeditString         uint16 = 2
	TextInputV3EventCommitString          uint16 = 3
	TextInputV3EventDeleteSurroundingText uint16 = 4
	TextInputV3EventDone                  uint16 = 5
	TextInputV3EventAction                uint16 = 6
	TextInputV3EventLanguage              uint16 = 7
	TextInputV3EventPreeditHint           uint16 = 8
)

type TextInputV3ChangeCause uint32

const (
	TextInputV3ChangeCauseInputMethod TextInputV3ChangeCause = 0
	TextInputV3ChangeCauseOther       TextInputV3ChangeCause = 1
)

type TextInputV3ContentHint uint32

const (
	TextInputV3ContentHintNone                  TextInputV3ContentHint = 0
	TextInputV3ContentHintCompletion            TextInputV3ContentHint = 1
	TextInputV3ContentHintSpellcheck            TextInputV3ContentHint = 2
	TextInputV3ContentHintAutoCapitalization    TextInputV3ContentHint = 4
	TextInputV3ContentHintLowercase             TextInputV3ContentHint = 8
	TextInputV3ContentHintUppercase             TextInputV3ContentHint = 16
	TextInputV3ContentHintTitlecase             TextInputV3ContentHint = 32
	TextInputV3ContentHintHiddenText            TextInputV3ContentHint = 64
	TextInputV3ContentHintSensitiveData         TextInputV3ContentHint = 128
	TextInputV3ContentHintLatin                 TextInputV3ContentHint = 256
	TextInputV3ContentHintMultiline             TextInputV3ContentHint = 512
	TextInputV3ContentHintOnScreenInputProvided TextInputV3ContentHint = 1024
	TextInputV3ContentHintNoEmoji               TextInputV3ContentHint = 2048
	TextInputV3ContentHintPreeditShown          TextInputV3ContentHint = 4096
)

type TextInputV3ContentPurpose uint32

const (
	TextInputV3ContentPurposeNormal   TextInputV3ContentPurpose = 0
	TextInputV3ContentPurposeAlpha    TextInputV3ContentPurpose = 1
	TextInputV3ContentPurposeDigits   TextInputV3ContentPurpose = 2
	TextInputV3ContentPurposeNumber   TextInputV3ContentPurpose = 3
	TextInputV3ContentPurposePhone    TextInputV3ContentPurpose = 4
	TextInputV3ContentPurposeUrl      TextInputV3ContentPurpose = 5
	TextInputV3ContentPurposeEmail    TextInputV3ContentPurpose = 6
	TextInputV3ContentPurposeName     TextInputV3ContentPurpose = 7
	TextInputV3ContentPurposePassword TextInputV3ContentPurpose = 8
	TextInputV3ContentPurposePin      TextInputV3ContentPurpose = 9
	TextInputV3ContentPurposeDate     TextInputV3ContentPurpose = 10
	TextInputV3ContentPurposeTime     TextInputV3ContentPurpose = 11
	TextInputV3ContentPurposeDatetime TextInputV3ContentPurpose = 12
	TextInputV3ContentPurposeTerminal TextInputV3ContentPurpose = 13
)

type TextInputV3Error uint32

const (
	TextInputV3ErrorInvalidAction TextInputV3Error = 0
)

type TextInputV3Action uint32

const (
	TextInputV3ActionNone   TextInputV3Action = 0
	TextInputV3ActionSubmit TextInputV3Action = 1
)

type TextInputV3PreeditHint uint32

const (
	TextInputV3PreeditHintWhole         TextInputV3PreeditHint = 1
	TextInputV3PreeditHintSelection     TextInputV3PreeditHint = 2
	TextInputV3PreeditHintPrediction    TextInputV3PreeditHint = 3
	TextInputV3PreeditHintPrefix        TextInputV3PreeditHint = 4
	TextInputV3PreeditHintSuffix        TextInputV3PreeditHint = 5
	TextInputV3PreeditHintSpellingError TextInputV3PreeditHint = 6
	TextInputV3PreeditHintComposeError  TextInputV3PreeditHint = 7
)

type TextInputV3DestroyRequest struct {
}

func (r *TextInputV3DestroyRequest) Opcode() uint16 { return TextInputV3RequestDestroy }

func (r *TextInputV3DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *TextInputV3DestroyRequest) Since() int { return 1 }

type TextInputV3EnableRequest struct {
}

func (r *TextInputV3EnableRequest) Opcode() uint16 { return TextInputV3RequestEnable }

func (r *TextInputV3EnableRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *TextInputV3EnableRequest) Since() int { return 1 }

type TextInputV3DisableRequest struct {
}

func (r *TextInputV3DisableRequest) Opcode() uint16 { return TextInputV3RequestDisable }

func (r *TextInputV3DisableRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *TextInputV3DisableRequest) Since() int { return 1 }

type TextInputV3SetSurroundingTextRequest struct {
	Text   string
	Cursor int32
	Anchor int32
}

func (r *TextInputV3SetSurroundingTextRequest) Opcode() uint16 {
	return TextInputV3RequestSetSurroundingText
}

func (r *TextInputV3SetSurroundingTextRequest) Marshal(w *wire.Writer) error {
	if err := w.String(r.Text); err != nil {
		return err
	}
	if err := w.Int32(r.Cursor); err != nil {
		return err
	}
	if err := w.Int32(r.Anchor); err != nil {
		return err
	}
	return nil
}

func (r *TextInputV3SetSurroundingTextRequest) Since() int { return 1 }

type TextInputV3SetTextChangeCauseRequest struct {
	Cause uint32
}

func (r *TextInputV3SetTextChangeCauseRequest) Opcode() uint16 {
	return TextInputV3RequestSetTextChangeCause
}

func (r *TextInputV3SetTextChangeCauseRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Cause); err != nil {
		return err
	}
	return nil
}

func (r *TextInputV3SetTextChangeCauseRequest) Since() int { return 1 }

type TextInputV3SetContentTypeRequest struct {
	Hint    uint32
	Purpose uint32
}

func (r *TextInputV3SetContentTypeRequest) Opcode() uint16 { return TextInputV3RequestSetContentType }

func (r *TextInputV3SetContentTypeRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Hint); err != nil {
		return err
	}
	if err := w.Uint32(r.Purpose); err != nil {
		return err
	}
	return nil
}

func (r *TextInputV3SetContentTypeRequest) Since() int { return 1 }

type TextInputV3SetCursorRectangleRequest struct {
	X      int32
	Y      int32
	Width  int32
	Height int32
}

func (r *TextInputV3SetCursorRectangleRequest) Opcode() uint16 {
	return TextInputV3RequestSetCursorRectangle
}

func (r *TextInputV3SetCursorRectangleRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.X); err != nil {
		return err
	}
	if err := w.Int32(r.Y); err != nil {
		return err
	}
	if err := w.Int32(r.Width); err != nil {
		return err
	}
	if err := w.Int32(r.Height); err != nil {
		return err
	}
	return nil
}

func (r *TextInputV3SetCursorRectangleRequest) Since() int { return 1 }

type TextInputV3CommitRequest struct {
}

func (r *TextInputV3CommitRequest) Opcode() uint16 { return TextInputV3RequestCommit }

func (r *TextInputV3CommitRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *TextInputV3CommitRequest) Since() int { return 1 }

type TextInputV3SetAvailableActionsRequest struct {
	AvailableActions []byte
}

func (r *TextInputV3SetAvailableActionsRequest) Opcode() uint16 {
	return TextInputV3RequestSetAvailableActions
}

func (r *TextInputV3SetAvailableActionsRequest) Marshal(w *wire.Writer) error {
	if err := w.Array(r.AvailableActions); err != nil {
		return err
	}
	return nil
}

func (r *TextInputV3SetAvailableActionsRequest) Since() int { return 2 }

type TextInputV3ShowInputPanelRequest struct {
}

func (r *TextInputV3ShowInputPanelRequest) Opcode() uint16 { return TextInputV3RequestShowInputPanel }

func (r *TextInputV3ShowInputPanelRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *TextInputV3ShowInputPanelRequest) Since() int { return 2 }

type TextInputV3HideInputPanelRequest struct {
}

func (r *TextInputV3HideInputPanelRequest) Opcode() uint16 { return TextInputV3RequestHideInputPanel }

func (r *TextInputV3HideInputPanelRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *TextInputV3HideInputPanelRequest) Since() int { return 2 }

type TextInputV3EnterEvent struct {
	Surface wire.ObjectID
}

func (e *TextInputV3EnterEvent) Opcode() uint16 { return TextInputV3EventEnter }

func (e *TextInputV3EnterEvent) Unmarshal(r *wire.Reader) error {
	surface, err := r.Object()
	if err != nil {
		return err
	}
	e.Surface = surface
	return nil
}

func (e *TextInputV3EnterEvent) Since() int { return 1 }

type TextInputV3LeaveEvent struct {
	Surface wire.ObjectID
}

func (e *TextInputV3LeaveEvent) Opcode() uint16 { return TextInputV3EventLeave }

func (e *TextInputV3LeaveEvent) Unmarshal(r *wire.Reader) error {
	surface, err := r.Object()
	if err != nil {
		return err
	}
	e.Surface = surface
	return nil
}

func (e *TextInputV3LeaveEvent) Since() int { return 1 }

type TextInputV3PreeditStringEvent struct {
	Text        string
	CursorBegin int32
	CursorEnd   int32
}

func (e *TextInputV3PreeditStringEvent) Opcode() uint16 { return TextInputV3EventPreeditString }

func (e *TextInputV3PreeditStringEvent) Unmarshal(r *wire.Reader) error {
	text, err := r.String()
	if err != nil {
		return err
	}
	e.Text = text
	cursorBegin, err := r.Int32()
	if err != nil {
		return err
	}
	e.CursorBegin = cursorBegin
	cursorEnd, err := r.Int32()
	if err != nil {
		return err
	}
	e.CursorEnd = cursorEnd
	return nil
}

func (e *TextInputV3PreeditStringEvent) Since() int { return 1 }

type TextInputV3CommitStringEvent struct {
	Text string
}

func (e *TextInputV3CommitStringEvent) Opcode() uint16 { return TextInputV3EventCommitString }

func (e *TextInputV3CommitStringEvent) Unmarshal(r *wire.Reader) error {
	text, err := r.String()
	if err != nil {
		return err
	}
	e.Text = text
	return nil
}

func (e *TextInputV3CommitStringEvent) Since() int { return 1 }

type TextInputV3DeleteSurroundingTextEvent struct {
	BeforeLength uint32
	AfterLength  uint32
}

func (e *TextInputV3DeleteSurroundingTextEvent) Opcode() uint16 {
	return TextInputV3EventDeleteSurroundingText
}

func (e *TextInputV3DeleteSurroundingTextEvent) Unmarshal(r *wire.Reader) error {
	beforeLength, err := r.Uint32()
	if err != nil {
		return err
	}
	e.BeforeLength = beforeLength
	afterLength, err := r.Uint32()
	if err != nil {
		return err
	}
	e.AfterLength = afterLength
	return nil
}

func (e *TextInputV3DeleteSurroundingTextEvent) Since() int { return 1 }

type TextInputV3DoneEvent struct {
	Serial uint32
}

func (e *TextInputV3DoneEvent) Opcode() uint16 { return TextInputV3EventDone }

func (e *TextInputV3DoneEvent) Unmarshal(r *wire.Reader) error {
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	return nil
}

func (e *TextInputV3DoneEvent) Since() int { return 1 }

type TextInputV3ActionEvent struct {
	Action uint32
	Serial uint32
}

func (e *TextInputV3ActionEvent) Opcode() uint16 { return TextInputV3EventAction }

func (e *TextInputV3ActionEvent) Unmarshal(r *wire.Reader) error {
	action, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Action = action
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	return nil
}

func (e *TextInputV3ActionEvent) Since() int { return 2 }

type TextInputV3LanguageEvent struct {
	Language string
}

func (e *TextInputV3LanguageEvent) Opcode() uint16 { return TextInputV3EventLanguage }

func (e *TextInputV3LanguageEvent) Unmarshal(r *wire.Reader) error {
	language, err := r.String()
	if err != nil {
		return err
	}
	e.Language = language
	return nil
}

func (e *TextInputV3LanguageEvent) Since() int { return 2 }

type TextInputV3PreeditHintEvent struct {
	Start uint32
	End   uint32
	Hint  uint32
}

func (e *TextInputV3PreeditHintEvent) Opcode() uint16 { return TextInputV3EventPreeditHint }

func (e *TextInputV3PreeditHintEvent) Unmarshal(r *wire.Reader) error {
	start, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Start = start
	end, err := r.Uint32()
	if err != nil {
		return err
	}
	e.End = end
	hint, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Hint = hint
	return nil
}

func (e *TextInputV3PreeditHintEvent) Since() int { return 2 }

type TextInputV3EnterFunc func(ev TextInputV3EnterEvent)

type TextInputV3LeaveFunc func(ev TextInputV3LeaveEvent)

type TextInputV3PreeditStringFunc func(ev TextInputV3PreeditStringEvent)

type TextInputV3CommitStringFunc func(ev TextInputV3CommitStringEvent)

type TextInputV3DeleteSurroundingTextFunc func(ev TextInputV3DeleteSurroundingTextEvent)

type TextInputV3DoneFunc func(ev TextInputV3DoneEvent)

type TextInputV3ActionFunc func(ev TextInputV3ActionEvent)

type TextInputV3LanguageFunc func(ev TextInputV3LanguageEvent)

type TextInputV3PreeditHintFunc func(ev TextInputV3PreeditHintEvent)

type TextInputV3 struct {
	proxy *wayland.Proxy
}

func NewTextInputV3(p *wayland.Proxy) *TextInputV3 {
	return &TextInputV3{proxy: p}
}

func (o *TextInputV3) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *TextInputV3) OnEnter(fn TextInputV3EnterFunc) {
	o.proxy.RegisterEvent(TextInputV3EventEnter, func(r *wire.Reader) {
		var ev TextInputV3EnterEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TextInputV3) OnLeave(fn TextInputV3LeaveFunc) {
	o.proxy.RegisterEvent(TextInputV3EventLeave, func(r *wire.Reader) {
		var ev TextInputV3LeaveEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TextInputV3) OnPreeditString(fn TextInputV3PreeditStringFunc) {
	o.proxy.RegisterEvent(TextInputV3EventPreeditString, func(r *wire.Reader) {
		var ev TextInputV3PreeditStringEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TextInputV3) OnCommitString(fn TextInputV3CommitStringFunc) {
	o.proxy.RegisterEvent(TextInputV3EventCommitString, func(r *wire.Reader) {
		var ev TextInputV3CommitStringEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TextInputV3) OnDeleteSurroundingText(fn TextInputV3DeleteSurroundingTextFunc) {
	o.proxy.RegisterEvent(TextInputV3EventDeleteSurroundingText, func(r *wire.Reader) {
		var ev TextInputV3DeleteSurroundingTextEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TextInputV3) OnDone(fn TextInputV3DoneFunc) {
	o.proxy.RegisterEvent(TextInputV3EventDone, func(r *wire.Reader) {
		var ev TextInputV3DoneEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TextInputV3) OnAction(fn TextInputV3ActionFunc) {
	o.proxy.RegisterEvent(TextInputV3EventAction, func(r *wire.Reader) {
		var ev TextInputV3ActionEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TextInputV3) OnLanguage(fn TextInputV3LanguageFunc) {
	o.proxy.RegisterEvent(TextInputV3EventLanguage, func(r *wire.Reader) {
		var ev TextInputV3LanguageEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TextInputV3) OnPreeditHint(fn TextInputV3PreeditHintFunc) {
	o.proxy.RegisterEvent(TextInputV3EventPreeditHint, func(r *wire.Reader) {
		var ev TextInputV3PreeditHintEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TextInputV3) Destroy() error {
	return o.proxy.SendRequest(TextInputV3RequestDestroy, &TextInputV3DestroyRequest{})
}

func (o *TextInputV3) Enable() error {
	return o.proxy.SendRequest(TextInputV3RequestEnable, &TextInputV3EnableRequest{})
}

func (o *TextInputV3) Disable() error {
	return o.proxy.SendRequest(TextInputV3RequestDisable, &TextInputV3DisableRequest{})
}

func (o *TextInputV3) SetSurroundingText(text string, cursor int32, anchor int32) error {
	return o.proxy.SendRequest(TextInputV3RequestSetSurroundingText, &TextInputV3SetSurroundingTextRequest{
		Text:   text,
		Cursor: cursor,
		Anchor: anchor,
	})
}

func (o *TextInputV3) SetTextChangeCause(cause uint32) error {
	return o.proxy.SendRequest(TextInputV3RequestSetTextChangeCause, &TextInputV3SetTextChangeCauseRequest{
		Cause: cause,
	})
}

func (o *TextInputV3) SetContentType(hint uint32, purpose uint32) error {
	return o.proxy.SendRequest(TextInputV3RequestSetContentType, &TextInputV3SetContentTypeRequest{
		Hint:    hint,
		Purpose: purpose,
	})
}

func (o *TextInputV3) SetCursorRectangle(x int32, y int32, width int32, height int32) error {
	return o.proxy.SendRequest(TextInputV3RequestSetCursorRectangle, &TextInputV3SetCursorRectangleRequest{
		X:      x,
		Y:      y,
		Width:  width,
		Height: height,
	})
}

func (o *TextInputV3) Commit() error {
	return o.proxy.SendRequest(TextInputV3RequestCommit, &TextInputV3CommitRequest{})
}

func (o *TextInputV3) SetAvailableActions(availableActions []byte) error {
	return o.proxy.SendRequest(TextInputV3RequestSetAvailableActions, &TextInputV3SetAvailableActionsRequest{
		AvailableActions: availableActions,
	})
}

func (o *TextInputV3) ShowInputPanel() error {
	return o.proxy.SendRequest(TextInputV3RequestShowInputPanel, &TextInputV3ShowInputPanelRequest{})
}

func (o *TextInputV3) HideInputPanel() error {
	return o.proxy.SendRequest(TextInputV3RequestHideInputPanel, &TextInputV3HideInputPanelRequest{})
}

func BindTextInputV3(b wayland.Binder, name uint32, version uint32) (*TextInputV3, error) {
	if version < 1 || version > VersionTextInputV3 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceTextInputV3, version)
	if err != nil {
		return nil, err
	}
	x := NewTextInputV3(p)
	x.proxy.SetVersion(version)
	return x, nil
}
