// Code generated by wayland-scanner. DO NOT EDIT.

package idleinhibitunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceIdleInhibitManagerV1 = "zwp_idle_inhibit_manager_v1"
const VersionIdleInhibitManagerV1 = 1

const (
	IdleInhibitManagerV1RequestDestroy         uint16 = 0
	IdleInhibitManagerV1RequestCreateInhibitor uint16 = 1
)

type IdleInhibitManagerV1DestroyRequest struct {
}

func (r *IdleInhibitManagerV1DestroyRequest) Opcode() uint16 {
	return IdleInhibitManagerV1RequestDestroy
}

func (r *IdleInhibitManagerV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *IdleInhibitManagerV1DestroyRequest) Since() uint32 { return 1 }

type IdleInhibitManagerV1CreateInhibitorRequest struct {
	ID      wire.NewID
	Surface wire.ObjectID
}

func (r *IdleInhibitManagerV1CreateInhibitorRequest) Opcode() uint16 {
	return IdleInhibitManagerV1RequestCreateInhibitor
}

func (r *IdleInhibitManagerV1CreateInhibitorRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Surface); err != nil {
		return err
	}
	return nil
}

func (r *IdleInhibitManagerV1CreateInhibitorRequest) Since() uint32 { return 1 }

type IdleInhibitManagerV1 struct {
	proxy *wayland.Proxy
}

func NewIdleInhibitManagerV1(p *wayland.Proxy) *IdleInhibitManagerV1 {
	return &IdleInhibitManagerV1{proxy: p}
}

func (o *IdleInhibitManagerV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *IdleInhibitManagerV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(IdleInhibitManagerV1RequestDestroy, &IdleInhibitManagerV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

func (o *IdleInhibitManagerV1) CreateInhibitor(surface wire.ObjectID) (*IdleInhibitorV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewIdleInhibitorV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), IdleInhibitManagerV1RequestCreateInhibitor, &IdleInhibitManagerV1CreateInhibitorRequest{
		ID:      wire.NewID(p.ID()),
		Surface: surface,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// BindIdleInhibitManagerV1 binds the zwp_idle_inhibit_manager_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionIdleInhibitManagerV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindIdleInhibitManagerV1(reg, name, min(g.Version,
// VersionIdleInhibitManagerV1)), to bind at the highest mutually supported version.
func BindIdleInhibitManagerV1(b wayland.Binder, name uint32, version uint32) (*IdleInhibitManagerV1, error) {
	if version < 1 || version > VersionIdleInhibitManagerV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceIdleInhibitManagerV1, version)
	if err != nil {
		return nil, err
	}
	x := NewIdleInhibitManagerV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
