// Code generated by wayland-scanner. DO NOT EDIT.

package extsessionlock

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceSessionLockV1 = "ext_session_lock_v1"
const VersionSessionLockV1 = 1

const (
	SessionLockV1RequestDestroy          uint16 = 0
	SessionLockV1RequestGetLockSurface   uint16 = 1
	SessionLockV1RequestUnlockAndDestroy uint16 = 2
)

const (
	SessionLockV1EventLocked   uint16 = 0
	SessionLockV1EventFinished uint16 = 1
)

type SessionLockV1Error uint32

const (
	SessionLockV1ErrorInvalidDestroy     SessionLockV1Error = 0
	SessionLockV1ErrorInvalidUnlock      SessionLockV1Error = 1
	SessionLockV1ErrorRole               SessionLockV1Error = 2
	SessionLockV1ErrorDuplicateOutput    SessionLockV1Error = 3
	SessionLockV1ErrorAlreadyConstructed SessionLockV1Error = 4
)

type SessionLockV1DestroyRequest struct {
}

func (r *SessionLockV1DestroyRequest) Opcode() uint16 { return SessionLockV1RequestDestroy }

func (r *SessionLockV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SessionLockV1DestroyRequest) Since() int { return 1 }

type SessionLockV1GetLockSurfaceRequest struct {
	ID      wire.NewID
	Surface wire.ObjectID
	Output  wire.ObjectID
}

func (r *SessionLockV1GetLockSurfaceRequest) Opcode() uint16 {
	return SessionLockV1RequestGetLockSurface
}

func (r *SessionLockV1GetLockSurfaceRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Surface); err != nil {
		return err
	}
	if err := w.Object(r.Output); err != nil {
		return err
	}
	return nil
}

func (r *SessionLockV1GetLockSurfaceRequest) Since() int { return 1 }

type SessionLockV1UnlockAndDestroyRequest struct {
}

func (r *SessionLockV1UnlockAndDestroyRequest) Opcode() uint16 {
	return SessionLockV1RequestUnlockAndDestroy
}

func (r *SessionLockV1UnlockAndDestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SessionLockV1UnlockAndDestroyRequest) Since() int { return 1 }

type SessionLockV1LockedEvent struct {
}

func (e *SessionLockV1LockedEvent) Opcode() uint16 { return SessionLockV1EventLocked }

func (e *SessionLockV1LockedEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *SessionLockV1LockedEvent) Since() int { return 1 }

type SessionLockV1FinishedEvent struct {
}

func (e *SessionLockV1FinishedEvent) Opcode() uint16 { return SessionLockV1EventFinished }

func (e *SessionLockV1FinishedEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *SessionLockV1FinishedEvent) Since() int { return 1 }

type SessionLockV1LockedFunc func(ev SessionLockV1LockedEvent)

type SessionLockV1FinishedFunc func(ev SessionLockV1FinishedEvent)

type SessionLockV1 struct {
	proxy *wayland.Proxy
}

func NewSessionLockV1(p *wayland.Proxy) *SessionLockV1 {
	return &SessionLockV1{proxy: p}
}

func (o *SessionLockV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *SessionLockV1) OnLocked(fn SessionLockV1LockedFunc) {
	o.proxy.RegisterEvent(SessionLockV1EventLocked, func(r *wire.Reader) {
		var ev SessionLockV1LockedEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *SessionLockV1) OnFinished(fn SessionLockV1FinishedFunc) {
	o.proxy.RegisterEvent(SessionLockV1EventFinished, func(r *wire.Reader) {
		var ev SessionLockV1FinishedEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *SessionLockV1) Destroy() error {
	return o.proxy.SendRequest(SessionLockV1RequestDestroy, &SessionLockV1DestroyRequest{})
}

func (o *SessionLockV1) GetLockSurface(surface wire.ObjectID, output wire.ObjectID) (*SessionLockSurfaceV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewSessionLockSurfaceV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), SessionLockV1RequestGetLockSurface, &SessionLockV1GetLockSurfaceRequest{
		ID:      wire.NewID(p.ID()),
		Surface: surface,
		Output:  output,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func (o *SessionLockV1) UnlockAndDestroy() error {
	return o.proxy.SendRequest(SessionLockV1RequestUnlockAndDestroy, &SessionLockV1UnlockAndDestroyRequest{})
}

func BindSessionLockV1(b wayland.Binder, name uint32, version uint32) (*SessionLockV1, error) {
	if version < 1 || version > VersionSessionLockV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceSessionLockV1, version)
	if err != nil {
		return nil, err
	}
	x := NewSessionLockV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
