// Code generated by wayland-scanner. DO NOT EDIT.

package extsessionlock

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceSessionLockSurfaceV1 = "ext_session_lock_surface_v1"
const VersionSessionLockSurfaceV1 = 1

const (
	SessionLockSurfaceV1RequestDestroy      uint16 = 0
	SessionLockSurfaceV1RequestAckConfigure uint16 = 1
)

const (
	SessionLockSurfaceV1EventConfigure uint16 = 0
)

// sessionlocksurfacev1EventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var sessionlocksurfacev1EventFDCounts = map[uint16]int{
	0: 0,
}

func init() {
	wayland.RegisterInterfaceFDCounts(InterfaceSessionLockSurfaceV1, sessionlocksurfacev1EventFDCounts)
}

type SessionLockSurfaceV1Error uint32

const (
	// SessionLockSurfaceV1ErrorCommitBeforeFirstAck surface committed before first ack_configure request.
	SessionLockSurfaceV1ErrorCommitBeforeFirstAck SessionLockSurfaceV1Error = 0

	// SessionLockSurfaceV1ErrorNullBuffer surface committed with a null buffer.
	SessionLockSurfaceV1ErrorNullBuffer SessionLockSurfaceV1Error = 1

	// SessionLockSurfaceV1ErrorDimensionsMismatch failed to match ack'd width/height.
	SessionLockSurfaceV1ErrorDimensionsMismatch SessionLockSurfaceV1Error = 2

	// SessionLockSurfaceV1ErrorInvalidSerial serial provided in ack_configure is invalid.
	SessionLockSurfaceV1ErrorInvalidSerial SessionLockSurfaceV1Error = 3
)

// SessionLockSurfaceV1DestroyRequest destroy the lock surface object.
//
// This informs the compositor that the lock surface object will no
// longer be used.
//
// It is recommended for a lock client to destroy lock surfaces if
// their corresponding wl_output global is removed.
//
// If a lock surface on an active output is destroyed before the
// ext_session_lock_v1.unlock_and_destroy event is sent, the compositor
// must fall back to rendering a solid color.
type SessionLockSurfaceV1DestroyRequest struct {
}

func (r *SessionLockSurfaceV1DestroyRequest) Opcode() uint16 {
	return SessionLockSurfaceV1RequestDestroy
}

func (r *SessionLockSurfaceV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SessionLockSurfaceV1DestroyRequest) Since() uint32 { return 1 }

// SessionLockSurfaceV1AckConfigureRequest ack a configure event.
//
// When a configure event is received, if a client commits the surface
// in response to the configure event, then the client must make an
// ack_configure request sometime before the commit request, passing
// along the serial of the configure event.
//
// If the client receives multiple configure events before it can
// respond to one, it only has to ack the last configure event.
//
// A client is not required to commit immediately after sending an
// ack_configure request - it may even ack_configure several times
// before its next surface commit.
//
// A client may send multiple ack_configure requests before committing,
// but only the last request sent before a commit indicates which
// configure event the client really is responding to.
//
// Sending an ack_configure request consumes the configure event
// referenced by the given serial, as well as all older configure events
// sent on this object.
//
// It is a protocol error to issue multiple ack_configure requests
// referencing the same configure event or to issue an ack_configure
// request referencing a configure event older than the last configure
// event acked for a given lock surface.
type SessionLockSurfaceV1AckConfigureRequest struct {
	// Serial serial from the configure event.
	Serial uint32
}

func (r *SessionLockSurfaceV1AckConfigureRequest) Opcode() uint16 {
	return SessionLockSurfaceV1RequestAckConfigure
}

func (r *SessionLockSurfaceV1AckConfigureRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Serial); err != nil {
		return err
	}
	return nil
}

func (r *SessionLockSurfaceV1AckConfigureRequest) Since() uint32 { return 1 }

// SessionLockSurfaceV1ConfigureEvent the client should resize its surface.
//
// This event is sent once on binding the interface and may be sent again
// at the compositor's discretion, for example if output geometry changes.
//
// The width and height are in surface-local coordinates and are exact
// requirements. Failing to match these surface dimensions in the next
// commit after acking a configure is a protocol error.
type SessionLockSurfaceV1ConfigureEvent struct {
	// Serial serial for use in ack_configure.
	Serial uint32
	Width  uint32
	Height uint32
}

func (e *SessionLockSurfaceV1ConfigureEvent) Opcode() uint16 {
	return SessionLockSurfaceV1EventConfigure
}

func (e *SessionLockSurfaceV1ConfigureEvent) Unmarshal(r *wire.Reader) error {
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	width, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Width = width
	height, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Height = height
	return nil
}

func (e *SessionLockSurfaceV1ConfigureEvent) Since() uint32 { return 1 }

// SessionLockSurfaceV1ConfigureFunc is a callback for Configure events.
type SessionLockSurfaceV1ConfigureFunc func(ev SessionLockSurfaceV1ConfigureEvent)

// SessionLockSurfaceV1 a surface displayed while the session is locked.
//
// The client may use lock surfaces to display a screensaver, render a
// dialog to enter a password and unlock the session, or however else it
// sees fit.
//
// On binding this interface the compositor will immediately send the
// first configure event. After making the ack_configure request in
// response to this event the client should attach and commit the first
// buffer. Committing the surface before acking the first configure is a
// protocol error. Committing the surface with a null buffer at any time
// is a protocol error.
//
// The compositor is free to handle keyboard/pointer focus for lock
// surfaces however it chooses. A reasonable way to do this would be to
// give the first lock surface created keyboard focus and change keyboard
// focus if the user clicks on other surfaces.
type SessionLockSurfaceV1 struct {
	proxy *wayland.Proxy
}

// NewSessionLockSurfaceV1 wraps p in a SessionLockSurfaceV1 proxy.
func NewSessionLockSurfaceV1(p *wayland.Proxy) *SessionLockSurfaceV1 {
	p.SetEventFDCounts(sessionlocksurfacev1EventFDCounts)
	return &SessionLockSurfaceV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *SessionLockSurfaceV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// OnConfigure registers fn to receive Configure events.
func (o *SessionLockSurfaceV1) OnConfigure(fn SessionLockSurfaceV1ConfigureFunc) {
	o.proxy.RegisterEvent(SessionLockSurfaceV1EventConfigure, func(r *wire.Reader) {
		var ev SessionLockSurfaceV1ConfigureEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Configure", err)
			return
		}

		fn(ev)
	})
}

// Destroy destroy the lock surface object.
//
// This informs the compositor that the lock surface object will no
// longer be used.
//
// It is recommended for a lock client to destroy lock surfaces if
// their corresponding wl_output global is removed.
//
// If a lock surface on an active output is destroyed before the
// ext_session_lock_v1.unlock_and_destroy event is sent, the compositor
// must fall back to rendering a solid color.
func (o *SessionLockSurfaceV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(SessionLockSurfaceV1RequestDestroy, &SessionLockSurfaceV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// AckConfigure ack a configure event.
//
// When a configure event is received, if a client commits the surface
// in response to the configure event, then the client must make an
// ack_configure request sometime before the commit request, passing
// along the serial of the configure event.
//
// If the client receives multiple configure events before it can
// respond to one, it only has to ack the last configure event.
//
// A client is not required to commit immediately after sending an
// ack_configure request - it may even ack_configure several times
// before its next surface commit.
//
// A client may send multiple ack_configure requests before committing,
// but only the last request sent before a commit indicates which
// configure event the client really is responding to.
//
// Sending an ack_configure request consumes the configure event
// referenced by the given serial, as well as all older configure events
// sent on this object.
//
// It is a protocol error to issue multiple ack_configure requests
// referencing the same configure event or to issue an ack_configure
// request referencing a configure event older than the last configure
// event acked for a given lock surface.
func (o *SessionLockSurfaceV1) AckConfigure(serial uint32) error {
	return o.proxy.SendRequest(SessionLockSurfaceV1RequestAckConfigure, &SessionLockSurfaceV1AckConfigureRequest{
		Serial: serial,
	})
}

// BindSessionLockSurfaceV1 binds the ext_session_lock_surface_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionSessionLockSurfaceV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindSessionLockSurfaceV1(reg, name, min(g.Version,
// VersionSessionLockSurfaceV1)), to bind at the highest mutually supported version.
func BindSessionLockSurfaceV1(b wayland.Binder, name uint32, version uint32) (*SessionLockSurfaceV1, error) {
	if version < 1 || version > VersionSessionLockSurfaceV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceSessionLockSurfaceV1, version)
	if err != nil {
		return nil, err
	}
	x := NewSessionLockSurfaceV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
