// Code generated by wayland-scanner. DO NOT EDIT.

package xdgtopleveltag

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceToplevelTagManagerV1 = "xdg_toplevel_tag_manager_v1"
const VersionToplevelTagManagerV1 = 1

const (
	ToplevelTagManagerV1RequestDestroy                uint16 = 0
	ToplevelTagManagerV1RequestSetToplevelTag         uint16 = 1
	ToplevelTagManagerV1RequestSetToplevelDescription uint16 = 2
)

type ToplevelTagManagerV1DestroyRequest struct {
}

func (r *ToplevelTagManagerV1DestroyRequest) Opcode() uint16 {
	return ToplevelTagManagerV1RequestDestroy
}

func (r *ToplevelTagManagerV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *ToplevelTagManagerV1DestroyRequest) Since() uint32 { return 1 }

type ToplevelTagManagerV1SetToplevelTagRequest struct {
	Toplevel wire.ObjectID
	Tag      string
}

func (r *ToplevelTagManagerV1SetToplevelTagRequest) Opcode() uint16 {
	return ToplevelTagManagerV1RequestSetToplevelTag
}

func (r *ToplevelTagManagerV1SetToplevelTagRequest) Marshal(w *wire.Writer) error {
	if err := w.Object(r.Toplevel); err != nil {
		return err
	}
	if err := w.String(r.Tag); err != nil {
		return err
	}
	return nil
}

func (r *ToplevelTagManagerV1SetToplevelTagRequest) Since() uint32 { return 1 }

type ToplevelTagManagerV1SetToplevelDescriptionRequest struct {
	Toplevel    wire.ObjectID
	Description string
}

func (r *ToplevelTagManagerV1SetToplevelDescriptionRequest) Opcode() uint16 {
	return ToplevelTagManagerV1RequestSetToplevelDescription
}

func (r *ToplevelTagManagerV1SetToplevelDescriptionRequest) Marshal(w *wire.Writer) error {
	if err := w.Object(r.Toplevel); err != nil {
		return err
	}
	if err := w.String(r.Description); err != nil {
		return err
	}
	return nil
}

func (r *ToplevelTagManagerV1SetToplevelDescriptionRequest) Since() uint32 { return 1 }

type ToplevelTagManagerV1 struct {
	proxy *wayland.Proxy
}

func NewToplevelTagManagerV1(p *wayland.Proxy) *ToplevelTagManagerV1 {
	return &ToplevelTagManagerV1{proxy: p}
}

func (o *ToplevelTagManagerV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *ToplevelTagManagerV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(ToplevelTagManagerV1RequestDestroy, &ToplevelTagManagerV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

func (o *ToplevelTagManagerV1) SetToplevelTag(toplevel wire.ObjectID, tag string) error {
	return o.proxy.SendRequest(ToplevelTagManagerV1RequestSetToplevelTag, &ToplevelTagManagerV1SetToplevelTagRequest{
		Toplevel: toplevel,
		Tag:      tag,
	})
}

func (o *ToplevelTagManagerV1) SetToplevelDescription(toplevel wire.ObjectID, description string) error {
	return o.proxy.SendRequest(ToplevelTagManagerV1RequestSetToplevelDescription, &ToplevelTagManagerV1SetToplevelDescriptionRequest{
		Toplevel:    toplevel,
		Description: description,
	})
}

// BindToplevelTagManagerV1 binds the xdg_toplevel_tag_manager_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionToplevelTagManagerV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindToplevelTagManagerV1(reg, name, min(g.Version,
// VersionToplevelTagManagerV1)), to bind at the highest mutually supported version.
func BindToplevelTagManagerV1(b wayland.Binder, name uint32, version uint32) (*ToplevelTagManagerV1, error) {
	if version < 1 || version > VersionToplevelTagManagerV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceToplevelTagManagerV1, version)
	if err != nil {
		return nil, err
	}
	x := NewToplevelTagManagerV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
