// Code generated by wayland-scanner. DO NOT EDIT.

package xdgdecorationunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceDecorationManagerV1 = "zxdg_decoration_manager_v1"
const VersionDecorationManagerV1 = 2

const (
	DecorationManagerV1RequestDestroy               uint16 = 0
	DecorationManagerV1RequestGetToplevelDecoration uint16 = 1
)

type DecorationManagerV1DestroyRequest struct {
}

func (r *DecorationManagerV1DestroyRequest) Opcode() uint16 { return DecorationManagerV1RequestDestroy }

func (r *DecorationManagerV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *DecorationManagerV1DestroyRequest) Since() int { return 1 }

type DecorationManagerV1GetToplevelDecorationRequest struct {
	ID       wire.NewID
	Toplevel wire.ObjectID
}

func (r *DecorationManagerV1GetToplevelDecorationRequest) Opcode() uint16 {
	return DecorationManagerV1RequestGetToplevelDecoration
}

func (r *DecorationManagerV1GetToplevelDecorationRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Toplevel); err != nil {
		return err
	}
	return nil
}

func (r *DecorationManagerV1GetToplevelDecorationRequest) Since() int { return 1 }

type DecorationManagerV1 struct {
	proxy *wayland.Proxy
}

func NewDecorationManagerV1(p *wayland.Proxy) *DecorationManagerV1 {
	return &DecorationManagerV1{proxy: p}
}

func (o *DecorationManagerV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *DecorationManagerV1) Destroy() error {
	return o.proxy.SendRequest(DecorationManagerV1RequestDestroy, &DecorationManagerV1DestroyRequest{})
}

func (o *DecorationManagerV1) GetToplevelDecoration(toplevel wire.ObjectID) (*ToplevelDecorationV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewToplevelDecorationV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), DecorationManagerV1RequestGetToplevelDecoration, &DecorationManagerV1GetToplevelDecorationRequest{
		ID:       wire.NewID(p.ID()),
		Toplevel: toplevel,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func BindDecorationManagerV1(b wayland.Binder, name uint32, version uint32) (*DecorationManagerV1, error) {
	if version < 1 || version > VersionDecorationManagerV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceDecorationManagerV1, version)
	if err != nil {
		return nil, err
	}
	x := NewDecorationManagerV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
