// Code generated by wayland-scanner. DO NOT EDIT.

package xwaylandkeyboardgrabunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceXwaylandKeyboardGrabManagerV1 = "zwp_xwayland_keyboard_grab_manager_v1"
const VersionXwaylandKeyboardGrabManagerV1 = 1

const (
	XwaylandKeyboardGrabManagerV1RequestDestroy      uint16 = 0
	XwaylandKeyboardGrabManagerV1RequestGrabKeyboard uint16 = 1
)

type XwaylandKeyboardGrabManagerV1DestroyRequest struct {
}

func (r *XwaylandKeyboardGrabManagerV1DestroyRequest) Opcode() uint16 {
	return XwaylandKeyboardGrabManagerV1RequestDestroy
}

func (r *XwaylandKeyboardGrabManagerV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *XwaylandKeyboardGrabManagerV1DestroyRequest) Since() int { return 1 }

type XwaylandKeyboardGrabManagerV1GrabKeyboardRequest struct {
	ID      wire.NewID
	Surface wire.ObjectID
	Seat    wire.ObjectID
}

func (r *XwaylandKeyboardGrabManagerV1GrabKeyboardRequest) Opcode() uint16 {
	return XwaylandKeyboardGrabManagerV1RequestGrabKeyboard
}

func (r *XwaylandKeyboardGrabManagerV1GrabKeyboardRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Surface); err != nil {
		return err
	}
	if err := w.Object(r.Seat); err != nil {
		return err
	}
	return nil
}

func (r *XwaylandKeyboardGrabManagerV1GrabKeyboardRequest) Since() int { return 1 }

type XwaylandKeyboardGrabManagerV1 struct {
	proxy *wayland.Proxy
}

func NewXwaylandKeyboardGrabManagerV1(p *wayland.Proxy) *XwaylandKeyboardGrabManagerV1 {
	return &XwaylandKeyboardGrabManagerV1{proxy: p}
}

func (o *XwaylandKeyboardGrabManagerV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *XwaylandKeyboardGrabManagerV1) Destroy() error {
	return o.proxy.SendRequest(XwaylandKeyboardGrabManagerV1RequestDestroy, &XwaylandKeyboardGrabManagerV1DestroyRequest{})
}

func (o *XwaylandKeyboardGrabManagerV1) GrabKeyboard(surface wire.ObjectID, seat wire.ObjectID) (*XwaylandKeyboardGrabV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewXwaylandKeyboardGrabV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), XwaylandKeyboardGrabManagerV1RequestGrabKeyboard, &XwaylandKeyboardGrabManagerV1GrabKeyboardRequest{
		ID:      wire.NewID(p.ID()),
		Surface: surface,
		Seat:    seat,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func BindXwaylandKeyboardGrabManagerV1(b wayland.Binder, name uint32, version uint32) (*XwaylandKeyboardGrabManagerV1, error) {
	if version < 1 || version > VersionXwaylandKeyboardGrabManagerV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceXwaylandKeyboardGrabManagerV1, version)
	if err != nil {
		return nil, err
	}
	x := NewXwaylandKeyboardGrabManagerV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
