// Code generated by wayland-scanner. DO NOT EDIT.

package alphamodifier

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceAlphaModifierSurfaceV1 = "wp_alpha_modifier_surface_v1"
const VersionAlphaModifierSurfaceV1 = 1

const (
	AlphaModifierSurfaceV1RequestDestroy       uint16 = 0
	AlphaModifierSurfaceV1RequestSetMultiplier uint16 = 1
)

type AlphaModifierSurfaceV1Error uint32

const (
	// AlphaModifierSurfaceV1ErrorNoSurface wl_surface was destroyed.
	AlphaModifierSurfaceV1ErrorNoSurface AlphaModifierSurfaceV1Error = 0
)

// AlphaModifierSurfaceV1DestroyRequest destroy the alpha modifier object.
//
// This destroys the object, and is equivalent to set_multiplier with
// a value of UINT32_MAX, with the same double-buffered semantics as
// set_multiplier.
type AlphaModifierSurfaceV1DestroyRequest struct{}

func (r *AlphaModifierSurfaceV1DestroyRequest) Opcode() uint16 {
	return AlphaModifierSurfaceV1RequestDestroy
}

func (r *AlphaModifierSurfaceV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *AlphaModifierSurfaceV1DestroyRequest) Since() uint32 { return 1 }

// AlphaModifierSurfaceV1SetMultiplierRequest specify the alpha multiplier.
//
// Sets the alpha multiplier for the surface. The alpha multiplier is
// double-buffered state, see wl_surface.commit for details.
//
// This factor is applied in the compositor's blending space, as an
// additional step after the processing of per-pixel alpha values for the
// wl_surface. The exact meaning of the factor is thus undefined, unless
// the blending space is specified in a different extension.
//
// This multiplier is applied even if the buffer attached to the
// wl_surface doesn't have an alpha channel; in that case an alpha value
// of one is used instead.
//
// Zero means completely transparent, UINT32_MAX means completely opaque.
type AlphaModifierSurfaceV1SetMultiplierRequest struct {
	Factor uint32
}

func (r *AlphaModifierSurfaceV1SetMultiplierRequest) Opcode() uint16 {
	return AlphaModifierSurfaceV1RequestSetMultiplier
}

func (r *AlphaModifierSurfaceV1SetMultiplierRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Factor); err != nil {
		return err
	}
	return nil
}

func (r *AlphaModifierSurfaceV1SetMultiplierRequest) Since() uint32 { return 1 }

// AlphaModifierSurfaceV1 alpha modifier object for a surface.
//
// This interface allows the client to set a factor for the alpha values on
// a surface, which can be used to offload such operations to the compositor.
// The default factor is UINT32_MAX.
//
// This object has to be destroyed before the associated wl_surface. Once the
// wl_surface is destroyed, all request on this object will raise the
// no_surface error.
type AlphaModifierSurfaceV1 struct {
	proxy *wayland.Proxy
}

// NewAlphaModifierSurfaceV1 wraps p in a AlphaModifierSurfaceV1 proxy.
func NewAlphaModifierSurfaceV1(p *wayland.Proxy) *AlphaModifierSurfaceV1 {
	return &AlphaModifierSurfaceV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *AlphaModifierSurfaceV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// Destroy destroy the alpha modifier object.
//
// This destroys the object, and is equivalent to set_multiplier with
// a value of UINT32_MAX, with the same double-buffered semantics as
// set_multiplier.
func (o *AlphaModifierSurfaceV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(AlphaModifierSurfaceV1RequestDestroy, &AlphaModifierSurfaceV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// SetMultiplier specify the alpha multiplier.
//
// Sets the alpha multiplier for the surface. The alpha multiplier is
// double-buffered state, see wl_surface.commit for details.
//
// This factor is applied in the compositor's blending space, as an
// additional step after the processing of per-pixel alpha values for the
// wl_surface. The exact meaning of the factor is thus undefined, unless
// the blending space is specified in a different extension.
//
// This multiplier is applied even if the buffer attached to the
// wl_surface doesn't have an alpha channel; in that case an alpha value
// of one is used instead.
//
// Zero means completely transparent, UINT32_MAX means completely opaque.
func (o *AlphaModifierSurfaceV1) SetMultiplier(factor uint32) error {
	return o.proxy.SendRequest(AlphaModifierSurfaceV1RequestSetMultiplier, &AlphaModifierSurfaceV1SetMultiplierRequest{
		Factor: factor,
	})
}

// BindAlphaModifierSurfaceV1 binds the wp_alpha_modifier_surface_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionAlphaModifierSurfaceV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindAlphaModifierSurfaceV1(reg, name, min(g.Version,
// VersionAlphaModifierSurfaceV1)), to bind at the highest mutually supported version.
func BindAlphaModifierSurfaceV1(b wayland.Binder, name, version uint32) (*AlphaModifierSurfaceV1, error) {
	if version < 1 || version > VersionAlphaModifierSurfaceV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceAlphaModifierSurfaceV1, version)
	if err != nil {
		return nil, err
	}
	x := NewAlphaModifierSurfaceV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
