// Code generated by wayland-scanner. DO NOT EDIT.

package alphamodifier

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceAlphaModifierV1 = "wp_alpha_modifier_v1"
const VersionAlphaModifierV1 = 1

const (
	AlphaModifierV1RequestDestroy    uint16 = 0
	AlphaModifierV1RequestGetSurface uint16 = 1
)

type AlphaModifierV1Error uint32

const (
	AlphaModifierV1ErrorAlreadyConstructed AlphaModifierV1Error = 0
)

type AlphaModifierV1DestroyRequest struct {
}

func (r *AlphaModifierV1DestroyRequest) Opcode() uint16 { return AlphaModifierV1RequestDestroy }

func (r *AlphaModifierV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *AlphaModifierV1DestroyRequest) Since() int { return 1 }

type AlphaModifierV1GetSurfaceRequest struct {
	ID      wire.NewID
	Surface wire.ObjectID
}

func (r *AlphaModifierV1GetSurfaceRequest) Opcode() uint16 { return AlphaModifierV1RequestGetSurface }

func (r *AlphaModifierV1GetSurfaceRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Surface); err != nil {
		return err
	}
	return nil
}

func (r *AlphaModifierV1GetSurfaceRequest) Since() int { return 1 }

type AlphaModifierV1 struct {
	proxy *wayland.Proxy
}

func NewAlphaModifierV1(p *wayland.Proxy) *AlphaModifierV1 {
	return &AlphaModifierV1{proxy: p}
}

func (o *AlphaModifierV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *AlphaModifierV1) Destroy() error {
	return o.proxy.SendRequest(AlphaModifierV1RequestDestroy, &AlphaModifierV1DestroyRequest{})
}

func (o *AlphaModifierV1) GetSurface(surface wire.ObjectID) (*AlphaModifierSurfaceV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewAlphaModifierSurfaceV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), AlphaModifierV1RequestGetSurface, &AlphaModifierV1GetSurfaceRequest{
		ID:      wire.NewID(p.ID()),
		Surface: surface,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func BindAlphaModifierV1(b wayland.Binder, name uint32, version uint32) (*AlphaModifierV1, error) {
	if version < 1 || version > VersionAlphaModifierV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceAlphaModifierV1, version)
	if err != nil {
		return nil, err
	}
	x := NewAlphaModifierV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
