// Code generated by wayland-scanner. DO NOT EDIT.

package drmlease

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceDrmLeaseRequestV1 = "wp_drm_lease_request_v1"
const VersionDrmLeaseRequestV1 = 1

const (
	DrmLeaseRequestV1RequestRequestConnector uint16 = 0
	DrmLeaseRequestV1RequestSubmit           uint16 = 1
)

type DrmLeaseRequestV1Error uint32

const (
	DrmLeaseRequestV1ErrorWrongDevice        DrmLeaseRequestV1Error = 0
	DrmLeaseRequestV1ErrorDuplicateConnector DrmLeaseRequestV1Error = 1
	DrmLeaseRequestV1ErrorEmptyLease         DrmLeaseRequestV1Error = 2
)

type DrmLeaseRequestV1RequestConnectorRequest struct {
	Connector wire.ObjectID
}

func (r *DrmLeaseRequestV1RequestConnectorRequest) Opcode() uint16 {
	return DrmLeaseRequestV1RequestRequestConnector
}

func (r *DrmLeaseRequestV1RequestConnectorRequest) Marshal(w *wire.Writer) error {
	if err := w.Object(r.Connector); err != nil {
		return err
	}
	return nil
}

func (r *DrmLeaseRequestV1RequestConnectorRequest) Since() int { return 1 }

type DrmLeaseRequestV1SubmitRequest struct {
	ID wire.NewID
}

func (r *DrmLeaseRequestV1SubmitRequest) Opcode() uint16 { return DrmLeaseRequestV1RequestSubmit }

func (r *DrmLeaseRequestV1SubmitRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	return nil
}

func (r *DrmLeaseRequestV1SubmitRequest) Since() int { return 1 }

type DrmLeaseRequestV1 struct {
	proxy *wayland.Proxy
}

func NewDrmLeaseRequestV1(p *wayland.Proxy) *DrmLeaseRequestV1 {
	return &DrmLeaseRequestV1{proxy: p}
}

func (o *DrmLeaseRequestV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *DrmLeaseRequestV1) RequestConnector(connector wire.ObjectID) error {
	return o.proxy.SendRequest(DrmLeaseRequestV1RequestRequestConnector, &DrmLeaseRequestV1RequestConnectorRequest{
		Connector: connector,
	})
}

func (o *DrmLeaseRequestV1) Submit() (*DrmLeaseV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewDrmLeaseV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), DrmLeaseRequestV1RequestSubmit, &DrmLeaseRequestV1SubmitRequest{
		ID: wire.NewID(p.ID()),
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func BindDrmLeaseRequestV1(b wayland.Binder, name uint32, version uint32) (*DrmLeaseRequestV1, error) {
	if version < 1 || version > VersionDrmLeaseRequestV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceDrmLeaseRequestV1, version)
	if err != nil {
		return nil, err
	}
	x := NewDrmLeaseRequestV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
