// Code generated by wayland-scanner. DO NOT EDIT.

package drmlease

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceDrmLeaseV1 = "wp_drm_lease_v1"
const VersionDrmLeaseV1 = 1

const (
	DrmLeaseV1RequestDestroy uint16 = 0
)

const (
	DrmLeaseV1EventLeaseFd  uint16 = 0
	DrmLeaseV1EventFinished uint16 = 1
)

var drmleasev1EventFDCounts = map[uint16]int{
	0: 1,
}

type DrmLeaseV1DestroyRequest struct {
}

func (r *DrmLeaseV1DestroyRequest) Opcode() uint16 { return DrmLeaseV1RequestDestroy }

func (r *DrmLeaseV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *DrmLeaseV1DestroyRequest) Since() int { return 1 }

type DrmLeaseV1LeaseFdEvent struct {
	LeasedFd int
}

func (e *DrmLeaseV1LeaseFdEvent) Opcode() uint16 { return DrmLeaseV1EventLeaseFd }

func (e *DrmLeaseV1LeaseFdEvent) Unmarshal(r *wire.Reader) error {
	leasedFd, err := r.Fd()
	if err != nil {
		return err
	}
	e.LeasedFd = leasedFd
	return nil
}

func (e *DrmLeaseV1LeaseFdEvent) Since() int { return 1 }

type DrmLeaseV1FinishedEvent struct {
}

func (e *DrmLeaseV1FinishedEvent) Opcode() uint16 { return DrmLeaseV1EventFinished }

func (e *DrmLeaseV1FinishedEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *DrmLeaseV1FinishedEvent) Since() int { return 1 }

type DrmLeaseV1LeaseFdFunc func(ev DrmLeaseV1LeaseFdEvent)

type DrmLeaseV1FinishedFunc func(ev DrmLeaseV1FinishedEvent)

type DrmLeaseV1 struct {
	proxy *wayland.Proxy
}

func NewDrmLeaseV1(p *wayland.Proxy) *DrmLeaseV1 {
	p.SetEventFDCounts(drmleasev1EventFDCounts)
	return &DrmLeaseV1{proxy: p}
}

func (o *DrmLeaseV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *DrmLeaseV1) OnLeaseFd(fn DrmLeaseV1LeaseFdFunc) {
	o.proxy.RegisterEvent(DrmLeaseV1EventLeaseFd, func(r *wire.Reader) {
		var ev DrmLeaseV1LeaseFdEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *DrmLeaseV1) OnFinished(fn DrmLeaseV1FinishedFunc) {
	o.proxy.RegisterEvent(DrmLeaseV1EventFinished, func(r *wire.Reader) {
		var ev DrmLeaseV1FinishedEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *DrmLeaseV1) Destroy() error {
	return o.proxy.SendRequest(DrmLeaseV1RequestDestroy, &DrmLeaseV1DestroyRequest{})
}

func BindDrmLeaseV1(b wayland.Binder, name uint32, version uint32) (*DrmLeaseV1, error) {
	if version < 1 || version > VersionDrmLeaseV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceDrmLeaseV1, version)
	if err != nil {
		return nil, err
	}
	x := NewDrmLeaseV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
