// Code generated by wayland-scanner. DO NOT EDIT.

package inputtimestampsunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceInputTimestampsV1 = "zwp_input_timestamps_v1"
const VersionInputTimestampsV1 = 1

const (
	InputTimestampsV1RequestDestroy uint16 = 0
)

const (
	InputTimestampsV1EventTimestamp uint16 = 0
)

// inputtimestampsv1EventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var inputtimestampsv1EventFDCounts = map[uint16]int{
	0: 0,
}

func init() {
	wayland.RegisterInterfaceFDCounts(InterfaceInputTimestampsV1, inputtimestampsv1EventFDCounts)
}

// InputTimestampsV1DestroyRequest destroy the input timestamps object.
//
// Informs the server that the client will no longer be using this
// protocol object. After the server processes the request, no more
// timestamp events will be emitted.
type InputTimestampsV1DestroyRequest struct{}

func (r *InputTimestampsV1DestroyRequest) Opcode() uint16 { return InputTimestampsV1RequestDestroy }

func (r *InputTimestampsV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *InputTimestampsV1DestroyRequest) Since() uint32 { return 1 }

// InputTimestampsV1TimestampEvent high-resolution timestamp event.
//
// The timestamp event is associated with the first subsequent input event
// carrying a timestamp which belongs to the set of input events this
// object is subscribed to.
//
// The timestamp provided by this event is a high-resolution version of
// the timestamp argument of the associated input event. The provided
// timestamp is in the same clock domain and is at least as accurate as
// the associated input event timestamp.
//
// The timestamp is expressed as tv_sec_hi, tv_sec_lo, tv_nsec triples,
// each component being an unsigned 32-bit value. Whole seconds are in
// tv_sec which is a 64-bit value combined from tv_sec_hi and tv_sec_lo,
// and the additional fractional part in tv_nsec as nanoseconds. Hence,
// for valid timestamps tv_nsec must be in [0, 999999999].
type InputTimestampsV1TimestampEvent struct {
	// TvSecHi high 32 bits of the seconds part of the timestamp.
	TvSecHi uint32
	// TvSecLo low 32 bits of the seconds part of the timestamp.
	TvSecLo uint32
	// TvNsec nanoseconds part of the timestamp.
	TvNsec uint32
}

func (e *InputTimestampsV1TimestampEvent) Opcode() uint16 { return InputTimestampsV1EventTimestamp }

func (e *InputTimestampsV1TimestampEvent) Unmarshal(r *wire.Reader) error {
	tvSecHi, err := r.Uint32()
	if err != nil {
		return err
	}
	e.TvSecHi = tvSecHi
	tvSecLo, err := r.Uint32()
	if err != nil {
		return err
	}
	e.TvSecLo = tvSecLo
	tvNsec, err := r.Uint32()
	if err != nil {
		return err
	}
	e.TvNsec = tvNsec
	return nil
}

func (e *InputTimestampsV1TimestampEvent) Since() uint32 { return 1 }

// InputTimestampsV1TimestampFunc is a callback for Timestamp events.
type InputTimestampsV1TimestampFunc func(ev InputTimestampsV1TimestampEvent)

// InputTimestampsV1 context object for input timestamps.
//
// Provides high-resolution timestamp events for a set of subscribed input
// events. The set of subscribed input events is determined by the
// zwp_input_timestamps_manager_v1 request used to create this object.
type InputTimestampsV1 struct {
	proxy *wayland.Proxy
}

// NewInputTimestampsV1 wraps p in a InputTimestampsV1 proxy.
func NewInputTimestampsV1(p *wayland.Proxy) *InputTimestampsV1 {
	p.SetEventFDCounts(inputtimestampsv1EventFDCounts)
	return &InputTimestampsV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *InputTimestampsV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// OnTimestamp registers fn to receive Timestamp events.
func (o *InputTimestampsV1) OnTimestamp(fn InputTimestampsV1TimestampFunc) {
	o.proxy.RegisterEvent(InputTimestampsV1EventTimestamp, func(r *wire.Reader) {
		var ev InputTimestampsV1TimestampEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Timestamp", err)
			return
		}
		fn(ev)
	})
}

// Destroy destroy the input timestamps object.
//
// Informs the server that the client will no longer be using this
// protocol object. After the server processes the request, no more
// timestamp events will be emitted.
func (o *InputTimestampsV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(InputTimestampsV1RequestDestroy, &InputTimestampsV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// BindInputTimestampsV1 binds the zwp_input_timestamps_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionInputTimestampsV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindInputTimestampsV1(reg, name, min(g.Version,
// VersionInputTimestampsV1)), to bind at the highest mutually supported version.
func BindInputTimestampsV1(b wayland.Binder, name, version uint32) (*InputTimestampsV1, error) {
	if version < 1 || version > VersionInputTimestampsV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceInputTimestampsV1, version)
	if err != nil {
		return nil, err
	}
	x := NewInputTimestampsV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
