// Code generated by wayland-scanner. DO NOT EDIT.

package xdgforeignunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceExporterV1 = "zxdg_exporter_v1"
const VersionExporterV1 = 1

const (
	ExporterV1RequestDestroy uint16 = 0
	ExporterV1RequestExport  uint16 = 1
)

// ExporterV1DestroyRequest destroy the xdg_exporter object.
//
// Notify the compositor that the xdg_exporter object will no longer be
// used.
type ExporterV1DestroyRequest struct {
}

func (r *ExporterV1DestroyRequest) Opcode() uint16 { return ExporterV1RequestDestroy }

func (r *ExporterV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *ExporterV1DestroyRequest) Since() uint32 { return 1 }

// ExporterV1ExportRequest export a surface.
//
// The export request exports the passed surface so that it can later be
// imported via xdg_importer. When called, a new xdg_exported object will
// be created and xdg_exported.handle will be sent immediately. See the
// corresponding interface and event for details.
//
// A surface may be exported multiple times, and each exported handle may
// be used to create an xdg_imported multiple times. Only xdg_surface
// surfaces may be exported.
type ExporterV1ExportRequest struct {
	// ID the new xdg_exported object.
	ID wire.NewID
	// Surface the surface to export.
	Surface wire.ObjectID
}

func (r *ExporterV1ExportRequest) Opcode() uint16 { return ExporterV1RequestExport }

func (r *ExporterV1ExportRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Surface); err != nil {
		return err
	}
	return nil
}

func (r *ExporterV1ExportRequest) Since() uint32 { return 1 }

// ExporterV1 interface for exporting surfaces.
//
// A global interface used for exporting surfaces that can later be imported
// using xdg_importer.
type ExporterV1 struct {
	proxy *wayland.Proxy
}

// NewExporterV1 wraps p in a ExporterV1 proxy.
func NewExporterV1(p *wayland.Proxy) *ExporterV1 {
	return &ExporterV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *ExporterV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// Destroy destroy the xdg_exporter object.
//
// Notify the compositor that the xdg_exporter object will no longer be
// used.
func (o *ExporterV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(ExporterV1RequestDestroy, &ExporterV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// Export export a surface.
//
// The export request exports the passed surface so that it can later be
// imported via xdg_importer. When called, a new xdg_exported object will
// be created and xdg_exported.handle will be sent immediately. See the
// corresponding interface and event for details.
//
// A surface may be exported multiple times, and each exported handle may
// be used to create an xdg_imported multiple times. Only xdg_surface
// surfaces may be exported.
func (o *ExporterV1) Export(surface wire.ObjectID) (*ExportedV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewExportedV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), ExporterV1RequestExport, &ExporterV1ExportRequest{
		ID:      wire.NewID(p.ID()),
		Surface: surface,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// BindExporterV1 binds the zxdg_exporter_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionExporterV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindExporterV1(reg, name, min(g.Version,
// VersionExporterV1)), to bind at the highest mutually supported version.
func BindExporterV1(b wayland.Binder, name uint32, version uint32) (*ExporterV1, error) {
	if version < 1 || version > VersionExporterV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceExporterV1, version)
	if err != nil {
		return nil, err
	}
	x := NewExporterV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
