// Code generated by wayland-scanner. DO NOT EDIT.

package pointerconstraintsunstable

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceLockedPointerV1 = "zwp_locked_pointer_v1"
const VersionLockedPointerV1 = 1

const (
	LockedPointerV1RequestDestroy               uint16 = 0
	LockedPointerV1RequestSetCursorPositionHint uint16 = 1
	LockedPointerV1RequestSetRegion             uint16 = 2
)

const (
	LockedPointerV1EventLocked   uint16 = 0
	LockedPointerV1EventUnlocked uint16 = 1
)

type LockedPointerV1DestroyRequest struct {
}

func (r *LockedPointerV1DestroyRequest) Opcode() uint16 { return LockedPointerV1RequestDestroy }

func (r *LockedPointerV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *LockedPointerV1DestroyRequest) Since() int { return 1 }

type LockedPointerV1SetCursorPositionHintRequest struct {
	SurfaceX wire.Fixed
	SurfaceY wire.Fixed
}

func (r *LockedPointerV1SetCursorPositionHintRequest) Opcode() uint16 {
	return LockedPointerV1RequestSetCursorPositionHint
}

func (r *LockedPointerV1SetCursorPositionHintRequest) Marshal(w *wire.Writer) error {
	if err := w.Fixed(r.SurfaceX); err != nil {
		return err
	}
	if err := w.Fixed(r.SurfaceY); err != nil {
		return err
	}
	return nil
}

func (r *LockedPointerV1SetCursorPositionHintRequest) Since() int { return 1 }

type LockedPointerV1SetRegionRequest struct {
	Region wire.ObjectID
}

func (r *LockedPointerV1SetRegionRequest) Opcode() uint16 { return LockedPointerV1RequestSetRegion }

func (r *LockedPointerV1SetRegionRequest) Marshal(w *wire.Writer) error {
	if err := w.Object(r.Region); err != nil {
		return err
	}
	return nil
}

func (r *LockedPointerV1SetRegionRequest) Since() int { return 1 }

type LockedPointerV1LockedEvent struct {
}

func (e *LockedPointerV1LockedEvent) Opcode() uint16 { return LockedPointerV1EventLocked }

func (e *LockedPointerV1LockedEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *LockedPointerV1LockedEvent) Since() int { return 1 }

type LockedPointerV1UnlockedEvent struct {
}

func (e *LockedPointerV1UnlockedEvent) Opcode() uint16 { return LockedPointerV1EventUnlocked }

func (e *LockedPointerV1UnlockedEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *LockedPointerV1UnlockedEvent) Since() int { return 1 }

type LockedPointerV1LockedFunc func(ev LockedPointerV1LockedEvent)

type LockedPointerV1UnlockedFunc func(ev LockedPointerV1UnlockedEvent)

type LockedPointerV1 struct {
	proxy *wayland.Proxy
}

func NewLockedPointerV1(p *wayland.Proxy) *LockedPointerV1 {
	return &LockedPointerV1{proxy: p}
}

func (o *LockedPointerV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *LockedPointerV1) OnLocked(fn LockedPointerV1LockedFunc) {
	o.proxy.RegisterEvent(LockedPointerV1EventLocked, func(r *wire.Reader) {
		var ev LockedPointerV1LockedEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "Locked", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *LockedPointerV1) OnUnlocked(fn LockedPointerV1UnlockedFunc) {
	o.proxy.RegisterEvent(LockedPointerV1EventUnlocked, func(r *wire.Reader) {
		var ev LockedPointerV1UnlockedEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "Unlocked", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *LockedPointerV1) Destroy() error {
	return o.proxy.SendRequest(LockedPointerV1RequestDestroy, &LockedPointerV1DestroyRequest{})
}

func (o *LockedPointerV1) SetCursorPositionHint(surfaceX wire.Fixed, surfaceY wire.Fixed) error {
	return o.proxy.SendRequest(LockedPointerV1RequestSetCursorPositionHint, &LockedPointerV1SetCursorPositionHintRequest{
		SurfaceX: surfaceX,
		SurfaceY: surfaceY,
	})
}

func (o *LockedPointerV1) SetRegion(region wire.ObjectID) error {
	return o.proxy.SendRequest(LockedPointerV1RequestSetRegion, &LockedPointerV1SetRegionRequest{
		Region: region,
	})
}

func BindLockedPointerV1(b wayland.Binder, name uint32, version uint32) (*LockedPointerV1, error) {
	if version < 1 || version > VersionLockedPointerV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceLockedPointerV1, version)
	if err != nil {
		return nil, err
	}
	x := NewLockedPointerV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
