// Code generated by wayland-scanner. DO NOT EDIT.

package tablet

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceTabletPadV2 = "zwp_tablet_pad_v2"
const VersionTabletPadV2 = 2

const (
	TabletPadV2RequestSetFeedback uint16 = 0
	TabletPadV2RequestDestroy     uint16 = 1
)

const (
	TabletPadV2EventGroup   uint16 = 0
	TabletPadV2EventPath    uint16 = 1
	TabletPadV2EventButtons uint16 = 2
	TabletPadV2EventDone    uint16 = 3
	TabletPadV2EventButton  uint16 = 4
	TabletPadV2EventEnter   uint16 = 5
	TabletPadV2EventLeave   uint16 = 6
	TabletPadV2EventRemoved uint16 = 7
)

type TabletPadV2ButtonState uint32

const (
	TabletPadV2ButtonStateReleased TabletPadV2ButtonState = 0
	TabletPadV2ButtonStatePressed  TabletPadV2ButtonState = 1
)

type TabletPadV2SetFeedbackRequest struct {
	Button      uint32
	Description string
	Serial      uint32
}

func (r *TabletPadV2SetFeedbackRequest) Opcode() uint16 { return TabletPadV2RequestSetFeedback }

func (r *TabletPadV2SetFeedbackRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Button); err != nil {
		return err
	}
	if err := w.String(r.Description); err != nil {
		return err
	}
	if err := w.Uint32(r.Serial); err != nil {
		return err
	}
	return nil
}

func (r *TabletPadV2SetFeedbackRequest) Since() int { return 1 }

type TabletPadV2DestroyRequest struct {
}

func (r *TabletPadV2DestroyRequest) Opcode() uint16 { return TabletPadV2RequestDestroy }

func (r *TabletPadV2DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *TabletPadV2DestroyRequest) Since() int { return 1 }

type TabletPadV2GroupEvent struct {
	PadGroup wire.NewID
}

func (e *TabletPadV2GroupEvent) Opcode() uint16 { return TabletPadV2EventGroup }

func (e *TabletPadV2GroupEvent) Unmarshal(r *wire.Reader) error {
	padGroup, err := r.NewID()
	if err != nil {
		return err
	}
	e.PadGroup = padGroup
	return nil
}

func (e *TabletPadV2GroupEvent) Since() int { return 1 }

type TabletPadV2PathEvent struct {
	Path string
}

func (e *TabletPadV2PathEvent) Opcode() uint16 { return TabletPadV2EventPath }

func (e *TabletPadV2PathEvent) Unmarshal(r *wire.Reader) error {
	path, err := r.String()
	if err != nil {
		return err
	}
	e.Path = path
	return nil
}

func (e *TabletPadV2PathEvent) Since() int { return 1 }

type TabletPadV2ButtonsEvent struct {
	Buttons uint32
}

func (e *TabletPadV2ButtonsEvent) Opcode() uint16 { return TabletPadV2EventButtons }

func (e *TabletPadV2ButtonsEvent) Unmarshal(r *wire.Reader) error {
	buttons, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Buttons = buttons
	return nil
}

func (e *TabletPadV2ButtonsEvent) Since() int { return 1 }

type TabletPadV2DoneEvent struct {
}

func (e *TabletPadV2DoneEvent) Opcode() uint16 { return TabletPadV2EventDone }

func (e *TabletPadV2DoneEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *TabletPadV2DoneEvent) Since() int { return 1 }

type TabletPadV2ButtonEvent struct {
	Time   uint32
	Button uint32
	State  uint32
}

func (e *TabletPadV2ButtonEvent) Opcode() uint16 { return TabletPadV2EventButton }

func (e *TabletPadV2ButtonEvent) Unmarshal(r *wire.Reader) error {
	time, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Time = time
	button, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Button = button
	state, err := r.Uint32()
	if err != nil {
		return err
	}
	e.State = state
	return nil
}

func (e *TabletPadV2ButtonEvent) Since() int { return 1 }

type TabletPadV2EnterEvent struct {
	Serial  uint32
	Tablet  wire.ObjectID
	Surface wire.ObjectID
}

func (e *TabletPadV2EnterEvent) Opcode() uint16 { return TabletPadV2EventEnter }

func (e *TabletPadV2EnterEvent) Unmarshal(r *wire.Reader) error {
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	tablet, err := r.Object()
	if err != nil {
		return err
	}
	e.Tablet = tablet
	surface, err := r.Object()
	if err != nil {
		return err
	}
	e.Surface = surface
	return nil
}

func (e *TabletPadV2EnterEvent) Since() int { return 1 }

type TabletPadV2LeaveEvent struct {
	Serial  uint32
	Surface wire.ObjectID
}

func (e *TabletPadV2LeaveEvent) Opcode() uint16 { return TabletPadV2EventLeave }

func (e *TabletPadV2LeaveEvent) Unmarshal(r *wire.Reader) error {
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	surface, err := r.Object()
	if err != nil {
		return err
	}
	e.Surface = surface
	return nil
}

func (e *TabletPadV2LeaveEvent) Since() int { return 1 }

type TabletPadV2RemovedEvent struct {
}

func (e *TabletPadV2RemovedEvent) Opcode() uint16 { return TabletPadV2EventRemoved }

func (e *TabletPadV2RemovedEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *TabletPadV2RemovedEvent) Since() int { return 1 }

type TabletPadV2GroupFunc func(ev TabletPadV2GroupEvent)

type TabletPadV2PathFunc func(ev TabletPadV2PathEvent)

type TabletPadV2ButtonsFunc func(ev TabletPadV2ButtonsEvent)

type TabletPadV2DoneFunc func(ev TabletPadV2DoneEvent)

type TabletPadV2ButtonFunc func(ev TabletPadV2ButtonEvent)

type TabletPadV2EnterFunc func(ev TabletPadV2EnterEvent)

type TabletPadV2LeaveFunc func(ev TabletPadV2LeaveEvent)

type TabletPadV2RemovedFunc func(ev TabletPadV2RemovedEvent)

type TabletPadV2 struct {
	proxy *wayland.Proxy
}

func NewTabletPadV2(p *wayland.Proxy) *TabletPadV2 {
	return &TabletPadV2{proxy: p}
}

func (o *TabletPadV2) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *TabletPadV2) OnGroup(fn TabletPadV2GroupFunc) {
	o.proxy.RegisterEvent(TabletPadV2EventGroup, func(r *wire.Reader) {
		var ev TabletPadV2GroupEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadV2) OnPath(fn TabletPadV2PathFunc) {
	o.proxy.RegisterEvent(TabletPadV2EventPath, func(r *wire.Reader) {
		var ev TabletPadV2PathEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadV2) OnButtons(fn TabletPadV2ButtonsFunc) {
	o.proxy.RegisterEvent(TabletPadV2EventButtons, func(r *wire.Reader) {
		var ev TabletPadV2ButtonsEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadV2) OnDone(fn TabletPadV2DoneFunc) {
	o.proxy.RegisterEvent(TabletPadV2EventDone, func(r *wire.Reader) {
		var ev TabletPadV2DoneEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadV2) OnButton(fn TabletPadV2ButtonFunc) {
	o.proxy.RegisterEvent(TabletPadV2EventButton, func(r *wire.Reader) {
		var ev TabletPadV2ButtonEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadV2) OnEnter(fn TabletPadV2EnterFunc) {
	o.proxy.RegisterEvent(TabletPadV2EventEnter, func(r *wire.Reader) {
		var ev TabletPadV2EnterEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadV2) OnLeave(fn TabletPadV2LeaveFunc) {
	o.proxy.RegisterEvent(TabletPadV2EventLeave, func(r *wire.Reader) {
		var ev TabletPadV2LeaveEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadV2) OnRemoved(fn TabletPadV2RemovedFunc) {
	o.proxy.RegisterEvent(TabletPadV2EventRemoved, func(r *wire.Reader) {
		var ev TabletPadV2RemovedEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *TabletPadV2) SetFeedback(button uint32, description string, serial uint32) error {
	return o.proxy.SendRequest(TabletPadV2RequestSetFeedback, &TabletPadV2SetFeedbackRequest{
		Button:      button,
		Description: description,
		Serial:      serial,
	})
}

func (o *TabletPadV2) Destroy() error {
	return o.proxy.SendRequest(TabletPadV2RequestDestroy, &TabletPadV2DestroyRequest{})
}

func BindTabletPadV2(b wayland.Binder, name uint32, version uint32) (*TabletPadV2, error) {
	if version < 1 || version > VersionTabletPadV2 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceTabletPadV2, version)
	if err != nil {
		return nil, err
	}
	x := NewTabletPadV2(p)
	x.proxy.SetVersion(version)
	return x, nil
}
