// Code generated by wayland-scanner. DO NOT EDIT.

package xdgshell

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfacePositioner = "xdg_positioner"
const VersionPositioner = 7

const (
	PositionerRequestDestroy                 uint16 = 0
	PositionerRequestSetSize                 uint16 = 1
	PositionerRequestSetAnchorRect           uint16 = 2
	PositionerRequestSetAnchor               uint16 = 3
	PositionerRequestSetGravity              uint16 = 4
	PositionerRequestSetConstraintAdjustment uint16 = 5
	PositionerRequestSetOffset               uint16 = 6
	PositionerRequestSetReactive             uint16 = 7
	PositionerRequestSetParentSize           uint16 = 8
	PositionerRequestSetParentConfigure      uint16 = 9
)

type PositionerError uint32

const (
	PositionerErrorInvalidInput PositionerError = 0
)

type PositionerAnchor uint32

const (
	PositionerAnchorNone        PositionerAnchor = 0
	PositionerAnchorTop         PositionerAnchor = 1
	PositionerAnchorBottom      PositionerAnchor = 2
	PositionerAnchorLeft        PositionerAnchor = 3
	PositionerAnchorRight       PositionerAnchor = 4
	PositionerAnchorTopLeft     PositionerAnchor = 5
	PositionerAnchorBottomLeft  PositionerAnchor = 6
	PositionerAnchorTopRight    PositionerAnchor = 7
	PositionerAnchorBottomRight PositionerAnchor = 8
)

type PositionerGravity uint32

const (
	PositionerGravityNone        PositionerGravity = 0
	PositionerGravityTop         PositionerGravity = 1
	PositionerGravityBottom      PositionerGravity = 2
	PositionerGravityLeft        PositionerGravity = 3
	PositionerGravityRight       PositionerGravity = 4
	PositionerGravityTopLeft     PositionerGravity = 5
	PositionerGravityBottomLeft  PositionerGravity = 6
	PositionerGravityTopRight    PositionerGravity = 7
	PositionerGravityBottomRight PositionerGravity = 8
)

type PositionerConstraintAdjustment uint32

const (
	PositionerConstraintAdjustmentNone    PositionerConstraintAdjustment = 0
	PositionerConstraintAdjustmentSlideX  PositionerConstraintAdjustment = 1
	PositionerConstraintAdjustmentSlideY  PositionerConstraintAdjustment = 2
	PositionerConstraintAdjustmentFlipX   PositionerConstraintAdjustment = 4
	PositionerConstraintAdjustmentFlipY   PositionerConstraintAdjustment = 8
	PositionerConstraintAdjustmentResizeX PositionerConstraintAdjustment = 16
	PositionerConstraintAdjustmentResizeY PositionerConstraintAdjustment = 32
)

type PositionerDestroyRequest struct {
}

func (r *PositionerDestroyRequest) Opcode() uint16 { return PositionerRequestDestroy }

func (r *PositionerDestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *PositionerDestroyRequest) Since() int { return 1 }

type PositionerSetSizeRequest struct {
	Width  int32
	Height int32
}

func (r *PositionerSetSizeRequest) Opcode() uint16 { return PositionerRequestSetSize }

func (r *PositionerSetSizeRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.Width); err != nil {
		return err
	}
	if err := w.Int32(r.Height); err != nil {
		return err
	}
	return nil
}

func (r *PositionerSetSizeRequest) Since() int { return 1 }

type PositionerSetAnchorRectRequest struct {
	X      int32
	Y      int32
	Width  int32
	Height int32
}

func (r *PositionerSetAnchorRectRequest) Opcode() uint16 { return PositionerRequestSetAnchorRect }

func (r *PositionerSetAnchorRectRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.X); err != nil {
		return err
	}
	if err := w.Int32(r.Y); err != nil {
		return err
	}
	if err := w.Int32(r.Width); err != nil {
		return err
	}
	if err := w.Int32(r.Height); err != nil {
		return err
	}
	return nil
}

func (r *PositionerSetAnchorRectRequest) Since() int { return 1 }

type PositionerSetAnchorRequest struct {
	Anchor uint32
}

func (r *PositionerSetAnchorRequest) Opcode() uint16 { return PositionerRequestSetAnchor }

func (r *PositionerSetAnchorRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Anchor); err != nil {
		return err
	}
	return nil
}

func (r *PositionerSetAnchorRequest) Since() int { return 1 }

type PositionerSetGravityRequest struct {
	Gravity uint32
}

func (r *PositionerSetGravityRequest) Opcode() uint16 { return PositionerRequestSetGravity }

func (r *PositionerSetGravityRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Gravity); err != nil {
		return err
	}
	return nil
}

func (r *PositionerSetGravityRequest) Since() int { return 1 }

type PositionerSetConstraintAdjustmentRequest struct {
	ConstraintAdjustment uint32
}

func (r *PositionerSetConstraintAdjustmentRequest) Opcode() uint16 {
	return PositionerRequestSetConstraintAdjustment
}

func (r *PositionerSetConstraintAdjustmentRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.ConstraintAdjustment); err != nil {
		return err
	}
	return nil
}

func (r *PositionerSetConstraintAdjustmentRequest) Since() int { return 1 }

type PositionerSetOffsetRequest struct {
	X int32
	Y int32
}

func (r *PositionerSetOffsetRequest) Opcode() uint16 { return PositionerRequestSetOffset }

func (r *PositionerSetOffsetRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.X); err != nil {
		return err
	}
	if err := w.Int32(r.Y); err != nil {
		return err
	}
	return nil
}

func (r *PositionerSetOffsetRequest) Since() int { return 1 }

type PositionerSetReactiveRequest struct {
}

func (r *PositionerSetReactiveRequest) Opcode() uint16 { return PositionerRequestSetReactive }

func (r *PositionerSetReactiveRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *PositionerSetReactiveRequest) Since() int { return 3 }

type PositionerSetParentSizeRequest struct {
	ParentWidth  int32
	ParentHeight int32
}

func (r *PositionerSetParentSizeRequest) Opcode() uint16 { return PositionerRequestSetParentSize }

func (r *PositionerSetParentSizeRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.ParentWidth); err != nil {
		return err
	}
	if err := w.Int32(r.ParentHeight); err != nil {
		return err
	}
	return nil
}

func (r *PositionerSetParentSizeRequest) Since() int { return 3 }

type PositionerSetParentConfigureRequest struct {
	Serial uint32
}

func (r *PositionerSetParentConfigureRequest) Opcode() uint16 {
	return PositionerRequestSetParentConfigure
}

func (r *PositionerSetParentConfigureRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Serial); err != nil {
		return err
	}
	return nil
}

func (r *PositionerSetParentConfigureRequest) Since() int { return 3 }

type Positioner struct {
	proxy *wayland.Proxy
}

func NewPositioner(p *wayland.Proxy) *Positioner {
	return &Positioner{proxy: p}
}

func (o *Positioner) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *Positioner) Destroy() error {
	return o.proxy.SendRequest(PositionerRequestDestroy, &PositionerDestroyRequest{})
}

func (o *Positioner) SetSize(width int32, height int32) error {
	return o.proxy.SendRequest(PositionerRequestSetSize, &PositionerSetSizeRequest{
		Width:  width,
		Height: height,
	})
}

func (o *Positioner) SetAnchorRect(x int32, y int32, width int32, height int32) error {
	return o.proxy.SendRequest(PositionerRequestSetAnchorRect, &PositionerSetAnchorRectRequest{
		X:      x,
		Y:      y,
		Width:  width,
		Height: height,
	})
}

func (o *Positioner) SetAnchor(anchor uint32) error {
	return o.proxy.SendRequest(PositionerRequestSetAnchor, &PositionerSetAnchorRequest{
		Anchor: anchor,
	})
}

func (o *Positioner) SetGravity(gravity uint32) error {
	return o.proxy.SendRequest(PositionerRequestSetGravity, &PositionerSetGravityRequest{
		Gravity: gravity,
	})
}

func (o *Positioner) SetConstraintAdjustment(constraintAdjustment uint32) error {
	return o.proxy.SendRequest(PositionerRequestSetConstraintAdjustment, &PositionerSetConstraintAdjustmentRequest{
		ConstraintAdjustment: constraintAdjustment,
	})
}

func (o *Positioner) SetOffset(x int32, y int32) error {
	return o.proxy.SendRequest(PositionerRequestSetOffset, &PositionerSetOffsetRequest{
		X: x,
		Y: y,
	})
}

func (o *Positioner) SetReactive() error {
	return o.proxy.SendRequest(PositionerRequestSetReactive, &PositionerSetReactiveRequest{})
}

func (o *Positioner) SetParentSize(parentWidth int32, parentHeight int32) error {
	return o.proxy.SendRequest(PositionerRequestSetParentSize, &PositionerSetParentSizeRequest{
		ParentWidth:  parentWidth,
		ParentHeight: parentHeight,
	})
}

func (o *Positioner) SetParentConfigure(serial uint32) error {
	return o.proxy.SendRequest(PositionerRequestSetParentConfigure, &PositionerSetParentConfigureRequest{
		Serial: serial,
	})
}

func BindPositioner(b wayland.Binder, name uint32, version uint32) (*Positioner, error) {
	if version < 1 || version > VersionPositioner {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfacePositioner, version)
	if err != nil {
		return nil, err
	}
	x := NewPositioner(p)
	x.proxy.SetVersion(version)
	return x, nil
}
