// Code generated by wayland-scanner. DO NOT EDIT.

package xdgshell

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceSurface = "xdg_surface"
const VersionSurface = 7

const (
	SurfaceRequestDestroy           uint16 = 0
	SurfaceRequestGetToplevel       uint16 = 1
	SurfaceRequestGetPopup          uint16 = 2
	SurfaceRequestSetWindowGeometry uint16 = 3
	SurfaceRequestAckConfigure      uint16 = 4
)

const (
	SurfaceEventConfigure uint16 = 0
)

type SurfaceError uint32

const (
	SurfaceErrorNotConstructed     SurfaceError = 1
	SurfaceErrorAlreadyConstructed SurfaceError = 2
	SurfaceErrorUnconfiguredBuffer SurfaceError = 3
	SurfaceErrorInvalidSerial      SurfaceError = 4
	SurfaceErrorInvalidSize        SurfaceError = 5
	SurfaceErrorDefunctRoleObject  SurfaceError = 6
)

type SurfaceDestroyRequest struct {
}

func (r *SurfaceDestroyRequest) Opcode() uint16 { return SurfaceRequestDestroy }

func (r *SurfaceDestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SurfaceDestroyRequest) Since() int { return 1 }

type SurfaceGetToplevelRequest struct {
	ID wire.NewID
}

func (r *SurfaceGetToplevelRequest) Opcode() uint16 { return SurfaceRequestGetToplevel }

func (r *SurfaceGetToplevelRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceGetToplevelRequest) Since() int { return 1 }

type SurfaceGetPopupRequest struct {
	ID         wire.NewID
	Parent     wire.ObjectID
	Positioner wire.ObjectID
}

func (r *SurfaceGetPopupRequest) Opcode() uint16 { return SurfaceRequestGetPopup }

func (r *SurfaceGetPopupRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Parent); err != nil {
		return err
	}
	if err := w.Object(r.Positioner); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceGetPopupRequest) Since() int { return 1 }

type SurfaceSetWindowGeometryRequest struct {
	X      int32
	Y      int32
	Width  int32
	Height int32
}

func (r *SurfaceSetWindowGeometryRequest) Opcode() uint16 { return SurfaceRequestSetWindowGeometry }

func (r *SurfaceSetWindowGeometryRequest) Marshal(w *wire.Writer) error {
	if err := w.Int32(r.X); err != nil {
		return err
	}
	if err := w.Int32(r.Y); err != nil {
		return err
	}
	if err := w.Int32(r.Width); err != nil {
		return err
	}
	if err := w.Int32(r.Height); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceSetWindowGeometryRequest) Since() int { return 1 }

type SurfaceAckConfigureRequest struct {
	Serial uint32
}

func (r *SurfaceAckConfigureRequest) Opcode() uint16 { return SurfaceRequestAckConfigure }

func (r *SurfaceAckConfigureRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Serial); err != nil {
		return err
	}
	return nil
}

func (r *SurfaceAckConfigureRequest) Since() int { return 1 }

type SurfaceConfigureEvent struct {
	Serial uint32
}

func (e *SurfaceConfigureEvent) Opcode() uint16 { return SurfaceEventConfigure }

func (e *SurfaceConfigureEvent) Unmarshal(r *wire.Reader) error {
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	return nil
}

func (e *SurfaceConfigureEvent) Since() int { return 1 }

type SurfaceConfigureFunc func(ev SurfaceConfigureEvent)

type Surface struct {
	proxy *wayland.Proxy
}

func NewSurface(p *wayland.Proxy) *Surface {
	return &Surface{proxy: p}
}

func (o *Surface) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *Surface) OnConfigure(fn SurfaceConfigureFunc) {
	o.proxy.RegisterEvent(SurfaceEventConfigure, func(r *wire.Reader) {
		var ev SurfaceConfigureEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "Configure", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *Surface) Destroy() error {
	return o.proxy.SendRequest(SurfaceRequestDestroy, &SurfaceDestroyRequest{})
}

func (o *Surface) GetToplevel() (*Toplevel, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewToplevel(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), SurfaceRequestGetToplevel, &SurfaceGetToplevelRequest{
		ID: wire.NewID(p.ID()),
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func (o *Surface) GetPopup(parent wire.ObjectID, positioner wire.ObjectID) (*Popup, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewPopup(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), SurfaceRequestGetPopup, &SurfaceGetPopupRequest{
		ID:         wire.NewID(p.ID()),
		Parent:     parent,
		Positioner: positioner,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func (o *Surface) SetWindowGeometry(x int32, y int32, width int32, height int32) error {
	return o.proxy.SendRequest(SurfaceRequestSetWindowGeometry, &SurfaceSetWindowGeometryRequest{
		X:      x,
		Y:      y,
		Width:  width,
		Height: height,
	})
}

func (o *Surface) AckConfigure(serial uint32) error {
	return o.proxy.SendRequest(SurfaceRequestAckConfigure, &SurfaceAckConfigureRequest{
		Serial: serial,
	})
}

func BindSurface(b wayland.Binder, name uint32, version uint32) (*Surface, error) {
	if version < 1 || version > VersionSurface {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceSurface, version)
	if err != nil {
		return nil, err
	}
	x := NewSurface(p)
	x.proxy.SetVersion(version)
	return x, nil
}
