// Code generated by wayland-scanner. DO NOT EDIT.

package xdgshell

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceWmBase = "xdg_wm_base"
const VersionWmBase = 7

const (
	WmBaseRequestDestroy          uint16 = 0
	WmBaseRequestCreatePositioner uint16 = 1
	WmBaseRequestGetXdgSurface    uint16 = 2
	WmBaseRequestPong             uint16 = 3
)

const (
	WmBaseEventPing uint16 = 0
)

type WmBaseError uint32

const (
	WmBaseErrorRole                WmBaseError = 0
	WmBaseErrorDefunctSurfaces     WmBaseError = 1
	WmBaseErrorNotTheTopmostPopup  WmBaseError = 2
	WmBaseErrorInvalidPopupParent  WmBaseError = 3
	WmBaseErrorInvalidSurfaceState WmBaseError = 4
	WmBaseErrorInvalidPositioner   WmBaseError = 5
	WmBaseErrorUnresponsive        WmBaseError = 6
)

type WmBaseDestroyRequest struct {
}

func (r *WmBaseDestroyRequest) Opcode() uint16 { return WmBaseRequestDestroy }

func (r *WmBaseDestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *WmBaseDestroyRequest) Since() int { return 1 }

type WmBaseCreatePositionerRequest struct {
	ID wire.NewID
}

func (r *WmBaseCreatePositionerRequest) Opcode() uint16 { return WmBaseRequestCreatePositioner }

func (r *WmBaseCreatePositionerRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	return nil
}

func (r *WmBaseCreatePositionerRequest) Since() int { return 1 }

type WmBaseGetXdgSurfaceRequest struct {
	ID      wire.NewID
	Surface wire.ObjectID
}

func (r *WmBaseGetXdgSurfaceRequest) Opcode() uint16 { return WmBaseRequestGetXdgSurface }

func (r *WmBaseGetXdgSurfaceRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Surface); err != nil {
		return err
	}
	return nil
}

func (r *WmBaseGetXdgSurfaceRequest) Since() int { return 1 }

type WmBasePongRequest struct {
	Serial uint32
}

func (r *WmBasePongRequest) Opcode() uint16 { return WmBaseRequestPong }

func (r *WmBasePongRequest) Marshal(w *wire.Writer) error {
	if err := w.Uint32(r.Serial); err != nil {
		return err
	}
	return nil
}

func (r *WmBasePongRequest) Since() int { return 1 }

type WmBasePingEvent struct {
	Serial uint32
}

func (e *WmBasePingEvent) Opcode() uint16 { return WmBaseEventPing }

func (e *WmBasePingEvent) Unmarshal(r *wire.Reader) error {
	serial, err := r.Uint32()
	if err != nil {
		return err
	}
	e.Serial = serial
	return nil
}

func (e *WmBasePingEvent) Since() int { return 1 }

type WmBasePingFunc func(ev WmBasePingEvent)

type WmBase struct {
	proxy *wayland.Proxy
}

func NewWmBase(p *wayland.Proxy) *WmBase {
	return &WmBase{proxy: p}
}

func (o *WmBase) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *WmBase) OnPing(fn WmBasePingFunc) {
	o.proxy.RegisterEvent(WmBaseEventPing, func(r *wire.Reader) {
		var ev WmBasePingEvent
		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().Logger().Warn("event unmarshal error", "event", "Ping", "error", err)
			return
		}
		fn(ev)
	})
}

func (o *WmBase) Destroy() error {
	return o.proxy.SendRequest(WmBaseRequestDestroy, &WmBaseDestroyRequest{})
}

func (o *WmBase) CreatePositioner() (*Positioner, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewPositioner(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), WmBaseRequestCreatePositioner, &WmBaseCreatePositionerRequest{
		ID: wire.NewID(p.ID()),
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func (o *WmBase) GetXdgSurface(surface wire.ObjectID) (*Surface, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewSurface(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), WmBaseRequestGetXdgSurface, &WmBaseGetXdgSurfaceRequest{
		ID:      wire.NewID(p.ID()),
		Surface: surface,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func (o *WmBase) Pong(serial uint32) error {
	return o.proxy.SendRequest(WmBaseRequestPong, &WmBasePongRequest{
		Serial: serial,
	})
}

func BindWmBase(b wayland.Binder, name uint32, version uint32) (*WmBase, error) {
	if version < 1 || version > VersionWmBase {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceWmBase, version)
	if err != nil {
		return nil, err
	}
	x := NewWmBase(p)
	x.proxy.SetVersion(version)
	return x, nil
}
