// Code generated by wayland-scanner. DO NOT EDIT.

package xxsessionmanagement

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceSessionV1 = "xx_session_v1"
const VersionSessionV1 = 1

const (
	SessionV1RequestDestroy         uint16 = 0
	SessionV1RequestRemove          uint16 = 1
	SessionV1RequestAddToplevel     uint16 = 2
	SessionV1RequestRestoreToplevel uint16 = 3
)

const (
	SessionV1EventCreated  uint16 = 0
	SessionV1EventRestored uint16 = 1
	SessionV1EventReplaced uint16 = 2
)

// sessionv1EventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var sessionv1EventFDCounts = map[uint16]int{
	0: 0,
	1: 0,
	2: 0,
}

func init() {
	wayland.RegisterInterfaceFDCounts(InterfaceSessionV1, sessionv1EventFDCounts)
}

type SessionV1Error uint32

const (
	// SessionV1ErrorInvalidRestore restore cannot be performed after initial toplevel commit.
	SessionV1ErrorInvalidRestore SessionV1Error = 1

	// SessionV1ErrorNameInUse toplevel name is already in used.
	SessionV1ErrorNameInUse SessionV1Error = 2

	// SessionV1ErrorAlreadyMapped toplevel was already mapped when restored.
	SessionV1ErrorAlreadyMapped SessionV1Error = 3
)

// SessionV1DestroyRequest destroy the session.
//
// Destroy a session object, preserving the current state but not continuing
// to make further updates if state changes occur. This makes the associated
// xx_toplevel_session_v1 objects inert.
type SessionV1DestroyRequest struct {
}

func (r *SessionV1DestroyRequest) Opcode() uint16 { return SessionV1RequestDestroy }

func (r *SessionV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SessionV1DestroyRequest) Since() uint32 { return 1 }

// SessionV1RemoveRequest remove the session.
//
// Remove the session, making it no longer available for restoration. A
// compositor should in response to this request remove the data related to
// this session from its storage.
type SessionV1RemoveRequest struct {
}

func (r *SessionV1RemoveRequest) Opcode() uint16 { return SessionV1RequestRemove }

func (r *SessionV1RemoveRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *SessionV1RemoveRequest) Since() uint32 { return 1 }

// SessionV1AddToplevelRequest add a new surface to the session.
//
// Attempt to add a given surface to the session. The passed name is used
// to identify what window is being restored, and may be used store window
// specific state within the session.
//
// Calling this with a toplevel that is already managed by the session with
// the same associated will raise an in_use error.
type SessionV1AddToplevelRequest struct {
	ID       wire.NewID
	Toplevel wire.ObjectID
	Name     string
}

func (r *SessionV1AddToplevelRequest) Opcode() uint16 { return SessionV1RequestAddToplevel }

func (r *SessionV1AddToplevelRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Toplevel); err != nil {
		return err
	}
	if err := w.String(r.Name); err != nil {
		return err
	}
	return nil
}

func (r *SessionV1AddToplevelRequest) Since() uint32 { return 1 }

// SessionV1RestoreToplevelRequest restore a surface state.
//
// Inform the compositor that the toplevel associated with the passed name
// should have its window management state restored.
//
// Calling this with a toplevel that is already managed by the session with
// the same associated will raise an in_use error.
//
// This request must be called prior to the first commit on the associated
// wl_surface, otherwise an already_mapped error is raised.
//
// As part of the initial configure sequence, if the toplevel was
// successfully restored, a xx_toplevel_session_v1.restored event is
// emitted. See the xx_toplevel_session_v1.restored event for further
// details.
type SessionV1RestoreToplevelRequest struct {
	ID       wire.NewID
	Toplevel wire.ObjectID
	Name     string
}

func (r *SessionV1RestoreToplevelRequest) Opcode() uint16 { return SessionV1RequestRestoreToplevel }

func (r *SessionV1RestoreToplevelRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Toplevel); err != nil {
		return err
	}
	if err := w.String(r.Name); err != nil {
		return err
	}
	return nil
}

func (r *SessionV1RestoreToplevelRequest) Since() uint32 { return 1 }

// SessionV1CreatedEvent newly-created session id.
//
// Emitted at most once some time after getting a new session object. It
// means that no previous state was restored, and a new session was created.
// The passed id can be used to restore previous sessions.
type SessionV1CreatedEvent struct {
	ID string
}

func (e *SessionV1CreatedEvent) Opcode() uint16 { return SessionV1EventCreated }

func (e *SessionV1CreatedEvent) Unmarshal(r *wire.Reader) error {
	id, err := r.String()
	if err != nil {
		return err
	}
	e.ID = id
	return nil
}

func (e *SessionV1CreatedEvent) Since() uint32 { return 1 }

// SessionV1RestoredEvent the session has been restored.
//
// Emitted at most once some time after getting a new session object. It
// means that previous state was at least partially restored. The same id
// can again be used to restore previous sessions.
type SessionV1RestoredEvent struct {
}

func (e *SessionV1RestoredEvent) Opcode() uint16 { return SessionV1EventRestored }

func (e *SessionV1RestoredEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *SessionV1RestoredEvent) Since() uint32 { return 1 }

// SessionV1ReplacedEvent the session has been restored.
//
// Emitted at most once, if the session was taken over by some other
// client. When this happens, the session and all its toplevel session
// objects become inert, and should be destroyed.
type SessionV1ReplacedEvent struct {
}

func (e *SessionV1ReplacedEvent) Opcode() uint16 { return SessionV1EventReplaced }

func (e *SessionV1ReplacedEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *SessionV1ReplacedEvent) Since() uint32 { return 1 }

// SessionV1CreatedFunc is a callback for Created events.
type SessionV1CreatedFunc func(ev SessionV1CreatedEvent)

// SessionV1RestoredFunc is a callback for Restored events.
type SessionV1RestoredFunc func(ev SessionV1RestoredEvent)

// SessionV1ReplacedFunc is a callback for Replaced events.
type SessionV1ReplacedFunc func(ev SessionV1ReplacedEvent)

// SessionV1 a session for an application.
//
// A xx_session_v1 object represents a session for an application. While the
// object exists, all surfaces which have been added to the session will
// have states stored by the compositor which can be reapplied at a later
// time. Two sessions cannot exist for the same identifier string.
//
// States for surfaces added to a session are automatically updated by the
// compositor when they are changed.
//
// Surfaces which have been added to a session are automatically removed from
// the session if xdg_toplevel.destroy is called for the surface.
type SessionV1 struct {
	proxy *wayland.Proxy
}

// NewSessionV1 wraps p in a SessionV1 proxy.
func NewSessionV1(p *wayland.Proxy) *SessionV1 {
	p.SetEventFDCounts(sessionv1EventFDCounts)
	return &SessionV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *SessionV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// OnCreated registers fn to receive Created events.
func (o *SessionV1) OnCreated(fn SessionV1CreatedFunc) {
	o.proxy.RegisterEvent(SessionV1EventCreated, func(r *wire.Reader) {
		var ev SessionV1CreatedEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Created", err)
			return
		}

		fn(ev)
	})
}

// OnRestored registers fn to receive Restored events.
func (o *SessionV1) OnRestored(fn SessionV1RestoredFunc) {
	o.proxy.RegisterEvent(SessionV1EventRestored, func(r *wire.Reader) {
		var ev SessionV1RestoredEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Restored", err)
			return
		}

		fn(ev)
	})
}

// OnReplaced registers fn to receive Replaced events.
func (o *SessionV1) OnReplaced(fn SessionV1ReplacedFunc) {
	o.proxy.RegisterEvent(SessionV1EventReplaced, func(r *wire.Reader) {
		var ev SessionV1ReplacedEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Replaced", err)
			return
		}

		fn(ev)
	})
}

// Destroy destroy the session.
//
// Destroy a session object, preserving the current state but not continuing
// to make further updates if state changes occur. This makes the associated
// xx_toplevel_session_v1 objects inert.
func (o *SessionV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(SessionV1RequestDestroy, &SessionV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// Remove remove the session.
//
// Remove the session, making it no longer available for restoration. A
// compositor should in response to this request remove the data related to
// this session from its storage.
func (o *SessionV1) Remove() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(SessionV1RequestRemove, &SessionV1RemoveRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// AddToplevel add a new surface to the session.
//
// Attempt to add a given surface to the session. The passed name is used
// to identify what window is being restored, and may be used store window
// specific state within the session.
//
// Calling this with a toplevel that is already managed by the session with
// the same associated will raise an in_use error.
func (o *SessionV1) AddToplevel(toplevel wire.ObjectID, name string) (*ToplevelSessionV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewToplevelSessionV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), SessionV1RequestAddToplevel, &SessionV1AddToplevelRequest{
		ID:       wire.NewID(p.ID()),
		Toplevel: toplevel,
		Name:     name,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// RestoreToplevel restore a surface state.
//
// Inform the compositor that the toplevel associated with the passed name
// should have its window management state restored.
//
// Calling this with a toplevel that is already managed by the session with
// the same associated will raise an in_use error.
//
// This request must be called prior to the first commit on the associated
// wl_surface, otherwise an already_mapped error is raised.
//
// As part of the initial configure sequence, if the toplevel was
// successfully restored, a xx_toplevel_session_v1.restored event is
// emitted. See the xx_toplevel_session_v1.restored event for further
// details.
func (o *SessionV1) RestoreToplevel(toplevel wire.ObjectID, name string) (*ToplevelSessionV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewToplevelSessionV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), SessionV1RequestRestoreToplevel, &SessionV1RestoreToplevelRequest{
		ID:       wire.NewID(p.ID()),
		Toplevel: toplevel,
		Name:     name,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// BindSessionV1 binds the xx_session_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionSessionV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindSessionV1(reg, name, min(g.Version,
// VersionSessionV1)), to bind at the highest mutually supported version.
func BindSessionV1(b wayland.Binder, name uint32, version uint32) (*SessionV1, error) {
	if version < 1 || version > VersionSessionV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceSessionV1, version)
	if err != nil {
		return nil, err
	}
	x := NewSessionV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
