// Code generated by wayland-scanner. DO NOT EDIT.

package xwaylandshell

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceShellV1 = "xwayland_shell_v1"
const VersionShellV1 = 1

const (
	ShellV1RequestDestroy            uint16 = 0
	ShellV1RequestGetXwaylandSurface uint16 = 1
)

type ShellV1Error uint32

const (
	ShellV1ErrorRole ShellV1Error = 0
)

type ShellV1DestroyRequest struct {
}

func (r *ShellV1DestroyRequest) Opcode() uint16 { return ShellV1RequestDestroy }

func (r *ShellV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *ShellV1DestroyRequest) Since() int { return 1 }

type ShellV1GetXwaylandSurfaceRequest struct {
	ID      wire.NewID
	Surface wire.ObjectID
}

func (r *ShellV1GetXwaylandSurfaceRequest) Opcode() uint16 { return ShellV1RequestGetXwaylandSurface }

func (r *ShellV1GetXwaylandSurfaceRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Surface); err != nil {
		return err
	}
	return nil
}

func (r *ShellV1GetXwaylandSurfaceRequest) Since() int { return 1 }

type ShellV1 struct {
	proxy *wayland.Proxy
}

func NewShellV1(p *wayland.Proxy) *ShellV1 {
	return &ShellV1{proxy: p}
}

func (o *ShellV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *ShellV1) Destroy() error {
	return o.proxy.SendRequest(ShellV1RequestDestroy, &ShellV1DestroyRequest{})
}

func (o *ShellV1) GetXwaylandSurface(surface wire.ObjectID) (*SurfaceV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())
	wrapped := NewSurfaceV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), ShellV1RequestGetXwaylandSurface, &ShellV1GetXwaylandSurfaceRequest{
		ID:      wire.NewID(p.ID()),
		Surface: surface,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

func BindShellV1(b wayland.Binder, name uint32, version uint32) (*ShellV1, error) {
	if version < 1 || version > VersionShellV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceShellV1, version)
	if err != nil {
		return nil, err
	}
	x := NewShellV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
