// Code generated by wayland-scanner. DO NOT EDIT.

package contenttype

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceContentTypeManagerV1 = "wp_content_type_manager_v1"
const VersionContentTypeManagerV1 = 1

const (
	ContentTypeManagerV1RequestDestroy               uint16 = 0
	ContentTypeManagerV1RequestGetSurfaceContentType uint16 = 1
)

type ContentTypeManagerV1Error uint32

const (
	// ContentTypeManagerV1ErrorAlreadyConstructed wl_surface already has a content type object.
	ContentTypeManagerV1ErrorAlreadyConstructed ContentTypeManagerV1Error = 0
)

// ContentTypeManagerV1DestroyRequest destroy the content type manager object.
//
// Destroy the content type manager. This doesn't destroy objects created
// with the manager.
type ContentTypeManagerV1DestroyRequest struct {
}

func (r *ContentTypeManagerV1DestroyRequest) Opcode() uint16 {
	return ContentTypeManagerV1RequestDestroy
}

func (r *ContentTypeManagerV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *ContentTypeManagerV1DestroyRequest) Since() uint32 { return 1 }

// ContentTypeManagerV1GetSurfaceContentTypeRequest create a new content type object.
//
// Create a new content type object associated with the given surface.
//
// Creating a wp_content_type_v1 from a wl_surface which already has one
// attached is a client error: already_constructed.
type ContentTypeManagerV1GetSurfaceContentTypeRequest struct {
	ID      wire.NewID
	Surface wire.ObjectID
}

func (r *ContentTypeManagerV1GetSurfaceContentTypeRequest) Opcode() uint16 {
	return ContentTypeManagerV1RequestGetSurfaceContentType
}

func (r *ContentTypeManagerV1GetSurfaceContentTypeRequest) Marshal(w *wire.Writer) error {
	if err := w.NewID(r.ID); err != nil {
		return err
	}
	if err := w.Object(r.Surface); err != nil {
		return err
	}
	return nil
}

func (r *ContentTypeManagerV1GetSurfaceContentTypeRequest) Since() uint32 { return 1 }

// ContentTypeManagerV1 surface content type manager.
//
// This interface allows a client to describe the kind of content a surface
// will display, to allow the compositor to optimize its behavior for it.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type ContentTypeManagerV1 struct {
	proxy *wayland.Proxy
}

// NewContentTypeManagerV1 wraps p in a ContentTypeManagerV1 proxy.
func NewContentTypeManagerV1(p *wayland.Proxy) *ContentTypeManagerV1 {
	return &ContentTypeManagerV1{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *ContentTypeManagerV1) Proxy() *wayland.Proxy {
	return o.proxy
}

// Destroy destroy the content type manager object.
//
// Destroy the content type manager. This doesn't destroy objects created
// with the manager.
func (o *ContentTypeManagerV1) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(ContentTypeManagerV1RequestDestroy, &ContentTypeManagerV1DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// GetSurfaceContentType create a new content type object.
//
// Create a new content type object associated with the given surface.
//
// Creating a wp_content_type_v1 from a wl_surface which already has one
// attached is a client error: already_constructed.
func (o *ContentTypeManagerV1) GetSurfaceContentType(surface wire.ObjectID) (*ContentTypeV1, error) {
	conn := o.proxy.Conn()
	p := wayland.NewProxy(conn)
	p.SetVersion(o.proxy.Version())

	wrapped := NewContentTypeV1(p)
	conn.RegisterProxy(p)
	err := conn.SendRequest(o.proxy.ID(), ContentTypeManagerV1RequestGetSurfaceContentType, &ContentTypeManagerV1GetSurfaceContentTypeRequest{
		ID:      wire.NewID(p.ID()),
		Surface: surface,
	})
	if err != nil {
		conn.UnregisterProxy(p.ID())
		return nil, err
	}
	return wrapped, nil
}

// BindContentTypeManagerV1 binds the wp_content_type_manager_v1 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionContentTypeManagerV1] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindContentTypeManagerV1(reg, name, min(g.Version,
// VersionContentTypeManagerV1)), to bind at the highest mutually supported version.
func BindContentTypeManagerV1(b wayland.Binder, name uint32, version uint32) (*ContentTypeManagerV1, error) {
	if version < 1 || version > VersionContentTypeManagerV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceContentTypeManagerV1, version)
	if err != nil {
		return nil, err
	}
	x := NewContentTypeManagerV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
