// Code generated by wayland-scanner. DO NOT EDIT.

package xdgforeignunstablev2

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceExportedV2 = "zxdg_exported_v2"
const VersionExportedV2 = 1

const (
	ExportedV2RequestDestroy uint16 = 0
)

const (
	ExportedV2EventHandle uint16 = 0
)

// exportedv2EventFDCounts maps every event opcode of this interface
// to the number of fds it carries (0 for events without fds). Dispatch uses it
// to drain fds and to reject unknown opcodes as stream violations.
var exportedv2EventFDCounts = map[uint16]int{
	0: 0,
}

// ExportedV2DestroyRequest unexport the exported surface.
//
// Revoke the previously exported surface. This invalidates any
// relationship the importer may have set up using the xdg_imported created
// given the handle sent via xdg_exported.handle.
type ExportedV2DestroyRequest struct {
}

func (r *ExportedV2DestroyRequest) Opcode() uint16 { return ExportedV2RequestDestroy }

func (r *ExportedV2DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *ExportedV2DestroyRequest) Since() uint32 { return 1 }

// ExportedV2HandleEvent the exported surface handle.
//
// The handle event contains the unique handle of this exported surface
// reference. It may be shared with any client, which then can use it to
// import the surface by calling xdg_importer.import_toplevel. A handle
// may be used to import the surface multiple times.
type ExportedV2HandleEvent struct {
	// Handle the exported surface handle.
	Handle string
}

func (e *ExportedV2HandleEvent) Opcode() uint16 { return ExportedV2EventHandle }

func (e *ExportedV2HandleEvent) Unmarshal(r *wire.Reader) error {
	handle, err := r.String()
	if err != nil {
		return err
	}
	e.Handle = handle
	return nil
}

func (e *ExportedV2HandleEvent) Since() uint32 { return 1 }

// ExportedV2HandleFunc is a callback for Handle events.
type ExportedV2HandleFunc func(ev ExportedV2HandleEvent)

// ExportedV2 an exported surface handle.
//
// An xdg_exported object represents an exported reference to a surface. The
// exported surface may be referenced as long as the xdg_exported object not
// destroyed. Destroying the xdg_exported invalidates any relationship the
// importer may have established using xdg_imported.
type ExportedV2 struct {
	proxy *wayland.Proxy
}

// NewExportedV2 wraps p in a ExportedV2 proxy.
func NewExportedV2(p *wayland.Proxy) *ExportedV2 {
	p.SetEventFDCounts(exportedv2EventFDCounts)
	return &ExportedV2{proxy: p}
}

// Proxy returns the underlying Wayland proxy.
func (o *ExportedV2) Proxy() *wayland.Proxy {
	return o.proxy
}

// OnHandle registers fn to receive Handle events.
func (o *ExportedV2) OnHandle(fn ExportedV2HandleFunc) {
	o.proxy.RegisterEvent(ExportedV2EventHandle, func(r *wire.Reader) {
		var ev ExportedV2HandleEvent

		if err := ev.Unmarshal(r); err != nil {
			o.proxy.Conn().FailEvent("Handle", err)
			return
		}

		fn(ev)
	})
}

// Destroy unexport the exported surface.
//
// Revoke the previously exported surface. This invalidates any
// relationship the importer may have set up using the xdg_imported created
// given the handle sent via xdg_exported.handle.
func (o *ExportedV2) Destroy() error {
	if o.proxy.Deleted() {
		return nil
	}
	if err := o.proxy.SendRequest(ExportedV2RequestDestroy, &ExportedV2DestroyRequest{}); err != nil {
		return err
	}
	o.proxy.Conn().UnregisterProxy(o.proxy.ID())
	return nil
}

// BindExportedV2 binds the zxdg_exported_v2 global advertised by the server.
// version is the version requested by the application; it must be within
// [1, VersionExportedV2] or ErrVersionMismatch is returned. Servers newer
// than this library may advertise a higher version: clamp the advertised
// version with the builtin min, e.g. BindExportedV2(reg, name, min(g.Version,
// VersionExportedV2)), to bind at the highest mutually supported version.
func BindExportedV2(b wayland.Binder, name uint32, version uint32) (*ExportedV2, error) {
	if version < 1 || version > VersionExportedV2 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceExportedV2, version)
	if err != nil {
		return nil, err
	}
	x := NewExportedV2(p)
	x.proxy.SetVersion(version)
	return x, nil
}
