// Code generated by wayland-scanner. DO NOT EDIT.

package extforeigntoplevellist

import (
	"github.com/xogas/wayland"
	"github.com/xogas/wayland/wire"
)

const InterfaceForeignToplevelListV1 = "ext_foreign_toplevel_list_v1"
const VersionForeignToplevelListV1 = 1

const (
	ForeignToplevelListV1RequestStop    uint16 = 0
	ForeignToplevelListV1RequestDestroy uint16 = 1
)

const (
	ForeignToplevelListV1EventToplevel uint16 = 0
	ForeignToplevelListV1EventFinished uint16 = 1
)

type ForeignToplevelListV1StopRequest struct {
}

func (r *ForeignToplevelListV1StopRequest) Opcode() uint16 { return ForeignToplevelListV1RequestStop }

func (r *ForeignToplevelListV1StopRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *ForeignToplevelListV1StopRequest) Since() int { return 1 }

type ForeignToplevelListV1DestroyRequest struct {
}

func (r *ForeignToplevelListV1DestroyRequest) Opcode() uint16 {
	return ForeignToplevelListV1RequestDestroy
}

func (r *ForeignToplevelListV1DestroyRequest) Marshal(w *wire.Writer) error {
	return nil
}

func (r *ForeignToplevelListV1DestroyRequest) Since() int { return 1 }

type ForeignToplevelListV1ToplevelEvent struct {
	Toplevel wire.NewID
}

func (e *ForeignToplevelListV1ToplevelEvent) Opcode() uint16 {
	return ForeignToplevelListV1EventToplevel
}

func (e *ForeignToplevelListV1ToplevelEvent) Unmarshal(r *wire.Reader) error {
	toplevel, err := r.NewID()
	if err != nil {
		return err
	}
	e.Toplevel = toplevel
	return nil
}

func (e *ForeignToplevelListV1ToplevelEvent) Since() int { return 1 }

type ForeignToplevelListV1FinishedEvent struct {
}

func (e *ForeignToplevelListV1FinishedEvent) Opcode() uint16 {
	return ForeignToplevelListV1EventFinished
}

func (e *ForeignToplevelListV1FinishedEvent) Unmarshal(r *wire.Reader) error {
	return nil
}

func (e *ForeignToplevelListV1FinishedEvent) Since() int { return 1 }

type ForeignToplevelListV1ToplevelFunc func(ev ForeignToplevelListV1ToplevelEvent)

type ForeignToplevelListV1FinishedFunc func(ev ForeignToplevelListV1FinishedEvent)

type ForeignToplevelListV1 struct {
	proxy *wayland.Proxy
}

func NewForeignToplevelListV1(p *wayland.Proxy) *ForeignToplevelListV1 {
	return &ForeignToplevelListV1{proxy: p}
}

func (o *ForeignToplevelListV1) Proxy() *wayland.Proxy {
	return o.proxy
}

func (o *ForeignToplevelListV1) OnToplevel(fn ForeignToplevelListV1ToplevelFunc) {
	o.proxy.RegisterEvent(ForeignToplevelListV1EventToplevel, func(r *wire.Reader) {
		var ev ForeignToplevelListV1ToplevelEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ForeignToplevelListV1) OnFinished(fn ForeignToplevelListV1FinishedFunc) {
	o.proxy.RegisterEvent(ForeignToplevelListV1EventFinished, func(r *wire.Reader) {
		var ev ForeignToplevelListV1FinishedEvent
		if err := ev.Unmarshal(r); err != nil {
			return
		}
		fn(ev)
	})
}

func (o *ForeignToplevelListV1) Stop() error {
	return o.proxy.SendRequest(ForeignToplevelListV1RequestStop, &ForeignToplevelListV1StopRequest{})
}

func (o *ForeignToplevelListV1) Destroy() error {
	return o.proxy.SendRequest(ForeignToplevelListV1RequestDestroy, &ForeignToplevelListV1DestroyRequest{})
}

func BindForeignToplevelListV1(b wayland.Binder, name uint32, version uint32) (*ForeignToplevelListV1, error) {
	if version < 1 || version > VersionForeignToplevelListV1 {
		return nil, wayland.ErrVersionMismatch
	}
	p, err := b.Bind(name, InterfaceForeignToplevelListV1, version)
	if err != nil {
		return nil, err
	}
	x := NewForeignToplevelListV1(p)
	x.proxy.SetVersion(version)
	return x, nil
}
